### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by mskelton** [one-dark/jetbrains-one-dark-theme#1]
I would like to go through these languages to make sure the theme matches as closely as possible to the original Atom theme, varying where it make sense.  This does not mean these languages aren't supported, but the syntax highlighting for them could definitely be improved.

**IntelliJ Languages/Frameworks**

- [x] Java #7
- [x] Groovy #10 
- [x] JSON #10 
- [x] YAML #10 
- [x] EditorConfig #10 
- [x] Cucumber #10 
- [x] HTML #10 
- [x] Dockerfile
- [x] JavaScript #11 
- [x] Kotlin #11 
- [x] TypeScript #11 
- [x] CSS #11 
- [x] Markdown #12 
- [x] Properties #12 
- [x] Angular #12 
- [x] XML #12 
- [x] Database #12 
- [x] RegExp #12 
- [x] HTTP Request
- [x] JPA/Hibernate QL
- [x] JSP #13 
- [x] Table diff
- [x] Sass #13 
- [x] OSGi Manifest #13 
- [x] XPath #13 
- [x] XSLT
- [x] Less #13 
- [x] Spy-js

**Comment by dacoto** [comment]
When do you think the new version will be ready?
