### ISSUE TITLE
Project window not showing color correctly

### ISSUE THREAD

**Issue by mskelton** [one-dark/jetbrains-one-dark-theme#100]
From this review comment on the plugin page.

> I like it but don't understand why my project window still has a puke grey background that doesn't match the screenshot here.

**Comment by mskelton** [comment]
Issue 100!  💯

**Comment by dbrennan** [comment]
Hi Mark & thanks for opening an issue! (#100!)
I'm on IntelliJ 2019.2.4 Community. 
I installed the theme and restarted, but the project panel doesn't have dark as background as I'd expect.
![image](https://user-images.githubusercontent.com/7130461/68328553-60ec3f80-0084-11ea-832e-6dca7bb81b27.png)

**Comment by mskelton** [comment]
After installing the theme, did you follow the steps to configure it as documented here?

https://one-dark.gitbook.io/jetbrains/the-basics/installation#plugin-marketplace-recommended

The key part of those steps is to go to `Preferences | Appearance & Behavior | Appearance` and select the theme from the list.

**Comment by dbrennan** [comment]
That was it, I had similar settings already applied and thought it switched when installed. 
User error, sorry about that.

**Comment by mskelton** [comment]
No problem, glad that it is working now!
