### ISSUE TITLE
What font do you use?

### ISSUE THREAD

**Issue by Wjinlei** [one-dark/jetbrains-one-dark-theme#102]
https://plugins.jetbrains.com/files/11938/screenshot_19494.png What font is used in this picture? Can you tell me

**Comment by mskelton** [comment]
The font I'm using is called [Operator Mono ScreenSmart](https://www.typography.com/fonts/operator/styles/operatormonoscreensmart).  I also use the [Operator Mono Lig](https://github.com/kiliman/operator-mono-lig) project on GitHub which adds ligatures to the font.

It is a paid font and is pretty pricy but here are some good alternatives:

- [Dank Mono](https://dank.sh)
- [Fira Code](https://github.com/tonsky/FiraCode)

**Comment by mskelton** [comment]
I've been asked this a number of times, so thanks to your question I decided to create an AMA where I can log questions like this that I get asked frequently.  Check out issue number 1 which is your question!!

https://github.com/mskelton/ama/issues/1
