### ISSUE TITLE
Trying to update the plugin kills the IDE !

### ISSUE THREAD

**Issue by astrolemonade** [one-dark/jetbrains-one-dark-theme#103]
**Describe the bug**

I started Clion IDE and I saw that there is an update available for the One dark package theme. I went to the plugin section and after I clicked update the IDE froze for all
**Expected behavior**
Clean and fluent update process

**Actual behavior**
Full freeze on the IDE and RAM hogging
**Screenshots**

Here is a stacktrace:
https://pastebin.com/hqQwmH5j

**Comment by mskelton** [comment]
@cata0309 Can you try uninstalling and re-installing the theme?

**Comment by astrolemonade** [comment]
It freezes the IDE at uninstalling too.It hangs on uninstalling and it doesn't uninstall. (It doesn't happen with other plugins, I can install them and uninstall them as many times I want)

**Comment by mskelton** [comment]
The updates are working fine for me on IntelliJ so I'll need download CLion and give it a shot.  In the mean time, what CLion and OS versions are you on?

**Comment by astrolemonade** [comment]
I am using CLion 2019.3 latest EAP build 193.5096.27 and I am using Linux(distribution Solus 4 Fortitude)

**Comment by mskelton** [comment]
I tested in CLion and IntelliJ EAP with no issues so my assumption is this is an issue with the IDE itself, not the theme.  I would recommend reaching out to JetBrains support and see if they can help out.

**Comment by astrolemonade** [comment]
I understand, thank you for helping me find out what is causing the bug
