### ISSUE TITLE
Go colors are broken again

### ISSUE THREAD

**Issue by Defman21** [one-dark/jetbrains-one-dark-theme#104]
#74 again. This time in 2019.3 Beta

**Comment by mskelton** [comment]
I'll see what I can find and release a patch.

**Comment by mskelton** [comment]
So, I'm encountering some really odd behavior in the EAP build.  First of all, it doesn't quit when pressing command Q on mac which is odd and my first red flag.  Once I made the changes and built a new set of theme files, I noticed that it wasn't recognizing the changes I made.  So while the theme.xml files had the correct tokens, GoLand EAP wasn't picking them up thus resulting in the colors acting odd.  I'm going to file an issue with JetBrains and see if we can get this sorted out.

**Comment by mskelton** [comment]
JetBrains issue here: https://youtrack.jetbrains.com/issue/GO-8365

**Comment by mskelton** [comment]
Looks like the issue was already reported here: https://youtrack.jetbrains.com/issue/GO-8117.  I'll keep this issue open for tracking purpose, but at the moment there is nothing I'll be able to do about it 😢

**Comment by Defman21** [comment]
Yeah I saw that. Thank you anyway!

**Comment by mskelton** [comment]
I'm going to close this since it will probably be fixed without any change to the plugin in the next version.

**Comment by petrjahoda** [comment]
Solution I found: after installing the theme:
1. Go to Editor-> Color Scheme, export the theme.
2. Restart
3. After that go back to Editor -> Color Scheme and select that exported theme and restart
4. After that bot UI and editor is in one dark mode
