### ISSUE TITLE
Color scheme changing after each update

### ISSUE THREAD

**Issue by mskelton** [one-dark/jetbrains-one-dark-theme#107]
From review

> would be really really really nice if it didn't change the code colour scheme every time it updates / does anything. i have to keep switching back to my own colour scheme after every burp the theme makes.

https://plugins.jetbrains.com/plugin/11938-one-dark-theme/reviews#review=36495

**Comment by mskelton** [comment]
I'm not sure I fully understand the issue and I would appreciate some additional context.  Is the review suggesting that the color scheme is getting set to something other than One Dark after each update?  Or do you have custom theme settings that override the default settings which get cleared after each update?  Thanks!

**Comment by mskelton** [comment]
Closing due to lack of response from the review author.

**Comment by petrjahoda** [comment]
I will describe the problem better.
1. install the theme ... everything is OK
2. restart jetbrains product
3. after restart... UI is in one dark mode, that is good, but editor is not in one dark mode

Solution I found: after installing the theme:
1. Go to Editor-> Color Scheme, export the theme.
2. Restart
3. After that go back to Editor -> Color Scheme and select that exported theme and restart
4. After that bot UI and editor is in one dark mode
