### ISSUE TITLE
Help wanted! Theme maintainers

### ISSUE THREAD

**Issue by mskelton** [one-dark/jetbrains-one-dark-theme#108]
When I created this theme at the beginning of this year, I had no idea that it would grow to the popularity that it has.  I'm still blown away that there are over 250,000 downloads of this theme and before I continue let me thank everyone who has contributed to this project through issues and pull requests.  Your contributions have been vital in keeping this project moving!

That said, I'm undergoing a shift in my development career and I see myself using JetBrains products far less than I have been this past year.  As a result, my involvement in maintaining this theme will not be as active as it has been previously as I will not be using IntelliJ every day.  **This is where I'm looking for help.**  I would so greatly appreciate if someone who is passionate about keeping this project alive would be able to join the effort of maintaining this theme and adding new features as they are made available by JetBrains.

**Please note: I do still intend to support this theme with bug fixes as necessary, however new features and enhancements will likely be fewer in number due to my lack of daily exposure to IntelliJ.**

If you are interested in helping with this effort, feel free to either comment on this issue or email me directly at mdskelton99@gmail.com.

Thanks again!

**Comment by Unthrottled** [comment]
Hey! I wouldn't mind helping out where I can. What's another 4 themes?

I also wanted to run a feature idea by you, for the users on MacOS.

_Feature request moved to issue #111 (@mskelton)_

**Comment by mskelton** [comment]
@cyclic-reference Thanks for volunteering to help out!  In what ways would you be most interested in helping?  Fixing bugs?  Adding new features?  Something else?

Regarding the feature request, I'm going to move that to a separate issue to keep this issue focused on it's topic.  Thanks for bringing it up though!

**Comment by Unthrottled** [comment]
I'd be happy to help fix bugs and add features. I do plan on continuing to use JetBrains products, so I can pitch in when they change stuff or add new things.

**Comment by mskelton** [comment]
@cyclic-reference Awesome!! Let me know if there is any information I can share that would be helpful!

**Comment by Unthrottled** [comment]
@mskelton Yeah, I was curious if this code base has all of the stuff for the themes. I took a peek at https://github.com/one-dark/jetbrains-one-dark-theme/tree/master/src/main/resources/themes and there is only one theme definition. Where are the others and the color xml files?

**Comment by mskelton** [comment]
I set this theme up with a bunch of scripts to make development easier so instead of maintaining a bunch of theme files, we only have to maintain one and then the script will do the heavy lifting to create all the variants.

You'll want to checkout the [scripts directory](https://github.com/one-dark/jetbrains-one-dark-theme/tree/master/scripts) as it has the scripts for building the theme, generating readme, generating changelog, etc.

**Comment by Unthrottled** [comment]
That is awesome! I'll have to look at that a bit more once I get some time.
