### ISSUE TITLE
menu separators might look better

### ISSUE THREAD

**Issue by vandriesh** [one-dark/jetbrains-one-dark-theme#109]
if I use ascii to draw to describe the issue (bg than might be wrong color)
e.g. 
```
New       <- very dark bg
--------  <- dark bg - it can (should) also be as menu item's bg
======    <- gray bg
--------  <- dark bg - it can (should) also be as menu item's bg
Cut       <- very dark bg
Copy      <- very dark bg
```

**Comment by mskelton** [comment]
I'm assuming you are referring to the menu separators of the IDE itself, correct?  If so, I'm assuming this is managed by the OS itself and outside of the control of this theme.

**Comment by mskelton** [comment]
Closing as this is not an issue with this theme.
