### ISSUE TITLE
Why colors do not match? 

### ISSUE THREAD

**Issue by IlyaVorozhbit** [one-dark/jetbrains-one-dark-theme#110]
Hello! I have install your theme, but I cant understand why colors from screenshots from your site / phpstorm marketplace are different from my:

Your screenshot:
![image](https://user-images.githubusercontent.com/5056861/70413841-6fee5500-1a69-11ea-8c73-6d470d36a05f.png)

My screenshot:
![Screenshot from 2019-12-09 09-45-05](https://user-images.githubusercontent.com/5056861/70413736-27cf3280-1a69-11ea-8961-2842d8bc5ebd.png)

Help me please :)

**Comment by mskelton** [comment]
It might be that you are looking at the screenshots for the vivid variant but you have the normal variant selected.  Take a look at the [Setup documentation](https://github.com/one-dark/jetbrains-one-dark-theme#setup) to see how to select the vivid variant.

**Comment by mskelton** [comment]
Closing due to lack of response

**Comment by IlyaVorozhbit** [comment]
Sorry for long response, it's already vivid variant. Don't know, it could be problem with font

**Comment by Unthrottled** [comment]
@mskelton Did you have a custom font set when you took those screenshots? The colors appear to be adhering to the palette.

**Comment by mskelton** [comment]
The font I use is Operator Mono Ssm but the colors look the same if I switch to Monaco.

<img width="812" alt="2019-12-16_17-58-22" src="https://user-images.githubusercontent.com/25914066/70953039-bd506080-202d-11ea-9e70-ed89b622be98.png">

**Comment by IlyaVorozhbit** [comment]
No, unfortunately, don't solve problem. You can close issue :(

**Comment by petrjahoda** [comment]
Solution I found: after installing the theme:
1. Go to Editor-> Color Scheme, export the theme.
2. Restart
3. After that go back to Editor -> Color Scheme and select that exported theme and restart
4. After that bot UI and editor is in one dark mode
