### ISSUE TITLE
MacOS title bar

### ISSUE THREAD

**Issue by mskelton** [one-dark/jetbrains-one-dark-theme#111]
From @cyclic-reference

I wanted to run a feature idea by you, for the users on MacOS.

It would make the title bar go from this:

<img width="1322" alt="Screen Shot 2019-12-15 at 3 17 56 PM" src="https://user-images.githubusercontent.com/15972415/70869282-f2d24c80-1f4e-11ea-8963-79fac807f965.png">

To this:

<img width="1309" alt="Screen Shot 2019-12-15 at 3 13 01 PM" src="https://user-images.githubusercontent.com/15972415/70869286-fc5bb480-1f4e-11ea-8ce2-125511ce21c6.png">

**Comment by mskelton** [comment]
@cyclic-reference I didn't realize this was possible to do, but I absolutely love the idea!  Is there a setting we could change to make this possible?

**Comment by Unthrottled** [comment]
It is not an out of the box feature you can get with native theme stuff. So some UI code will have to be written. 

One of the things to keep in mind is that if it is introduced, the plugin looses it's ability to be _instantly installed_. Where somebody who downloads the plugin gets the one dark theme applied right away. New and existing users will have to restart the IDE to consume any new updates.  At least that is what I am assuming, I have not tested that out yet.

**Comment by mskelton** [comment]
Interesting.  Is there another theme that does this that you could point me to so I can get up to speed on this?  Thanks!

**Comment by Unthrottled** [comment]
Alright, so I just thought of something that would not require any changes to this code base. 

If a _separate_ plugin that was built with the required components, then that separate plugin can be installed and then the title bar functionality can exist for many themes. This way all the other themes, including this one, can remain the same and I do not have to pepper that code all over the place.

Sorry for not thinking this out very far before blurting out a feature request!

**Comment by mskelton** [comment]
Not a problem for the feature request and I love the idea of making it a separate plugin for better shareability 🙂 

Should we keep this issue open or close it?

**Comment by Unthrottled** [comment]
You can close it. Also, if you are curious, once I get something around I can let you know.

**Comment by mskelton** [comment]
Yes!  I'd love to see what you put out there as I'm sure I'll want to install it!

**Comment by Unthrottled** [comment]
@mskelton So I got something put together
https://github.com/cyclic-reference/themed-components/tree/master

I have the plugin attached to the release, if you wanted to give it a spin. I'll eventually get around to publishing it to the market place.
