### ISSUE TITLE
Broken git commit window

### ISSUE THREAD

**Issue by mikejav** [one-dark/jetbrains-one-dark-theme#112]
When I open the git commit window (CTRL+K) I see broken theme in it.
OS: Manjaro, Ubuntu 18.04 LTS. Both on Gnome
![image](https://user-images.githubusercontent.com/25515470/70925318-5336bc00-202b-11ea-94e1-4fc42a0ca0ae.png)

**Comment by Unthrottled** [comment]
Hey! I am having issues replicating the issue could you do this for me?

Please go to *Help -> About* and copy the infos

It should look something like this.

```
IntelliJ IDEA 2019.3.1 (Community Edition)
Build #IC-193.5662.31, built on December 10, 2019
Runtime version: 11.0.2+7-LTS amd64
VM: OpenJDK 64-Bit Server VM by Azul Systems, Inc.
Linux 4.15.0-72-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 512M
Cores: 12
Registry: java.completion.argument.hints.internal=false
Non-Bundled Plugins: com.markskelton.one-dark-theme
````

In addition could you attach the `idea.log` for me please?

You can find it at *Help -> Show Log in Files*

**Comment by mikejav** [comment]
```
WebStorm 2019.3
Build #WS-193.5233.80, built on November 25, 2019
Licensed to ------------- / Michał Jaworski
You have a perpetual fallback license for this version
Subscription is active until December 3, 2020
Runtime version: 11.0.4+10-b520.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.0.0-37-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1960M
Cores: 4
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.codota.csp.intellij, com.markskelton.one-dark-theme
```
I noticed that this bug may have something to do with turning off all the colors in the GIT tree.
Settings -> Version Control -> File Status Colors

![image](https://user-images.githubusercontent.com/25515470/70971870-3f7a6c80-20a2-11ea-9793-c00a8bd0c230.png)

**Comment by mikejav** [comment]
My idea.log file weighs 3.5MB, I will try to review it later, because it may contain sensitive data of my company.
Or best of all I will send a file from my home computer (on Manjaro) where I only develop not significant personal projects :)

**Comment by mikejav** [comment]
I added it to this repo:
https://github.com/mikejav/webstorm-logs

**Comment by Unthrottled** [comment]
Hey Friend! Thank you for your efforts!

So I was able to replicate this without having the one dark theme installed. 
Turns out it is not the theme's issue but an issue with the platform itself. You where right about the correlation between the vcs colors and it being broken! 

There is already an issue submitted, you can follow it there :)
https://youtrack.jetbrains.com/issue/IDEA-228312

**Comment by mskelton** [comment]
@cyclic-reference Nice find!!  Since the issue is with the IDE itself, I'll close this issue.
