### ISSUE TITLE
Issue with code highlighting

### ISSUE THREAD

**Issue by visini** [one-dark/jetbrains-one-dark-theme#115]
Since 2019.3.1 code highlighting seems to be broken on mac, I only get weird colors.

**Comment by mskelton** [comment]
Can you provide a screenshot?  Thanks!

**Comment by Unthrottled** [comment]
Hey! I am having issues replicating the issue could you do this for me?

Please go to *Help -> About* and copy the infos

It should look a little something like this.

```
IntelliJ IDEA 2019.3.1 (Community Edition)
Build #IC-193.5662.31, built on December 10, 2019
Runtime version: 11.0.2+7-LTS amd64
VM: OpenJDK 64-Bit Server VM by Azul Systems, Inc.
Linux 4.15.0-72-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 512M
Cores: 12
Registry: java.completion.argument.hints.internal=false
Non-Bundled Plugins: com.markskelton.one-dark-theme
````

**Comment by visini** [comment]
Thank you for your reply. See below:

```
PyCharm 2019.3.1 (Professional Edition)
Build #PY-193.5662.61, built on December 18, 2019
Licensed to ...
Subscription is active until September 20, 2020
For educational use only.
Runtime version: 11.0.5+10-b520.17 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: 
Non-Bundled Plugins: com.markskelton.one-dark-theme
```

![wed](https://i.imgur.com/x7goCIa.png)

**Comment by visini** [comment]
I found some further info, seems the color scheme of the theme is somehow not persistent. This is what I did: 

1. Open PyCharm: The colors are a mix between One Dark theme and Darcula.
2. Uninstall One Dark theme and restart PyCharm.
3. Install One Dark theme: The colors are displayed correctly. 
4. After closing and reopening PyCharm, the colors are changed back to a mix between One Dark theme and Darcula.

What do you suggest? I would very much like to fix this issue so I can enjoy your beautiful theme again. Thank you very much for your help and for your stellar work.

**Comment by Unthrottled** [comment]
Hey Friend! So I was able to reproduce and fix the issue. 

Until @mskelton is able to release the fix, you can manually install the plugin.

You can find the binary attached to this release
https://github.com/one-dark/jetbrains-one-dark-theme/releases/tag/v3.3.2

You can follow the instructions for manual install here
https://one-dark.gitbook.io/jetbrains/the-basics/installation#manual

**Comment by mskelton** [comment]
[v3.3.2](https://github.com/one-dark/jetbrains-one-dark-theme/releases/tag/v3.3.2) just released.  It will be a day or two before JetBrains approves the plugin and it is available.

**Comment by mindyourlifeguide** [comment]
> [v3.3.2](https://github.com/one-dark/jetbrains-one-dark-theme/releases/tag/v3.3.2) just released. It will be a day or two before JetBrains approves the plugin and it is available.

I just got update 3.3.2.
After updating and restarting, my color scheme was lost. Instead, Darcula became. I switched back to One Dark, but all my custom settings were gone.
Previously, when updating, all my settings were saved.
Can this be fixed somehow?
I have a backup of the system, so I can restore everything. But I will not install the update then.

**Comment by Unthrottled** [comment]
@mindyourlifeguide I had the same thing happen to me.

1. Updated Plugin (Color scheme went back to darcula)
1. Restarted IDE
1. Changed Look and feel to Darcula
1. Changed look and feel back to previous one dark

I'll try and see why this is acting silly.

**Comment by Unthrottled** [comment]
Okay, so I think it is an issue with the IDE's live update, when I get time I can submit an issue back to jetbrains.

**Comment by mindyourlifeguide** [comment]
@cyclic-reference I rolled back the system, copied my `.WebStorm2019.3 / config / colors / _ @ user_One Dark.icls` file and updated the plugin. Everything repeated. But I just threw my file back again and it worked.

**Comment by visini** [comment]
Updating to [v3.3.2](https://github.com/one-dark/jetbrains-one-dark-theme/releases/tag/v3.3.2) fixed the issue for me. Thank you very much for your help!

**Comment by mskelton** [comment]
@visini Would you be willing to update your review on the plugin site now that the issue has been resolved?  Thanks!

**Comment by visini** [comment]
Of course, I already updated it. Thanks for your help!

**Comment by mindyourlifeguide** [comment]
Today I received a notification about the available update OneDark
Just in case, I made a backup of the settings, updated and my color scheme was again lost.
