### ISSUE TITLE
Issue with code highlighting in Rubymine 2019.3.1 and 2019 3.2 RC

### ISSUE THREAD

**Issue by xelarion** [one-dark/jetbrains-one-dark-theme#120]
I get weird colors in Rubymine 2019.3.1.
As the first picture shows：
![rubymine-issue](https://user-images.githubusercontent.com/28296509/72802156-1db66b80-3c86-11ea-9ccc-3876ac67d5c3.png)

The second picture is expected：

![rubymine-right](https://user-images.githubusercontent.com/28296509/72802822-97028e00-3c87-11ea-95fa-9ef8d63e268c.png)

**Comment by mskelton** [comment]
Ugh, I believe these are all related to https://youtrack.jetbrains.com/issue/GO-8117.  I know the solution but I was hoping it was less widespread, but it seems to be an issue for all IDEs.  I'll be publishing an update which updates all the IDEs to hopefully fix this wholesale.

Thanks for reporting this!

**Comment by mskelton** [comment]
@all-contributors add @XanderCheung to bugs

**Comment by mskelton** [comment]
This should be fixed in [3.3.4](https://github.com/one-dark/jetbrains-one-dark-theme/releases/tag/v3.3.4).  If you still have problems, please let me know.
