### ISSUE TITLE
my color scheme was again lost

### ISSUE THREAD

**Issue by mindyourlifeguide** [one-dark/jetbrains-one-dark-theme#121]
Today I received a notification about the available update OneDark
Just in case, I made a backup of the settings, updated and my color scheme was again lost.

_Originally posted by @mindyourlifeguide in https://github.com/one-dark/jetbrains-one-dark-theme/issues/115#issuecomment-576706054_

**Comment by mskelton** [comment]
What editor are you using?  From your comments I assume Webstorm but I want to make sure.

**Comment by mindyourlifeguide** [comment]
> What editor are you using? From your comments I assume Webstorm but I want to make sure.

I apologize for not taking so long to answer.
Yes, I use Webstorm.


`WebStorm 2019.3.2
Build #WS-193.6015.40, built on January 21, 2020
Subscription is active until July 26, 2020
Runtime version: 11.0.5+10-b520.30 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.4.13-3-MANJARO
GC: ParNew, ConcurrentMarkSweep
Memory: 2000M
Cores: 4
Registry: ide.balloon.shadow.size=0, completion.stats.show.ml.ranking.diff=true
Non-Bundled Plugins: BashSupport, ImportCost, Key Promoter X, com.chrisrm.idea.MaterialThemeUI, com.deadlock.scsyntax, com.intellij.react.css.modules, com.jinsihou.react.snippets, com.mallowigi.imageicon, com.markskelton.one-dark-theme, com.softwareco.intellij.plugin, com.suming.react.PropTypes, com.tobszarny.activetabhighlighter.plugin.id, com.upsolver.PreCommitHook, com.vladsch.idea.multimarkdown, com.wakatime.intellij.plugin, com.wix.eslint, com.xcodersteam.idea.plugins.mkupscss, commit-template-idea-plugin, in.thekalinga.snippet.intellij, io.github.qeesung.component.HighlightBracketPair, izhangzhihao.rainbow.brackets, mobi.hsz.idea.gitignore, net.seesharpsoft.intellij.plugins.file-preview, org.intellij.plugins.postcss, quokka.js, ru.adelf.idea.dotenv, socrates.tabshifter, tanvd.grazi, zielu.gittoolbox`

**Comment by mskelton** [comment]
This should be fixed in [3.3.4](https://github.com/one-dark/jetbrains-one-dark-theme/releases/tag/v3.3.4).  If you still have problems, please let me know.

**Comment by mindyourlifeguide** [comment]
> This should be fixed in [3.3.4](https://github.com/one-dark/jetbrains-one-dark-theme/releases/tag/v3.3.4). If you still have problems, please let me know.

With update 3.3.4, the theme did not reset to darcula. And this is already good. But the reset of my customized colors is still happening.

**Comment by mskelton** [comment]
I'm almost certain that the reset of the custom colors is not something that I can fix as the theme author.  That is something that is probably an issue with JetBrains itself.  Their method of overriding theme colors with user defined colors is pretty awful compared to other editors like VS Code which properly maintain overrides when themes are updated.  You could try filling an issue on https://youtrack.jetbrains.com/ and see what comes of it?

**Comment by mindyourlifeguide** [comment]
> I'm almost certain that the reset of the custom colors is not something that I can fix as the theme author. That is something that is probably an issue with JetBrains itself. Their method of overriding theme colors with user defined colors is pretty awful compared to other editors like VS Code which properly maintain overrides when themes are updated. You could try filling an issue on https://youtrack.jetbrains.com/ and see what comes of it?

Yes, no problem, I’ll write to them.
I already do backup settings regularly)
Thanks for your work!
