### ISSUE TITLE
when i restart webstorm theme changed

### ISSUE THREAD

**Issue by hj2060** [one-dark/jetbrains-one-dark-theme#124]
# The installation is complete
![image](https://user-images.githubusercontent.com/9586285/73818213-d99b9d00-4827-11ea-816e-932a9245f025.png)
# when i exit ide and start ide theme has changed to the following
![image](https://user-images.githubusercontent.com/9586285/73818468-6c3c3c00-4828-11ea-89cd-63207f4a43fc.png)

**Comment by mskelton** [comment]
Thanks for reporting this.  I'll take a look into this soon

**Comment by mskelton** [comment]
@hj2060 I'm not seeing this behavior.  What version of the plugin and WebStorm are you using?

**Comment by hj2060** [comment]
> @hj2060 I'm not seeing this behavior. What version of the plugin and WebStorm are you using?

webstorm version 2019.3.2  plugin version 3.3.4  maybe only me?

**Comment by mskelton** [comment]
Now I'm seeing the issue

**Comment by mskelton** [comment]
Looks like this issue should be fixed in IntelliJ 2019.3.4 (https://youtrack.jetbrains.com/issue/GO-8117).

**Comment by hj2060** [comment]
ok thanks~
