### ISSUE TITLE
Text invisible when select Open file

### ISSUE THREAD

**Issue by idontgotit** [one-dark/jetbrains-one-dark-theme#126]
I enable One Dark version 3.3.4
Pycharm 2019.3
Macos high sierra 10.13.6

This is result when i click File -> Open:

<img width="1273" alt="Screen Shot 2020-02-24 at 2 48 55 PM" src="https://user-images.githubusercontent.com/12474525/75135780-372f5500-5715-11ea-8cd2-74edea7eefc8.png">
<img width="1273" alt="Screen Shot 2020-02-24 at 2 48 55 PM" src="https://user-images.githubusercontent.com/12474525/75135816-59c16e00-5715-11ea-9ece-05737f782f5c.png">

**Comment by mskelton** [comment]
I don't see this error on my machine.  Since it is finder, this is almost certainly an IDE issue rather than a theme issue.  Closing as such.
