### ISSUE TITLE
Poor colour scheme in CLion

### ISSUE THREAD

**Issue by Rendok** [one-dark/jetbrains-one-dark-theme#127]
One dark scheme is very basic in CLion 2019.3.4 on Ubuntu 18.04.

CLion One Dark
![image](https://user-images.githubusercontent.com/39846664/76282193-296bf900-62eb-11ea-826f-2ebe4acd8313.png)

Visual Studio One Dark
![image](https://user-images.githubusercontent.com/39846664/76282228-4274aa00-62eb-11ea-8287-a6321e74ee9e.png)

**Comment by mskelton** [comment]
Not sure if this would help, but could you try uninstalling and re-installing the theme and then selecting the theme again in the appearance/color theme settings?

I tried reproducing this on my machine and I'm not noticing what you are were the highlighting doesn't work so I'm a bit puzzled by this one.

**Comment by Rendok** [comment]
Fixed it. I had an error in the CMake file that caused the problem.
