### ISSUE TITLE
Color Brightness

### ISSUE THREAD

**Issue by zPrototype** [one-dark/jetbrains-one-dark-theme#128]
Hey guys first off all you did an amazing job! I wanted to ask if you plan on making the colors brighter? They are not like on the screenshots.. there is no difference between vivid and normal

**Comment by mskelton** [comment]
Is One Dark Vivid selected in both the Appearance and Color Scheme sections?

**Comment by zPrototype** [comment]
Yes it is. added some screenshots.
![colors](https://user-images.githubusercontent.com/43825360/77374581-61ebe800-6d6b-11ea-946d-4f8281f2cca6.png)
![setting1](https://user-images.githubusercontent.com/43825360/77374587-631d1500-6d6b-11ea-93e6-d56ab554aabb.png)
![setting2](https://user-images.githubusercontent.com/43825360/77374588-631d1500-6d6b-11ea-8cdb-ca2b1e8bc13a.png)

**Comment by zPrototype** [comment]
Colors dont look as vibrant as in your screenshots. They have more of a matte pastel like feel to it.

**Comment by mskelton** [comment]
I just took a screenshot on the latest version of IntelliJ.  Here is what I got.

<img width="1344" alt="2020-03-23_21-15-05" src="https://user-images.githubusercontent.com/25914066/77381275-76b88380-6d4b-11ea-92df-562fd4401e51.png">
