### ISSUE TITLE
Color scheme partially off

### ISSUE THREAD

**Issue by HelloAndrewNgo** [one-dark/jetbrains-one-dark-theme#129]
I downloaded the plugin and can see the theme being applied, but I noticed that the color scheme is off.

As you can see the differences on the left (mine) and right (intended) sides of the photo. 
The class names, methods, and variables are all grey.

![image](https://user-images.githubusercontent.com/37164595/77863190-47839580-71d5-11ea-8e1e-8e183a009c72.png)

Any help would be appreciated! I am using IntelliJ IDEA CE

**Comment by mskelton** [comment]
Typically this is an issue with the project, especially since it shows up properly in the settings window you show on the right.  I've noticed that if my project isn't loading properly it will not show up with proper syntax highlighting.

**Comment by HelloAndrewNgo** [comment]
Hi Mark, 

Thanks for getting back to me! Project files weren't being recognized as Java because it was located outside the source root. I was able to get the syntax highlighting by relocating the files into the source root.

https://stackoverflow.com/questions/43307532/auto-errors-detection-in-intellij-idea/43319356#43319356
