### ISSUE TITLE
Support for WebStrom 2020.01

### ISSUE THREAD

**Issue by IgorPropisnov** [one-dark/jetbrains-one-dark-theme#130]
The Theme is currently not runnable with WebStorm 2020.01.

![deprecated](https://user-images.githubusercontent.com/22197464/79246488-938f3500-7e79-11ea-9efe-336ed04770ac.png)

Current WebStorm Version: 

WebStorm 2020.1
Build #WS-201.6668.106, built on April 6, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by mskelton** [comment]
From your screenshot, it looks like you are using version 3.3.3.  Version 3.3.4 is compatible with 2020.1.  Could you try updating to that version?
