### ISSUE TITLE
Colours aren't appearing correctly within Pycharm

### ISSUE THREAD

**Issue by thomasdot** [one-dark/jetbrains-one-dark-theme#131]
For me, colours are nowhere near accurate, other than splashes of blue and pink. I've attached screenshots of each.

Atom:
![atom](https://user-images.githubusercontent.com/19692934/80803581-a0ff2b80-8baa-11ea-9d8e-9c76c87cf334.png)

Pycharm:
![pycharm](https://user-images.githubusercontent.com/19692934/80803582-a3618580-8baa-11ea-8495-8eddbff5390c.png)

While I can edit most of this, my main concern is getting instance attributes coloured correctly (see lines 20 and 21), but haven't found a way to do this yet.

**Comment by mskelton** [comment]
Unfortunately, this is just a limitation of PyCharm and the scopes it defines.  I wish that PyCharm and other JetBrains IDEs had better defined scopes similar to VS Code or Atom, but they just don't.

I'd recommend opening an issue on YouTrack (https://youtrack.jetbrains.com/issues) and ask the question there about why instance attributes aren't an identified scope.

**Comment by thomasdot** [comment]
Okay thanks for the insight. Semantic formatting will help here, so there’s the trade off I suppose.
