### ISSUE TITLE
Pycharm EDU, theme contains only UI theme, the editor theme is missing

### ISSUE THREAD

**Issue by astrolemonade** [one-dark/jetbrains-one-dark-theme#136]
Hello!
I am using Pycharm EDU.
I updated One Dark to the latest version and I noticed the editor theme disappeared but the UI theme remained applied.
![image](https://user-images.githubusercontent.com/35623921/82097065-dbb8a600-970a-11ea-89f4-092c2825e749.png)
![image](https://user-images.githubusercontent.com/35623921/82097087-e5420e00-970a-11ea-9801-8095244fd201.png)
![image](https://user-images.githubusercontent.com/35623921/82097106-ea9f5880-970a-11ea-8131-c36c0af71715.png)
Theme version: One Dark 3.3.5
Pycharm Edu version:
PyCharm 2020.1 (Edu)
Build #PE-201.6668.147, built on April 10, 2020

EDIT: the previous version 3.3.4 works as expected ! Version 3.3.5 introduced the bug

**Comment by Unthrottled** [comment]
@cata0309 
Hey! So I was not able to reproduce it on PyCharm EDU, but I was able to have something like that happen on Intellij when upgrading.

It looks like the IDE has a hard time doing a hot swap of the theme. It threw this exception:

```
....
020-05-16 06:59:15,481 [136977501]  ERROR - rationStore.ComponentStoreImpl - Cannot read scheme from /themes/one_dark.xml 
java.nio.file.NoSuchFileException: /home/alex/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-1/201.7223.91.plugins/one-dark-theme/lib/one-dark-theme-3.3.4.jar
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
....
```
I was able to fix this by restarting and re-applying the theme.

Did you have something like that happen? You can check the IDE's logs via `Help -> Show log in files`

**Comment by astrolemonade** [comment]
Yes, I have. Restarting and re-applying the theme works just fine.

**Comment by mskelton** [comment]
Glad that fixed the issue!  JetBrains IDEs definitely have a lot of issues with updates randomly breaking things.  Looks like other theme authors have had the same issue:

https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000444230-ERROR-rationStore-ComponentStoreImpl-Cannot-read-scheme-from-
