### ISSUE TITLE
v4

### ISSUE THREAD

**Issue by mskelton** [one-dark/jetbrains-one-dark-theme#139]
This theme has undergone some large improvements in the past where we added additional theme variants.  While these have been great, I would love to see a more settings based approach to configuring the theme.  I did this in https://github.com/one-dark/vscode-one-dark-theme and it worked very well.  The basic idea is you have three settings (vivid, italic, and bold) and then when the settings change, you regenerate the theme files.

A few things we would need to verify to make this solution work:

1. Understand how plugin preferences work and how to listen for changes
1. Can we write the updated theme file to the file system when preferences change?
1. We would likely need to display some type of prompt to restart the IDE after changes are made to the theme.
1. Figure out what to do about the `one_dark.theme.json` file.  IntelliJ will live reload when making changes to this file which is handy when developing.  That said, we might find other ways of doing this than the current approach.

Assuming the assumptions work, I think we could take the following steps to implement this:

- [x] Create a new v4 branch to use for the next version of the theme
- [x] Rewrite the theme in Java since it will need to be able to generate the theme files at runtime
- [x] Convert the color file from YAML to something easier to parse at runtime
- [x] Create a script to pre-build the theme files in CI with a set of defaults (no italic, no vivid, no bold)
- [ ] Update docs to explain how to configure the theme.

**Comment by Unthrottled** [comment]
@mskelton 
Hey! I know that there is an `Italic` version, `regular`, and `vivid` version.
Do is there a bold version or is that mixed in with `italic`, `regular`, and `vivid`?

I just need to get an idea of what needs to be bold. Could just be as simple as making the things that are _italic_ in the `Italic` theme **bold**?

**Comment by Unthrottled** [comment]
Oh yeah, I've also got the `vivid`/`regular` setting working.

I still have quirks to fix but it looks something like this: 
![Peek 2020-05-22 19-21](https://user-images.githubusercontent.com/15972415/82717531-44030c80-9c62-11ea-90da-d9db4c61a4d2.gif)

**Comment by mskelton** [comment]
We can probably hold off on bold for the 4.0 release and do it in a 4.x release since we don't currently have a bold theme.  That said, what I did in the VS Code theme was bold function names, class names, and namespace names.

Looking really good by the way!

**Comment by mskelton** [comment]
Going to close this in favor of the other v4 issues we have already in progress.
