### ISSUE TITLE
Keywords are highlighted inside Ruby comments

### ISSUE THREAD

**Issue by hosamaly** [one-dark/jetbrains-one-dark-theme#144]
Hi. Thanks for the beautiful theme!

I noticed that some keywords are highlighted in single-line comments, which can be distracting. Block comments, however, are not affected by this issue.

Here is a screenshot from RubyMine 2020.1.1:
![image](https://user-images.githubusercontent.com/330633/82927505-b6ccfa00-9f78-11ea-870e-3d44e62b7a1a.png)

I tried to compare the configuration to a couple of other themes, but I couldn't find a relevant difference.

Your help is appreciated!

**Comment by Unthrottled** [comment]
Hello Friend! Thank you for taking the time to submit this issue.

However, this a feature of RubyMine :)

https://youtrack.jetbrains.com/issue/RUBY-17761#focus=streamItem-27-1288415.0-0

> please uncheck option Settings | Editor | General| Appearance-> Highlight RDoc and ruby syntax in comments and restart RubyMine.

![Peek 2020-05-26 17-13](https://user-images.githubusercontent.com/15972415/82955478-897e4d00-9f74-11ea-84eb-0eb6f8e064fc.gif)

Thanks!
