### ISSUE TITLE
Italic for HTML Attributes

### ISSUE THREAD

**Issue by dorudumitru** [one-dark/jetbrains-one-dark-theme#145]
Is it possible to add italics for HTML Attributes?

Example:

One Dark
![jetbrains](https://user-images.githubusercontent.com/11142539/83097808-ae2c0f00-a0b1-11ea-9a19-0624d3c32962.png)

Monokai
![jetbrains-monokai](https://user-images.githubusercontent.com/11142539/83097953-006d3000-a0b2-11ea-977c-61790e9ea95d.png)

**Comment by Unthrottled** [comment]
I like the idea, what about you @mskelton ?

**Comment by mskelton** [comment]
I'm definitely open to it.  As I mentioned in the issue you opened in the VS Code theme, I'm still waffling on if this should be a separate setting.  I'm leaning towards a separate setting, but I'm open for suggestions.

@Unthrottled Thoughts on a separate setting?  If so, this would fit well into v4.

**Comment by Unthrottled** [comment]
@mskelton  :thinking: Hmm, I can see that. I suppose if we come up with groups that can be _italicized_, then yeah, it makes sense.

**Comment by mskelton** [comment]
> I suppose if we come up with groups that can be italicized, then yeah, it makes sense.

What exactly do you mean by this?  I'm not sure I follow.

**Comment by Unthrottled** [comment]
@mskelton 

Something like:

| Groups | Style |
| --- | --- |
| Reserved Words |   _Italic_ |
| Attributes | **Bold Italic** |

Rather than have an `Italic` and a `Html Attributes Italic` just provide a group of abstractions you can apply a style to, if that makes sense.

**Comment by mskelton** [comment]
Gotcha, that makes sense.

**Comment by Unthrottled** [comment]
@mskelton Let's hold up on v4 until I get done with this feature. I'm re-imagining the current settings.

This way I don't have to write 2 migrations.

Here is the idea, it might look a bit different and with different items in the combo box.

![Screenshot from 2020-06-02 18-59-18](https://user-images.githubusercontent.com/15972415/83581049-57846200-a503-11ea-8fc1-dd99c73e7a62.png)

**Comment by mskelton** [comment]
Fancy!  Sounds good.  I'm working on migrating the CI from Travis to GitHub actions and then I'll be working on the docs.  I don't plan on releasing until I get the green light from you.

**Comment by mskelton** [comment]
Closing now that this is merged into the v4 branch.  It will be live once we finish the v4 milestone and release it.

**Comment by Unthrottled** [comment]
@mskelton Are we still doing that _all contributors_ stuff? Does it work if I ask it to do stuff?

**Comment by mskelton** [comment]
@Unthrottled Yes and yes!
