### ISSUE TITLE
Highlights when a file is opened from a Remote Host (double-click)

### ISSUE THREAD

**Issue by AlexandrDev** [one-dark/jetbrains-one-dark-theme#150]
Example: I'm open js file from Remote Host (ftp server) and syntax highlights works not correctly. But if I download file and open from local storage, highlights wokrs correctly. No functions, vars highlight. 
![2020-06-09_11-17-44](https://user-images.githubusercontent.com/7019034/84108850-044e6a00-aa43-11ea-8a58-2c13d537559d.png)
![2020-06-09_11-18-18](https://user-images.githubusercontent.com/7019034/84108853-06b0c400-aa43-11ea-817a-593602199f08.png)

**Comment by Unthrottled** [comment]
Hey friend!

This is most likely an issue with your project set up and not the plugin. 

IntelliJ Probably needs to be configured to recognize your files from your remote host as part of the sources, so it can do all the smart stuff.

Try something like this, please: https://stackoverflow.com/questions/43307532/auto-errors-detection-in-intellij-idea/43319356#43319356

**Comment by Unthrottled** [comment]
@AlexandrDev Any updates on figuring out how to add those files as known project sources?

**Comment by Unthrottled** [comment]
Considering that this is an issue with the platform itself and not the one dark theme, I am going to close this issue. 

Let me know if you need any help figuring out your issue.
