### ISSUE TITLE
Compatibility with IDEA 2020.2 (EAP)

### ISSUE THREAD

**Issue by Flixt** [one-dark/jetbrains-one-dark-theme#151]
It seems the plugin is currently not compatible with the 2020.2 version of IntelliJ IDEA (currently in EAP).
What needs to be done, to get it compatible? I would be happy to help out, but would need a   hint for a starting point.
Currently the incompatibility is, what prevents me from using 2020.2 EAP, which is not the worst thing ever. I just love the code style the this theme provides and don't want to go without it :)

**Comment by Unthrottled** [comment]
Hey Friend!

Thank your for your interest in helping! 

So to make the plugin compatible with the builds `202.* `, all that needs be done is to re-build the plugin, that will pick up the `LATEST-EAP-SNAPSHOT`.

@mskelton Do we plan on releasing any more `v3.X` versions of the plugin before `v4` ?

For the time being, if you are extra motivated and want it to work on your machine:

1. [Follow the instructions here](https://one-dark.gitbook.io/jetbrains/contributing/development) (Make sure you run gradle on Java 11)
1. Replace the last step with `./gradlew buildPlugin`
1. You can find the `zip` file in `<path-to-repo>/build/distributions/` and can install it manually [following these instructions](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk)

**Comment by mskelton** [comment]
@Unthrottled I'll kick off a release on master.

**Comment by mskelton** [comment]
Just published version 3.3.6 which should work on 2020.2

**Comment by Flixt** [comment]
Works like a charm. Thank you!
