### ISSUE TITLE
Use the GitHub release notes for the plugin changelog

### ISSUE THREAD

**Issue by mskelton** [one-dark/jetbrains-one-dark-theme#152]
Currently, we have the changelog file in the root of the repo which is used as the change notes.  However, this doesn't show up very nicely in the change notes on the plugin page: https://plugins.jetbrains.com/plugin/11938-one-dark-theme/versions

Let's update the build process to pull the change notes from the GitHub release.

**Comment by Unthrottled** [comment]
@mskelton 
I'm not quite sure I understand what problem you are trying to fix.

![Screenshot from 2020-06-20 10-05-58](https://user-images.githubusercontent.com/15972415/85204953-b147a300-b2dd-11ea-8571-d0bb00788ce8.png)

This is what it looks like right now.

**Comment by mskelton** [comment]
My thought was we really only need to include the release notes in the most recent release rather than including the last three releases.  Mostly because the "What's new" really refers to what's new in **this** release, not what's new in the **last few** releases.

**Comment by Unthrottled** [comment]
That makes sense.

I guess I'm used to publishing releases every so often. I just batch up all my small change releases and publish them every so often. Rather than publishing every time I release (which I find annoying having to constantly update a plugin I've installed :)

**Comment by mskelton** [comment]
Publishing and releasing are synonymous in this repo since creating a GitHub release will publish to the JetBrains marketplace.
