### ISSUE TITLE
Broken rendering in DB Navigator when picking a connection color

### ISSUE THREAD

**Issue by themasch** [one-dark/jetbrains-one-dark-theme#153]
When setting a color for a Connection/DB/Table some artifacts start appearing in the action bar for for the table display view of the DB Navigator: 
![grafik](https://user-images.githubusercontent.com/170171/84285204-760ade80-ab3d-11ea-8c38-51c1d6507443.png)
![grafik](https://user-images.githubusercontent.com/170171/84285397-b79b8980-ab3d-11ea-8c31-fe5acc1df727.png)

This does not happen when using the default dark thema (dracula) or when using one dark with no color set for the view. Its gone when setting it back to "no color":
![grafik](https://user-images.githubusercontent.com/170171/84285455-cb46f000-ab3d-11ea-9004-ccbaf0c3763b.png)

Have not found these errors in any other part of the software yet. 

Running PHPStorm 2020.1.1 with One Dark 3.3.6.

**Comment by Unthrottled** [comment]
Excellent find! However this is not an issue with this theme though. Please see the link below for more info. :)

https://github.com/one-dark/jetbrains-one-dark-theme/issues/116#issuecomment-568906428

**Comment by themasch** [comment]
Ah, thanks for the hint and sorry for the redundant ticket, I was looking for an existing one but guess I did not try hard enough ;) thanks!

**Comment by Unthrottled** [comment]
No worries! I'll use your, more descriptive, title for the other issue as well.
