### ISSUE TITLE
JetBrains 2019.X Bug: Settings Menu Not showing Up

### ISSUE THREAD

**Issue by Unthrottled** [one-dark/jetbrains-one-dark-theme#163]
**Describe the bug**

Settings Menu not showing up.
**To Reproduce**

1. Go to the `One Dark Theme` settings menu.

**Expected Behavior**

To be able to view the settings

**Environment**

```
IntelliJ IDEA 2019.3 (Community Edition)
Build #IC-193.5233.102, built on November 27, 2019
Runtime version: 1.8.0_252-b14 amd64
VM: OpenJDK 64-Bit Server VM by Azul Systems, Inc.
Linux 4.15.0-106-generic
GC: PS Scavenge, PS MarkSweep
Memory: 470M
Cores: 12
Registry: java.completion.argument.hints.internal=false
Non-Bundled Plugins: com.markskelton.one-dark-theme
```
Really any 193.xx build for any platform.

**Comment by Unthrottled** [comment]
[Related Stacktrace](https://sentry.io/share/issue/9d6527bd99af461195485c749b748be9/)

Unfortunately, the [Intellij Kotlin UI DSL](https://www.jetbrains.org/intellij/sdk/docs/user_interface_components/kotlin_ui_dsl.html) has breaking changes from the 2019 to 2020 builds. 

I forgot to cap the release to the 2020 builds. So anybody who is on 2019 of any product (pycharm, intellij, etc) will have this issue. I will clamp the next release to 2020, that way 2019 platforms will not receive anymore breaking updates.

Sadly, there is no good way to release a fix for this so you can get an automatic fix.

However you do have some manual workarounds available:
1.  You can upgrade your IDE to the 2020 version :grin:
1. You can follow the [manual installation steps](https://one-dark.gitbook.io/jetbrains/the-basics/installation#manual) (replacing the latest release with [v3.3.6](https://github.com/one-dark/jetbrains-one-dark-theme/releases/tag/v3.3.6))

Thank you for your patience and understanding!

**Comment by mskelton** [comment]
Could we checkout an old version of the repo and manually publish a release capped at the latest 2019 release?

**Comment by Unthrottled** [comment]
@mskelton 

I don't know how the platform updates their components, but I think it takes the highest version that is compatible with the platform. If we were to release v3.3.7 (capped at 191), I don't know if the update will take. 

It would be weird if we released 4.0.1-2019 that was only compatible with the 2019 builds only (but it might work).

**Comment by mskelton** [comment]
@Unthrottled up to you.  Feel free to publish if you want or leave it as is.

**Comment by Unthrottled** [comment]
@mskelton I'll probably just for the time being, publish a 2019.x only version (off a separate branch) that fixes the existing issues. Then I'll cap v4 to only be 2020.x after that. That way the 2019 builds will get the last one-dark update, and 2020 will be the current supported platform.

Provided it is possible to release without affecting the 2020 users.

**Comment by Unthrottled** [comment]
@mskelton I am not going to support the configurable settings for the 2019 builds. Too many API differences between 2020.

So I opted to create a 4.0.3-2019 version that:

- Has the compatibility locked from 191 to 193.*
- Has all the code from v3.3.6 (the variants and no kotlin stuff)

I made it a version higher than the current one published, so that way the users will automatically upgrade to this. I checked that 2020 builds don't pick up the changes when I have the [update plugins xml](http://jetbrains.assets.unthrottled.io/canary/updatePlugins.xml) set to the plugin range. So I'll assume that the real plugin repository will do the same thing :crossed_fingers: .

When users on the legacy platforms upgrade, whenever 4.0.4 or whatever is greater might be available so they can have a real v4. For now they will have v3 dressed up in as v4 :confounded: 

When you get the chance can you manually upload this, please? It should only be compatible only for 2019 to 2019.3.4

https://jetbrains.assets.unthrottled.io/one-dark/one-dark-theme.4.0.3-2019.zip

Thanks for helping me clean up my mess :sweat_smile:

**Comment by Unthrottled** [comment]
You can find the branch I made changes on here: https://github.com/one-dark/jetbrains-one-dark-theme/compare/v4-2019-revert

**Comment by mskelton** [comment]
Just uploaded the build.  everything looks good from the plugin page, but you may want to double check that 2020 IDEs don't get the update.

<img width="598" alt="Screen Shot 2020-07-01 at 7 40 05 AM" src="https://user-images.githubusercontent.com/25914066/86244813-22a11480-bb6e-11ea-82fa-55fb164bb002.png">

**Comment by Unthrottled** [comment]
@mskelton Thanks! That worked, the 2019 ides get the patch and the 2020 ides are not prompted to upgrade! :confetti_ball: :partying_face: 

I'll clean up the issues later today. Thanks Again :)

**Comment by Unthrottled** [comment]
Everything appears to have quieted down since the 2019 deploy. I think things may be good. I'll close this issue later this week, just in case the folks who have not upgraded know that they will need to update to the version that does not have configurable settings.

**Comment by Unthrottled** [comment]
The sentry logs are getting quite, so I think everybody is migrated over.
