### ISSUE TITLE
The plugin is conflict with Indent Rainbow.

### ISSUE THREAD

**Issue by hongsefb** [one-dark/jetbrains-one-dark-theme#169]
**Issue**
The theme plugin is conflict with Indent Rainbow. When you enable one dark theme, a pycharm plugin named Indent Rainbow doesn't work. And when you disable one dark theme in pycharm ,then Indent Rainbow works normally.

**Expected Behavior**
I expect one dark theme plugin is compatible with Indent Rainbow.

**Environment**
PyCharm 2020.1.2 (Professional Edition)
Build #PY-201.7846.77, built on June 1, 2020
Licensed to Zhang Tengfei
Subscription is active until January 24, 2021
For educational use only.
Runtime version: 11.0.7+10-b765.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 982M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: AceJump, com.intellij.plugins.vscodekeymap, com.jetbrains.colorful.toolwindow.icons, com.markskelton.one-dark-theme, indent-rainbow.indent-rainbow, io.github.qeesung.component.HighlightBracketPair, net.seesharpsoft.intellij.plugins.csv, izhangzhihao.rainbow.brackets, com.kite.intellij, com.leinardi.pycharm.pylint, some.awesome

**Screenshots**
![image](https://user-images.githubusercontent.com/29223722/86310219-11c8cf80-bc50-11ea-8c9e-9bc79ad3e5ba.png)
![image](https://user-images.githubusercontent.com/29223722/86310305-4d639980-bc50-11ea-9e51-b0df623703f5.png)

**Comment by Unthrottled** [comment]
Hey, Thanks for bringing this to my attention!

:thinking: Hmm, looks like I may need to revisit how the color themes are applied.

Until then, I have a work around you can use, if you want:

1. Navigate to the `Settings > Editor > Color Scheme`
1. If `One Dark Generated` is the current scheme then click the :gear: 
1. Select `Duplicate`
1. Apply the setting.

![Peek 2020-07-02 04-22](https://user-images.githubusercontent.com/15972415/86341362-d0b6c800-bc1b-11ea-859b-b827757c3a5d.gif)

**Comment by Unthrottled** [comment]
I decided to revert the configurable theme options in favor of a consistent and reliable theme user experience. Please upgrade to the stable v5.0.0.

I found other issues that are unacceptable to have at the moment. I will re-visit the configurable theme options in a later date, when I have more time to flesh out all of the quirks of making the platform have configurable themes. 
 
Thank you for your patience and understanding!
