### ISSUE TITLE
Theme is not working properly after the latest update

### ISSUE THREAD

**Issue by tesla1volt** [one-dark/jetbrains-one-dark-theme#172]
![one_dark_1](https://user-images.githubusercontent.com/67409062/86410043-ee614d00-bc6e-11ea-98eb-b69acf7743d2.png)
![one_dark_2](https://user-images.githubusercontent.com/67409062/86410046-f02b1080-bc6e-11ea-9703-16aafd91cf3f.png)

**Describe the bug**

Theme is broken in Intellij IDEA after updating to version 4.0.1. There is this white window color coming up in the Idea.

**To Reproduce**

1. In the Intellij IDEA for  microsoft windows install One Dark theme the version 4.0.1

**Expected Behavior**

**Environment**

**Comment by Unthrottled** [comment]
Hey! So I was able to reproduce this issue on the Mac, but not Linux. It is unreliable at the moment.

I was able to temporarily fix the white crazyness by:

1. Setting the theme to `Darcula` (it will still be white)
1. Setting the theme back to `One Dark` (Still White)
1. Restart Intellij.

Let me know if that works for you. I'll have a fix out for this some time later this week.

**Comment by Unthrottled** [comment]
If that does not work you can manually install v3.3.6.

[Here is how to manually install](https://one-dark.gitbook.io/jetbrains/the-basics/installation#manual). You can replace the `current release` with the assets from [v3.3.6](https://github.com/one-dark/jetbrains-one-dark-theme/releases/tag/v3.3.6)

Thank you for your patience and understanding.

**Comment by Unthrottled** [comment]
Related to #171

**Comment by kwiat1990** [comment]
> Hey! So I was able to reproduce this issue on the Mac, but not Linux. It is unreliable at the moment.
> 
> I was able to temporarily fix the white crazyness by:
> 
> 1. Setting the theme to `Darcula` (it will still be white)
> 2. Setting the theme back to `One Dark` (Still White)
> 3. Restart Intellij.
> 
> Let me know if that works for you. I'll have a fix out for this some time later this week.

I have that Bug on Ubuntu 18.04, so it exists on Linux as well. Your solution with switching themes did not work for me though. What bothers me is the fact that the Bug breaks now any other theme I have already installed (with new ones I didn't try) and even default themes from IntelliJ!.

**Comment by skrubbel** [comment]
I'm not sure if this part of the cause, but it appears that activating the theme results in both a "One Dark" and a "One Dark Generated" color scheme. Switching from "One Dark Generated" to "One Dark" seems to trigger an unstable color scheme e.g. I have seen the editor switch to Darcula between start-ups and getting the white "noise" UI. Also after selecting "One Dark" the "One Dark Generated" option disappear. It re-emerges when selecting Darcula and switching back to "One Dark" theme.

Both these color schemes are present in Rider too but there I have not yet seen the random activation of other schemes, when sticking to the "One Dark Generated" theme

![image](https://user-images.githubusercontent.com/868432/86437241-5c0b8880-bd04-11ea-9cc7-a6f5ff80b0c6.png)

**Comment by Unthrottled** [comment]
> I have that Bug on Ubuntu 18.04, so it exists on Linux as well.

@kwiat1990 I have seen it on my Ubuntu box as well (when developing), I just can't reliably reproduce it.

> What bothers me is the fact that the Bug breaks now any other theme I have already installed...

Who would have guessed using un-documented platform APIs would have such unintended consequences :sweat_smile:

**Comment by Unthrottled** [comment]
@skrubbel 

Thank you for the info! I have a fix that I am going to test across all environments.

This version will not set the look and feel (which causes the corruption) of the IDE to change the editor color scheme. Instead it will just replace the color scheme directly, that way the chances of the IDE messing up and becoming white is removed.

**Comment by skrubbel** [comment]
@Unthrottled 
Just installed the new version in Pycharm, and things are looking much better. I have done quite a few re-starts of Pycharm, and no quirks so far. I see the vivid & vivid italics options are back which is great. Thanks for the speedy response - Nice work!

**Comment by Unthrottled** [comment]
@skrubbel Thanks!

I decided to revert the configurable theme options in favor of a consistent and reliable theme user experience. Please upgrade to the stable v5.0.0.

 I find that this issue is unacceptable to have at the moment. I will re-visit the configurable theme options in a later date, when I have more time to flesh out all of the quirks of making the platform have configurable themes. 
 
Thank you for your patience and understanding!

**Comment by tesla1volt** [comment]
@Unthrottled 
Works with v5.0.0. Thank you for fast response.
Those options to configure themes separately was cool option thought.

**Comment by Unthrottled** [comment]
@tesla1volt 
You are welcome! Sorry for giving you a broken release. I have the separate configurations planned for a later release in the future, when I worked out all of the bugs.
