### ISSUE TITLE
syntax highlighting

### ISSUE THREAD

**Issue by Antoshkiv** [one-dark/jetbrains-one-dark-theme#177]
Will you make the theme more similar to vs code in the future?
I like your theme and webstorm but in vs code this theme is better 
syntax highlighting is better readable in vs code

<img width="870" alt="Знімок екрана 2020-07-11 о 18 21 34" src="https://user-images.githubusercontent.com/43931364/87227455-bdd28f00-c3a3-11ea-9392-bddf8e136718.png">
<img width="870" alt="Знімок екрана 2020-07-11 о 18 21 25" src="https://user-images.githubusercontent.com/43931364/87227457-c1661600-c3a3-11ea-80c0-f3d843a98517.png">
<img width="870" alt="Знімок екрана 2020-07-11 о 18 21 16" src="https://user-images.githubusercontent.com/43931364/87227458-c32fd980-c3a3-11ea-8161-311cfa7825ee.png">
<img width="752" alt="Знімок екрана 2020-07-11 о 18 21 01" src="https://user-images.githubusercontent.com/43931364/87227463-c62aca00-c3a3-11ea-9f3d-4caa3cfbc231.png">

**Comment by mskelton** [comment]
What specifically do you like about the VS Code theme?  BTW, the VS Code theme you are showing is not the one I maintain :) It must be a different one.

**Comment by Antoshkiv** [comment]
Oh sorry, I was wrong but in that theme which you support for example function setState(setLoading) is always blue it is easy to see in the code

**Comment by Unthrottled** [comment]
@Antoshkiv 
![image](https://user-images.githubusercontent.com/15972415/87353212-fd26ea00-c521-11ea-9bf3-6e48c82fbf15.png)
:point_up: Is that it or is there more? 

I haven't seen much of the VS Code theme. I do think that having a consistent experience between the IDE's is cool.

Also an example/open-source project would be most helpful.

**Comment by mskelton** [comment]
VS Code uses semantic highlighting to determine that `setLoading` is a function which is why it's colored blue.  @Unthrottled Does JetBrains handle highlighting differently?  I'm pretty sure functions in this theme are blue, so if `setLoading` isn't blue it must be how JetBrains handles highlighting.

**Comment by Antoshkiv** [comment]
@Unthrottled  you're right that's what i meant

**Comment by Unthrottled** [comment]
![image](https://user-images.githubusercontent.com/15972415/87410047-6e4eb780-c58b-11ea-9f01-7dbd8d185d01.png)

:thinking: Looks like the grammar is not that smart at the moment. It thinks that the destructured function reference is a `JS:IDENTIFIER`. So I am thinking that it is a current limitation of the platform. When the grammar evolves then we should be able to apply the appropriate colors. 

I'm not sure how much we can do on the one-dark side. I could look into what can be done to extend the grammar. However, I think that might be out of scope of what this plugin should do. It might be better as a separate component, so other themes/plugins could use it.

**Comment by Unthrottled** [comment]
![image](https://user-images.githubusercontent.com/15972415/87411880-f46bfd80-c58d-11ea-904f-1a42c6267cc8.png)

I also looked into the `cart.js`. The IDE apparently recognizes it a global variable, so it should have a color.

This is my IDE:

```
WebStorm 2020.2 Beta
Build #WS-202.6250.10, built on July 8, 2020
WebStorm EAP User
Expiration date: August 7, 2020
Runtime version: 1.8.0_252-b14 amd64
VM: OpenJDK 64-Bit Server VM by Azul Systems, Inc.
Linux 4.15.0-109-generic
GC: PS Scavenge, PS MarkSweep
Memory: 488M
Cores: 12
Non-Bundled Plugins: PsiViewer, com.markskelton.one-dark-theme
Current Desktop: ubuntu:GNOME
```

It also does the same coloring on:

```
IntelliJ IDEA 2020.2 Beta (Ultimate Edition)
Build #IU-202.6250.13, built on July 8, 2020
IntelliJ IDEA EAP User
Expiration date: August 7, 2020
Runtime version: 1.8.0_252-b14 amd64
VM: OpenJDK 64-Bit Server VM by Azul Systems, Inc.
Linux 4.15.0-109-generic
GC: PS Scavenge, PS MarkSweep
Memory: 455M
Cores: 12
Non-Bundled Plugins: com.markskelton.one-dark-theme
Current Desktop: ubuntu:GNOME
```

**Comment by Unthrottled** [comment]
@Antoshkiv Is there anything else? It currently does not look like we can do much on the theme side.

I have been checking to see if things can be changed by using the [Jump to Colors and Fonts](https://www.jetbrains.com/help/idea/configuring-colors-and-fonts.html#ddb454a0) which allows you to easily customize the coloring.

**Comment by Antoshkiv** [comment]
@Unthrottled thanks for the explanation, now i understand the problem.

**Comment by Unthrottled** [comment]
I'll see what I can do. If I can't get anything reasonable by the 25th of July, I'll close this issue.  Thank you for your suggestion!

**Comment by Unthrottled** [comment]
So I was not unsuccessful in my attempt for finding a simple solution. Thank you for the idea though, I'll keep my eye out for the feature in the future!
