### ISSUE TITLE
folder icon

### ISSUE THREAD

**Issue by AsiaChampion** [one-dark/jetbrains-one-dark-theme#182]
[Screenshots](https://github.com/one-dark/jetbrains-one-dark-theme/raw/master/docs/screenshots/default.png)
Will you tell me how to set the similar folder icon?

**Comment by Unthrottled** [comment]
I am fairly confident that it is the [Atom Material Icons Plugin](https://plugins.jetbrains.com/plugin/10044-atom-material-icons). @mskelton Is that right?

I can add that to the documentation.

**Comment by AsiaChampion** [comment]
@Unthrottled  Great! thank you very much!
