### ISSUE TITLE
Database icons have a visual glitch when db connection has a background color

### ISSUE THREAD

**Issue by jlopez-gc** [one-dark/jetbrains-one-dark-theme#183]
**Describe the bug**
The icons used to interact with a database table are not properly displayed when the database connection has a background color. (Please check screenshots to know what I mean when I say "not properly displayed")

**To Reproduce**
1. Install and activate One Dark Theme
2. Go to a database connection with a background color
3. Hover over the buttons

**Expected Behavior**
The icons should be displayed properly (Please check screenshots to know what I mean when I say "properly displayed")

**Environment**

**_OS_**
Windows 10 Pro

**_IntelliJ Product_**
IntelliJ IDEA 2020.2 (Ultimate Edition)
Build #IU-202.6397.94, built on July 27, 2020
Runtime version: 11.0.7+10-b944.20 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1960M
Cores: 12
Non-Bundled Plugins: Lombook Plugin, com.markskelton.one-dark-theme, com.intellij.kubernetes, intellij.prettierJS, aws.toolkit, org.intellij.scala, izhangzhihao.rainbow.brackets

**_Plugin Version_**
5.0.0

**Screenshots**
**_Current behaviour_**
![image](https://user-images.githubusercontent.com/1812957/89267311-f6762900-d62e-11ea-888e-1d43adba094c.png)

**_Expected behaviour_**
![image](https://user-images.githubusercontent.com/1812957/89267344-04c44500-d62f-11ea-996c-60a52d78bdd5.png)

**Comment by Unthrottled** [comment]
Thank you for taking the time to make a very descriptive and helpful issue!

However, this is not unique to this theme. It happens with all custom themes.
I filed an issue, you can track it here. Please vote for it if you can!

https://youtrack.jetbrains.com/issue/DBE-9857

Related to #153 and #116 

Maybe I should look into the fix myself sometime and submit a PR? :thinking:

**Comment by jlopez-gc** [comment]
Thanks for your fast response. Upvoted the issue, I'm very sorry for duplicating this item. My search for a related issues was not thorough enough :(

Have a nice day and keep the good work :)

**Comment by Unthrottled** [comment]
No worries and thank you for understanding!

If I can fix it myself, I'll keep you posted on the issue. Thanks!
