### ISSUE TITLE
Plugin not compatible with IntelliJ IDEA 2020.3 EAP

### ISSUE THREAD

**Issue by imranzahid01** [one-dark/jetbrains-one-dark-theme#190]
Installing the latest EAP of Intellij IDEA (2020.3) alerts the user that this theme is incompatible.
The exact error is:

Plugin 'One Dark theme' (version '5.1.0') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is IU-203.3645.34

IntelliJ IDEA 2020.3 EAP (Ultimate Edition)
Build #IU-203.3645.34, built on September 22, 2020
IntelliJ IDEA EAP User
Expiration date: October 22, 2020
Runtime version: 11.0.8+10-b1094.1 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep
Memory: 2476M
Cores: 12
Registry: debugger.watches.in.variables=false, ide.images.show.chessboard=true
Non-Bundled Plugins: com.arcticicestudio.nord.jetbrains, CheckStyle-IDEA, com.thvardhan.gradianto, net.seesharpsoft.intellij.plugins.csv

**Comment by Unthrottled** [comment]
Hey! Thanks for reporting this. `v5.1.1` has been published and is available for installation.
