### ISSUE TITLE
Remove Deprecated API Usage

### ISSUE THREAD

**Issue by Unthrottled** [one-dark/jetbrains-one-dark-theme#191]
The plugin verification step has highlighted usages of deprecated APIs. Please migrate to supported API usage.

```
Deprecated API usages (1): 
    #Deprecated constructor com.intellij.notification.NotificationGroup.<init>(String, NotificationDisplayType, boolean, String, Icon) invocation
        Deprecated constructor com.intellij.notification.NotificationGroup.<init>(java.lang.String displayId, com.intellij.notification.NotificationDisplayType displayType, boolean isLogByDefault, java.lang.String toolWindowId, javax.swing.Icon icon) is invoked in com.markskelton.notification.Notifications.<clinit>() : void
```

**Comment by Unthrottled** [comment]
Thank you stale bot, I'll look into it this weekend to see how much this reduces the compatibility range.

**Comment by Unthrottled** [comment]
@mskelton 
Just wanted to get a second opinion.

Performing this upgrade will set the lowest platform compatibility to 2020.3. [See docs if curious](https://jetbrains.org/intellij/sdk/docs/user_interface_components/notifications.html#top-level-notifications)

Just wanted to know if this is cool. It will make android studio lag behind a bit. However, I don't anticipate any new fancy features in the coming future.

**Comment by mskelton** [comment]
@Unthrottled since it is just deprecated, seems like we might want to leave it for now and remove it once it is fully removed from the platform.

**Comment by Unthrottled** [comment]
I'll just close this and it will come back when it becomes an issue due to removal.
