### ISSUE TITLE
Font shadow problem

### ISSUE THREAD

**Issue by lonely-doge** [one-dark/jetbrains-one-dark-theme#192]
![Snipaste_2020-10-12_16-01-56](https://user-images.githubusercontent.com/54979163/95720842-55e25c00-0ca4-11eb-8d0b-d5e44f630953.png)
When opening multiple files, when I hover over the redundant tabs, there will be some shadows on them, as shown in the figure

**Comment by mskelton** [comment]
I doubt this is an issue with this theme as it looks like an IDE issue.  Could you try a different theme and see if the problem persists?

**Comment by RichardConfused** [comment]
I change theme to IntelliJ Light, it's no problem

**Comment by lonely-doge** [comment]
> 
> 
> I doubt this is an issue with this theme as it looks like an IDE issue. Could you try a different theme and see if the problem persists?

I change theme to IntelliJ Light, it's no problem

**Comment by mskelton** [comment]
Interesting.  Could you try the default dark theme?  Not sure if that matters but just trying to think through all the possibilities.

**Comment by lonely-doge** [comment]
> 
> 
> Interesting. Could you try the default dark theme? Not sure if that matters but just trying to think through all the possibilities.

I change theme to Darcula, it's no problem

**Comment by Unthrottled** [comment]
This is an issue with any custom UI theme, not just One Dark. It happens only for files with custom file colors. It appears on Linux, and probably windows 10. MacOS might be fine. I'll need to test that out.

Once I get more information I can submit an issue to Jetbrains and close this issue.

It may be related to this

https://youtrack.jetbrains.com/issue/DBE-9857

**Comment by lonely-doge** [comment]
> 
> 
> This is an issue with any custom UI theme, not just One Dark. It happens only for files with custom file colors. It appears on Linux, and probably windows 10. MacOS might be fine. I'll need to test that out.
> 
> Once I get more information I can submit an issue to Jetbrains and close this issue.
> 
> It may be related to this
> 
> https://youtrack.jetbrains.com/issue/DBE-9857

but just now test Dracula theme and Solarized theme, they're ok, and there is no such problem

**Comment by Unthrottled** [comment]
> Dracula theme and Solarized

From which vendor?

I was able to reproduce with this plugin: 
https://plugins.jetbrains.com/plugin/12310-gruvbox-theme

![image](https://user-images.githubusercontent.com/15972415/95759487-60363300-0c6f-11eb-85cd-bf65a5dff839.png)

**env**
```
PyCharm 2020.2.2 (Edu)
Build #PE-202.7319.79, built on September 24, 2020
Runtime version: 11.0.8+10-b944.31 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 4.15.0-118-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Non-Bundled Plugins: com.vincentp.gruvbox-theme
Current Desktop: ubuntu:GNOME
```

**Comment by lonely-doge** [comment]
> 
> 
> > Dracula theme and Solarized
> 
> From which vendor?
> 
> I was able to reproduce with this plugin:
> https://plugins.jetbrains.com/plugin/12310-gruvbox-theme
> 
> ![image](https://user-images.githubusercontent.com/15972415/95759487-60363300-0c6f-11eb-85cd-bf65a5dff839.png)
> 
> **env**
> 
> ```
> PyCharm 2020.2.2 (Edu)
> Build #PE-202.7319.79, built on September 24, 2020
> Runtime version: 11.0.8+10-b944.31 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> Linux 4.15.0-118-generic
> GC: ParNew, ConcurrentMarkSweep
> Memory: 1979M
> Cores: 12
> Non-Bundled Plugins: com.vincentp.gruvbox-theme
> Current Desktop: ubuntu:GNOME
> ```

![图片](https://user-images.githubusercontent.com/54979163/95814429-f9874700-0d4c-11eb-9033-79144bc9fdf2.png)
> IntelliJ IDEA 2020.1.4 (Ultimate Edition)
Build #IU-201.8743.12, built on July 21, 2020
Runtime version: 11.0.7+10-b765.65 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.4lex4.intellij.solarized, Lombook Plugin, com.bruce.intellijpluin.stackoverflow, com.mallowigi, com.markskelton.one-dark-theme, com.vermouthx.idea, cn.yiiguxing.plugin.translate

- Dracula theme
![图片](https://user-images.githubusercontent.com/54979163/95814769-cf825480-0d4d-11eb-8be0-4bc220c9c1da.png)

- Solarized Dark
![图片](https://user-images.githubusercontent.com/54979163/95814796-ddd07080-0d4d-11eb-84c0-9c933b4af48b.png)

**Comment by Unthrottled** [comment]
@RichardConfused 
Thank you for the additional information.
I was able to confirm that the themes you mentioned do not have the issue.

This feels like a bug in the platform, I'll take a peek to see if there is something that can be done on the theme side to patch this issue. If not, I'll submit a bug report to Jetbrains and close this issue.

Thank you for bringing this to my attention!

**Comment by lonely-doge** [comment]
> @RichardConfused
> Thank you for the additional information.
> I was able to confirm that the themes you mentioned do not have the issue.
> 
> This feels like a bug in the platform, I'll take a peek to see if there is something that can be done on the theme side to patch this issue. If not, I'll submit a bug report to Jetbrains and close this issue.
> 
> Thank you for bringing this to my attention!

you're welcome

**Comment by Unthrottled** [comment]
@all-contributors add @RichardConfused for bugs
