### ISSUE TITLE
idea Show Diagram can not see clearly

### ISSUE THREAD

**Issue by chenchenfang** [one-dark/jetbrains-one-dark-theme#194]
**Describe the bug**
Thread class  use Show Diagram ,i cannot see clearly
![image](https://user-images.githubusercontent.com/50065243/96331916-afc39700-1093-11eb-8eb5-0db637355a9e.png)

**To Reproduce**

1.click Thread
2.Right click
3.
![image](https://user-images.githubusercontent.com/50065243/96331946-e1d4f900-1093-11eb-8979-7d71af7c03cb.png)

**Expected Behavior**

as use 
![image](https://user-images.githubusercontent.com/50065243/96331972-016c2180-1094-11eb-9588-b9ae997ea615.png)

i can see this 
![image](https://user-images.githubusercontent.com/50065243/96331975-0af58980-1094-11eb-829d-d2428c14b72f.png)

**Environment**
IntelliJ IDEA 2020.2.3 (Ultimate Edition)
Build #IU-202.7660.26, built on October 6, 2020

Subscription is active until June 26, 2021
For educational use only.
Runtime version: 11.0.8+10-b944.34 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 1450M
Cores: 8
Registry: debugger.watches.in.variables=false, compiler.automake.allow.when.app.running=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: Key Promoter X, Lombook Plugin, com.alibaba.p3c.smartfox, com.intellij.plugins.watcher, com.markskelton.one-dark-theme, io.github.qeesung.component.HighlightBracketPair, org.jetbrains.plugins.hocon, mobi.hsz.idea.gitignore, some.awesome, MavenRunHelper, org.jetbrains.kotlin, com.codota.csp.intellij, com.intellij.plugins.html.instantEditing, JRebelPlugin, org.intellij.scala, izhangzhihao.rainbow.brackets, Pythonid, cn.yiiguxing.plugin.translate, training

this is my first report bug ...
If there is something wrong, I hope to inform.
thinks

**Comment by Unthrottled** [comment]
Thank you for taking the time and making such a detailed issue! I think I have everything I need. I will look into the fix as soon as possible

**Comment by Unthrottled** [comment]
Note to self, this is a Intellij IDEA Ultimate plugin (not available in community).

**Comment by Unthrottled** [comment]
@all-contributors add @chenchenfang for bugs
