### ISSUE TITLE
Narrowed variables not being highlighted correctly

### ISSUE THREAD

**Issue by infix** [one-dark/jetbrains-one-dark-theme#198]
### Intellij light
![image](https://user-images.githubusercontent.com/40860821/101212129-e3c53c80-3680-11eb-9987-e157fe19ec91.png)
### Darcula
![image](https://user-images.githubusercontent.com/40860821/101212238-1111ea80-3681-11eb-83f8-b7b3f061bb8c.png)
### One Dark
![image](https://user-images.githubusercontent.com/40860821/101212284-2424ba80-3681-11eb-9cae-9ec5c7aad8e7.png)

expected behavior: 
`someVar` should be highlighted inside the `console.log`

Actual behavior:
No highlighting

**Comment by mskelton** [comment]
@Unthrottled Thoughts on this one?  Is the narrowing highlighting an option in IntelliJ?  If not, I would be hesitant to change it as it introduces a lot of extra highlighting and I'm not sure how much value that adds 🤔

**Comment by Unthrottled** [comment]
@mskelton 

I think it is just another thing that we can put in the editor colors `xml` file.

![image](https://user-images.githubusercontent.com/15972415/101215429-6fb87380-3643-11eb-88e1-a175f05d65de.png)

[Jump to colors and font](https://blog.jetbrains.com/phpstorm/2017/08/jump-to-colors-and-fonts-in-phpstorm/)

**Comment by Unthrottled** [comment]
Just as a heads up. I've made the change, however, I think  there may be a bug in the platform that over-writes the attribute set by the custom theme. I'll have to investigate more.

**Comment by Unthrottled** [comment]
Turns out it is an issue with the platform.

[I created an issue so that it could be fixed](https://youtrack.jetbrains.com/issue/IDEA-257040). Please vote for visibility. 

Will add a themed typeguard to the plugin once the issue is fixed.

**Comment by mskelton** [comment]
Thanks for looking into this @Unthrottled!

**Comment by Unthrottled** [comment]
@all-contributors please add @infix for bugs
