### ISSUE TITLE
Cannot display this theme on idea

### ISSUE THREAD

**Issue by wanxiaolong** [one-dark/jetbrains-one-dark-theme#200]
Hi,

I followed this readme file to config my idea, but unfortunately, this theme didn't appear on my idea after I install it. 
Could you please help to take a look?

IDEA version: 2018.3.6(Ultimate Edition)
One dark theme version: 1.8.2

Screenshots:
![image](https://user-images.githubusercontent.com/7314085/103056278-777e8e80-45d7-11eb-87ef-9a818523cb3d.png)

![image](https://user-images.githubusercontent.com/7314085/103056300-882f0480-45d7-11eb-8e42-ceff85b0a6e9.png)

Thanks,
Xiaolong.

**Comment by mskelton** [comment]
Have you tried restarting IntelliJ?  Sometimes that will fix the issue.

**Comment by Unthrottled** [comment]
@wanxiaolong 

I was a bit curious about this myself, so I looked into it.

I got the plugin to build for 2018. It did not work, the plugin was registered as _installed_ but the look and feel was not present. Just like you are observing.  I think it may have to do with how the `theme.json` is structured.

Here is the IDE I used to test it out.
```
IntelliJ IDEA 2018.3.6 (Ultimate Edition)
Build #IU-183.6156.11, built on March 25, 2019
Licensed to Alex Simons
You have a perpetual fallback license for this version
Subscription is active until February 21, 2021
JRE: 1.8.0_152-release-1343-b28 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.4.0-58-generic
```

Unfortunately, I am not going to support this version of the IDE and am not going to look into the issue any further .

However, I did  [create a branch](https://github.com/one-dark/jetbrains-one-dark-theme/tree/2018Build), that you could fork from, maintain, and use yourself.
[Here is some helpful documentation if you want to go that route](https://jetbrains.org/intellij/sdk/docs/reference_guide/ui_themes/themes_intro.html)


I'm going to close this issue. However feel free to use this issue as a channel of communication if you wish. 

Thank you for your interest and understanding!

**Comment by wanxiaolong** [comment]
@mskelton Thank you for your reply. Yes I restarted my IDEA after installed this plugin, but still not work.

**Comment by wanxiaolong** [comment]
Hi @Unthrottled Thank you for your investigation. The reason that I use this old version of one-dark-theme is that I only have license of IntelliJ IDEA 2018.3.6. I may not have time to work it out, but we can still keep this branch as others may met the same issue and have time to investigate more on it. Thank you again for your investigation and suggestion.
