### ISSUE TITLE
Updating to new versions (e.g. 5.1) does not preserve Settings/Editor/Color settings.

### ISSUE THREAD

**Issue by MonteCreasor** [one-dark/jetbrains-one-dark-theme#202]
**Describe the bug**
When updating to new versions in Android Studio (e.g. 5.1), the update reverts to a "pure" one dark theme which removes any customization you may have made by setting the editor background colour in Settings/Editor/Color. I have my editor colour scheme set to Cobolt and I lose it every time your one dark theme releases a new update. It's no biggie because I can always (and do) just reset my editor colour scheme, but it might be something you want to fix at some point if you think it's worth it.

**To Reproduce**
1. Allow one dark to update when a new release is available.

**Expected Behavior**
I would expect my editor's custom colour scheme to remain intact and not be replaced by my chosen one dark overall IDE theme.

**Environment**
Android Studio 4.1.1
Build #AI-201.8743.12.41.6953283, built on November 4, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.4.0-58-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true
Non-Bundled Plugins: IdeaVIM, Key Promoter X, com.alayouni.ansiHighlight, GrepConsole, com.github.jk1.ytplugin, org.intellij.plugins.markdown, org.jetbrains.kotlin, mobi.hsz.idea.gitignore, net.vektah.codeglance, com.developerphil.adbidea, com.konifar.material_icon_generator, com.markskelton.one-dark-theme
Current Desktop: ubuntu:GNOME

It should contain:
* OS (Windows, Linux, Mac)
* IntelliJ Product + version (IDEA, RubyMine...)
* Plugin version 
* If needed a list of enabled plugins -->

**Screenshots**
Not required since I think my description is clear.

**Comment by Unthrottled** [comment]
Hey friend! Thank you for taking the time to fill out this issue and providing very helpful details!

I think this is a feature of the platform itself, and not the plugin. The platform exhibits, the behavior you described, for all theme plugins (at least all of the other ones I have tried). When installed/updated it well set the look and feel/editor color scheme/theme to the current version. I can investigate a bit more, but I think it may be out of the control of the plugin itself.

**Comment by MonteCreasor** [comment]
Thanks for responding so quickly! I'm certainly not at all worried or even bothered by it. I've built a pretty complicated Intellij plugin myself (shows a collection of git repositories from various users for testing and grading Vanderbilt University Android assignments for Juniors and graduates). I wasn't sure if it would be possible based on my knowledge, so I was really just making sure you knew how yours behaved and were good with that! Have a great holiday season!

**Comment by MonteCreasor** [comment]
Oh ya, and BTW, thanks so much for your plugin and great colour choices, I just love it!

**Comment by Unthrottled** [comment]
>  so I was really just making sure you knew how yours behaved and were good with that

Got it! Once I verify that it is part of the platform. I'll close the issue. I don't want to add anything to complex to the simple plugin at the moment (complex stuff breaks easy 😅)

And thank you for the kind words! However, its thanks to the efforts of everybody that has contributed that made the theme the way it is (I just keep the lights on 😄 )

**Comment by Unthrottled** [comment]
Thank you for bringing this to my attention! However, I am not going to override the platforms default behavior.
