### ISSUE TITLE
Title bar font color

### ISSUE THREAD

**Issue by yxd0018** [one-dark/jetbrains-one-dark-theme#203]
With dark theme, the title bar font is too faint to see. Is there a way to set that color?

**Comment by Unthrottled** [comment]
Are you talking about the Window 10 frame?

![image](https://user-images.githubusercontent.com/15972415/103347427-9b6d2480-4a5c-11eb-8fea-180992cca63d.png)

Edit: This is just for me
[image](https://user-images.githubusercontent.com/15972415/103347794-98beff00-4a5d-11eb-8857-01760ff1e98b.png)

**Comment by yxd0018** [comment]
yes, the top one saying progress-bar. It's barely viewable.

**Comment by Unthrottled** [comment]
Cool, Yeah, that can be updated to be a bit brighter..

**Comment by yxd0018** [comment]
Better to be able to select custom color

**Comment by Unthrottled** [comment]
Fair enough! That's pretty straight forward.
