### ISSUE TITLE
Missed color for methods/variables in RubyMine

### ISSUE THREAD

**Issue by yuri-karpovich** [one-dark/jetbrains-one-dark-theme#207]
Thanks for the theme! It's almost perfect but I have a little pain with it - Rubymine shows the same color for variables and for methods.  

```ruby
array = []
array.join
```

Plugin version:  5.1.4
RubyMine RubyMine 2020.3.2
MacOS 10.15.7 

![image](https://user-images.githubusercontent.com/7230069/109047620-267a3c00-76e7-11eb-98aa-593a644e8f3b.png)

**Comment by Unthrottled** [comment]
Hey! I'll assume this is ruby?

Do me a favor:
- Put your cursor over join/array
- `Command+shift+a`
- `Jump to colors and font`

What does RubyMine think those 2 things are?

![Peek 2021-02-24 17-11](https://user-images.githubusercontent.com/15972415/109078648-4dbf1200-76c3-11eb-9bb5-4da9ed51708e.gif)

For me it was identifier and weak warning.

It also looks like methods are supposed to be colored

![Screenshot from 2021-02-24 17-15-08](https://user-images.githubusercontent.com/15972415/109078997-e35aa180-76c3-11eb-8dbd-eb2962741fb4.png)

**Comment by yuri-karpovich** [comment]
Right. It's Ruby. `array` is identified and local variable at the same time 


![Feb-25-2021 10-15-27](https://user-images.githubusercontent.com/7230069/109117024-78a47700-7752-11eb-907d-d2bf3ab27c59.gif)


Here is an example how it works in another theme:
![image](https://user-images.githubusercontent.com/7230069/109116810-2bc0a080-7752-11eb-81eb-2d7ea190c4c2.png)

**Comment by Unthrottled** [comment]
@all-contributors add @yuri-karpovich for design

**Comment by yuri-karpovich** [comment]
Thank you! 🎉
