### ISSUE TITLE
Highlight method usage in same class in the right side

### ISSUE THREAD

**Issue by heitorcolangelo** [one-dark/jetbrains-one-dark-theme#208]
**Describe the bug**
With the default Darcula theme from IntelliJ/AndroidStudio I can see a green tick on the right side of the screen indicating where the method that it is currently selected is being used inside that class.
In the screenshot below (screenshot section), the method is being used in one other place of that class, so we have two green ticks, one for the method definition and another one for the line that is calling that method.

**To Reproduce**
1. Change to a default theme in AndroidStudio,
2. Open a file with at least one class, containing one method, and a call to this method in the same class:
```kotlin
class MyClass {
        init {
               myMethod()
        }

        fun myMethod() {}
}
```
3. Put the blinking cursor on the method name,
4. You should see two ticks on the right side of the IDE, indicating the method definition and the calling line.

**Expected Behavior**
I should see the same ticks with One dark theme

**Environment**
Android Studio Arctic Fox | 2020.3.1 Canary 8
Build #AI-203.7148.57.2031.7165533, built on February 23, 2021
Runtime version: 11.0.8+10-b944.6842174 x86_64
VM: OpenJDK 64-Bit Server VM by N/A
macOS 10.16
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4
Registry: external.system.auto.import.disabled=true

**Screenshots**
**With Darcula**
<img width="348" alt="image" src="https://user-images.githubusercontent.com/6201773/109204916-b1f5da80-7784-11eb-9d02-042dd2ac7661.png">

**With One Dark**
<img width="364" alt="image" src="https://user-images.githubusercontent.com/6201773/109205134-f3868580-7784-11eb-9c4a-7604fb00564b.png">

**Comment by Unthrottled** [comment]
![image](https://user-images.githubusercontent.com/15972415/109230816-1c117e00-778b-11eb-977a-2b282d8ae760.png)

:thinking: Interesting! TIL. I'll have some time to investigate the right setting later this week.

**Comment by Unthrottled** [comment]
@all-contributors add @heitorcolangelo for bugs
