### ISSUE TITLE
Differences don't stand out in IDEA diff window

### ISSUE THREAD

**Issue by znerd** [one-dark/jetbrains-one-dark-theme#212]
**Describe the bug**
The visual appearance of differences in the IntelliJ IDEA diff window is insufficiently distinct from the other file contents.

**To Reproduce**
1. Have a unit test that compares a lot of text.
2. Ensure that there is a small difference between what is expected and what is actual.
3. Perform the unit test, and then click on the “Click here” text to show the diff in a separate dialog.

**Expected Behavior**
Significant difference between differences on the one hand, and the text that is the same on the other hand.

**Environment**
IntelliJ IDEA 2021.1 EAP (Ultimate Edition)
Build #IU-211.6222.4, built on February 25, 2021
IntelliJ IDEA EAP User
Expiration date: March 27, 2021
Runtime version: 11.0.10+9-b1341.2 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Jenkins Plugin 0.13.10-2020.3
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.jetbrains.ChooseRuntime (1.2), com.markskelton.one-dark-theme (5.1.5), google-java-format (1.9.0.0), net.seesharpsoft.intellij.plugins.csv (2.14.4), com.microsoft.vso.idea (1.161.1), name.kropp.intellij.makefile (211.6222.4), Jenkins Control Plugin (0.13.10-2020.3), com.sensei.solutions (2021.1.1), org.asciidoctor.intellij.asciidoc (0.32.26), org.sonarlint.idea (4.14.2.28348)
Kotlin: 211-1.4.21-release-IJ6222.3

**Screenshots**
See the screenshot. Notice that on the left hand side there is “Foo bar.” – ending in a period, but on the right hand side that period is not there. This is very difficult to spot, especially as the amount of text grows larger.
![Screen Shot 2021-03-05 at 10 59 24](https://user-images.githubusercontent.com/117866/110099759-f810f680-7da1-11eb-85b7-904b112a5034.png)

**Comment by Unthrottled** [comment]
:thinking: Interesting problem we have here, both of these colors are around the same hue, one is just a darker less saturated variant. I'll have to think of some way to make that work.

Quick fix is just doing this
![Screenshot from 2021-03-05 08-03-24](https://user-images.githubusercontent.com/15972415/110125755-4e257000-7d89-11eb-92d5-d0314ed3049d.png)

Which does this
![Screenshot from 2021-03-05 08-04-35](https://user-images.githubusercontent.com/15972415/110125921-7c0ab480-7d89-11eb-8987-9e3925e9ea4f.png)

Which doesn't feel much better. I'll have to play around with it some more to see what looks good.
