### ISSUE TITLE
Different font look

### ISSUE THREAD

**Issue by Kamilkime** [one-dark/jetbrains-one-dark-theme#217]
After updating IJ from version 2020.3.4 to version 2021.1 - the font looks different. The settings are still the same - JetBrains Mono, size 13, line height 1.2. But now the font seems... higher, bigger, despite having the same set size. Was sth changed in IJ itself, or was sth changed in the newer versions of the One Dark plugin?

Old look:
![obraz](https://user-images.githubusercontent.com/10383567/118057336-0f64f500-b38c-11eb-8e3e-349ab5090fef.png)

New look:
![obraz](https://user-images.githubusercontent.com/10383567/118057344-14c23f80-b38c-11eb-87e4-c43af0e2b281.png)

Both images show full height of the editor window, so the new font shows a bit less code

**Comment by Unthrottled** [comment]
> After updating IJ from version 2020.3.4 to version 2021.1 

If you had `v5.1.5` on 2020.3.4 and 2021.1, then there isn't any code (in the plugin) that changes the font size with different versions of the platform.

It appears that `Font Weight Options` is part of [what's new](https://www.jetbrains.com/idea/whatsnew/) in intellij. Could that be it? :thinking: 

![image](https://user-images.githubusercontent.com/15972415/118199019-bb9fed80-b417-11eb-891c-69c463c26234.png)

| 2020.3.4 | 2021.1.1 |
| --- | --- |
| ![Screenshot from 2021-05-13 18-23-51](https://user-images.githubusercontent.com/15972415/118199379-9bbcf980-b418-11eb-936f-63badc98288a.png) | ![Screenshot from 2021-05-13 18-20-32](https://user-images.githubusercontent.com/15972415/118199391-a11a4400-b418-11eb-9d90-096223b6b3ed.png) |

:point_up: Here's mine. To be honest, I can't see the difference, then again I am running on Ubuntu.

Best I can do friend is show you places you can play around with the font settings. So you can tweak it to your liking :smile: 

![Screenshot from 2021-05-13 18-29-56](https://user-images.githubusercontent.com/15972415/118199705-3f0e0e80-b419-11eb-9967-7be378fc869f.png)
![Screenshot from 2021-05-13 18-29-46](https://user-images.githubusercontent.com/15972415/118199706-3f0e0e80-b419-11eb-97fa-c7d573789c7e.png)
![Screenshot from 2021-05-13 18-29-31](https://user-images.githubusercontent.com/15972415/118199707-3fa6a500-b419-11eb-902e-9b822bf6c4bc.png)


Also today I learned: `'sth' === 'something'`
