### ISSUE TITLE
How do I use your theme in the plugin "code with me", it is not in the marketplace.

### ISSUE THREAD

**Issue by terror3800** [one-dark/jetbrains-one-dark-theme#220]

**Comment by Unthrottled** [comment]
I am pretty sure the plugin is not available on that platform because of some unnecessary platform dependencies listed in the plugin descriptor. 

I'll have some time later this week to remove those and test to see if it works on that platform.

**Comment by terror3800** [comment]
Thank you, I'm waiting for your answer.

**Comment by Unthrottled** [comment]
@terror3800 v5.3.0 is available in the marketplace. Thanks for bringing this to my attention!

**Comment by terror3800** [comment]
thank you so much
