### ISSUE TITLE
Theme not showing up in Android Studio Artic fox 2020.3.1.

### ISSUE THREAD

**Issue by wyao4-ford** [one-dark/jetbrains-one-dark-theme#223]
All I did was upgrading android studio to Arctic Fox and upgrade OneDark plugin to 5.3, then as shows in the screenshot I am not able to select one dark theme anymore 

![image](https://user-images.githubusercontent.com/79589200/127390479-5bc0a1ea-fc5c-4774-9280-4c22d2bdfcd4.png)

**Comment by Unthrottled** [comment]
Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos to the clipboard and paste it here.

It should contain:
* OS (Windows, Linux, Mac)
* IntelliJ Product + version (IDEA, RubyMine...)
* Plugin version 
* If needed a list of enabled plugins 

Here is mine:

```
Android Studio Bumblebee | 2021.1.1 Canary 5
Build #AI-211.7628.21.2111.7579519, built on July 23, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-80-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry: bigger.font.in.project.view=true, external.system.auto.import.disabled=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM (0.69), com.jetbrains.ChooseRuntime (1.2), com.markskelton.one-dark-theme (5.3.0), io.acari.normandy.progress.bar (1.9.10), io.unthrottled.DokiTheme (14.3.0), io.unthrottled.amii (0.10.6), Dart (211.7727), org.jetbrains.kotlin (211-1.5.21-release-328-AS7442.40), io.flutter (58.0.3), io.unthrottled.amii.android (0.1.0)
Current Desktop: ubuntu:GNOME
````

Did you also restart your android studio?

**Comment by wyao4-ford** [comment]
I restart the device and android studio but issue remain the same. 
When I go to help the screenshot is what I have, I don't find a Help -> About IntelliJ IDEA (Windows) 
![image](https://user-images.githubusercontent.com/79589200/127407186-13773338-f5fe-4bdd-ba55-50004e0cfd17.png)

when I do just Help -> About, below is what I have 
![image](https://user-images.githubusercontent.com/79589200/127407268-5f6a5503-c950-4a24-bf1f-86d5ba9f3185.png)

**Comment by Unthrottled** [comment]
Could you please click
![image](https://user-images.githubusercontent.com/15972415/127407584-58bade2b-aab5-4cdc-92d2-3f3ac851f3b0.png)
and paste the contents here?

**Comment by wyao4-ford** [comment]
Android Studio Arctic Fox | 2020.3.1
Build #AI-203.7717.56.2031.7583922, built on July 26, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 12
Registry: external.system.auto.import.disabled=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: Batch Scripts Support, CMD Support, Key Promoter X, com.intellij.marketplace, com.mallowigi, com.markskelton.one-dark-theme, net.vektah.codeglance, name.kropp.intellij.makefile, org.sonarlint.idea, wu.seal.tool.jsontokotlin, org.jetbrains.kotlin, zielu.gittoolbox, com.chrisrm.idea.MaterialThemeUI, com.madrapps.dagger-plugin, izhangzhihao.rainbow.brackets, org.intellij.plugins.markdown, github.cweijan.test-theme

**Comment by Unthrottled** [comment]
:thinking: The plugin is installed. Are there only two entries? Is the drop-down just short?
It looks like your current theme is a Material Theme (Darker maybe?)

Could you try the `Quick Switch` option, please? Choose `Look and Feel`, you should be able to see `One Dark` and the others.
https://www.jetbrains.com/help/idea/switching-between-schemes.html

**Comment by wyao4-ford** [comment]
the drop-down only have that two options, which should not happen.
![image](https://user-images.githubusercontent.com/79589200/127408545-aad46ee0-f496-4e1b-b849-24e46b5365c7.png)

My current appearance theme is Darcula because that is one of the two options I have.

Inside `Quick Switch` there is not a `Look and Feel`, only as this 
![image](https://user-images.githubusercontent.com/79589200/127408622-7231a2c2-0fb4-493e-8372-13b3b2b205b7.png)

Even I choose from Material Theme I don't find a One Dark Theme there 
![image](https://user-images.githubusercontent.com/79589200/127408703-d11ff4a6-80c4-4f50-a589-188f0516b54e.png)

**Comment by Unthrottled** [comment]
Okay, A bit confusing. Is the plugin enabled?

Can you go to `Settings` -> `Plugins` -> `Installed` and check the `One Dark theme` please?

![image](https://user-images.githubusercontent.com/15972415/127409061-8d2e09c0-e4f2-4c13-a25d-dab3a145783e.png)

**Comment by wyao4-ford** [comment]
Yes 
![image](https://user-images.githubusercontent.com/79589200/127409114-ce01c17d-ae45-46fb-8d51-1b3dca2b2a41.png)

**Comment by wyao4-ford** [comment]
I find it's probably not the problem of One Dark Theme. I install other themes and it's also not showing on the theme options.

**Comment by Unthrottled** [comment]
![What the heck](https://akm-img-a-in.tosshub.com/indiatoday/images/story/201701/jackie-story_647_012517032327.jpg)

Have you tried, un-installing the plugin, restarting, and installing the plugin again?

I'm going to try Arctic Fox, I  was on Bumblebee.

**Comment by wyao4-ford** [comment]
I already tried that and it didn't work.

**Comment by wyao4-ford** [comment]
I upgraded both on Mac machine and Windows Machine and seems like Mac machine works fine, just a heads up.

**Comment by Unthrottled** [comment]
I am able to reproduce the issue on Arctic Fox on Linux. It's also not just One Dark. I also downloaded Gruv Box, and it doesn't show.

```Android Studio Arctic Fox | 2020.3.1
Build #AI-203.7717.56.2031.7583922, built on July 26, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-80-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry: bigger.font.in.project.view=true, external.system.auto.import.disabled=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, com.jetbrains.ChooseRuntime, com.markskelton.one-dark-theme, io.acari.normandy.progress.bar, io.unthrottled.DokiTheme, io.unthrottled.amii, io.unthrottled.amii.android
Current Desktop: ubuntu:GNOME
```

Have you considered using the early access Android Studios (Bumblebee)?
https://developer.android.com/studio/preview


I'll have some time later to chase down if anybody else is having the same issue.
Thanks for being patient with me.

**Comment by wyao4-ford** [comment]
I would probably try that version.

Thanks for being patients too, at least we know where the problem is coming from. I have raise an issue and let's see https://issuetracker.google.com/issues/194935987.

**Comment by SamueldaCostaAraujoNunes** [comment]
I share the same problem!

**Comment by winskyan** [comment]
I share the same problem!

**Comment by irfnyas** [comment]
I share the same problem!

**Comment by linxiangcheer** [comment]
This question makes me sad

**Comment by MiranKm** [comment]
I share the same problem!

**Comment by khoben** [comment]
Here is temporary fix: https://issuetracker.google.com/issues/194925628#comment4

**Comment by Sheitak** [comment]
I have same problem, Ubuntu 20,

```
Android Studio Arctic Fox | 2020.3.1
Build #AI-203.7717.56.2031.7583922, built on July 26, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-80-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 12
Registry: external.system.auto.import.disabled=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: Lombook Plugin, com.intellij.marketplace, com.mallowigi, com.markskelton.one-dark-theme, mobi.hsz.idea.gitignore, Dart, com.thoughtworks.gauge, org.jetbrains.kotlin, io.flutter, com.ruiyu.ruiyu, pl.pszklarska.pubversionchecker, ru.adelf.idea.dotenv, org.intellij.plugins.markdown
Current Desktop: ubuntu:GNOME
```

**Comment by mskelton** [comment]
Hi folks, instead of posting a "I'm having this issue type of comment", please use the reactions on the original issue to denote that you are also having this issue.  Adding another comment just creates extra noise for people subscribed to this thread.

I'm going to lock this issue for now until we have more details.

**Comment by Unthrottled** [comment]
It would appear that the issue has been addressed in the Arctic Fox Patch 1. Current patch is Arctic Fox 2.
https://issuetracker.google.com/issues/194925628

I verified that custom themes work on my android studio.

```
Android Studio Arctic Fox | 2020.3.1 Patch 2
Build #AI-203.7717.56.2031.7678000, built on August 26, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-84-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry: bigger.font.in.project.view=true, external.system.auto.import.disabled=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, com.jetbrains.ChooseRuntime, com.vincentp.gruvbox-theme, io.acari.DDLCTheme, io.acari.normandy.progress.bar, io.unthrottled.amii, Dart, org.jetbrains.kotlin, io.flutter, io.unthrottled.amii.android
Current Desktop: ubuntu:GNOME
```
