### ISSUE TITLE
Different theme is suggestion popup

### ISSUE THREAD

**Issue by Kamilkime** [one-dark/jetbrains-one-dark-theme#224]
When the suggestions popup is opened - the colors in it don't match the rest of the One Dark Theme.
![obraz](https://user-images.githubusercontent.com/10383567/127436356-034766c5-22e9-4b30-93c2-349620d5bd69.png)

**Environment**
Windows 10
IntelliJ IDEA 2021.2 (Community Edition)
Build #IC-212.4746.92, built on July 27, 2021
Newest (v5.3.0) version of the One Dark plugin

**Comment by Unthrottled** [comment]
Ah, it is a different shade of gray

![image](https://user-images.githubusercontent.com/15972415/127476088-379a00b0-6a6c-4e7d-8a89-e3da34b93c42.png)

Just making sure, you are expecting it to look like this :point_up: and not something else, right?

**Comment by Kamilkime** [comment]
Yup, exactly. The one from my screen looks more like the Darcula theme colors. And the one from your screen - it looked like this before I updated IJ to 2021.2

**Comment by Unthrottled** [comment]
Cool, thanks! 

I'm going to wait a bit before releasing the fix. In hopes of catching any other issues. I can provide a built version of the plugin if wanted. You could also (in the mean time):

- Export your current color scheme
- Add this in the `<colors>` node.
```xml
<option name="LOOKUP_COLOR" value="3d424b"/>
```

- Import the modified theme.

[Docs](https://www.jetbrains.com/help/idea/settings-colors-and-fonts.html)

**Comment by Kamilkime** [comment]
I'll just wait for the release and add the option manually to the color scheme for now. Thanks for the help :D

**Comment by Unthrottled** [comment]
Thanks for the sharp eyes!

@all-contributors add @Kamilkime  for bug
