### ISSUE TITLE
Themes not working/ showing up in Appearance in Android Studio Artic fox 2020.3.1 version 

### ISSUE THREAD

**Issue by MiranKm** [one-dark/jetbrains-one-dark-theme#226]
**Describe the bug**

**To Reproduce**

1. Update android studio to version Artic fox 2020.3.1

**Tried**
- Uninstalling and installing again
- installing from JetBrains plugin page
- invalidating cache and restart 

**Expected Behavior**

**Environment**

**Screenshots**

**Comment by Unthrottled** [comment]
Hey! You can track the status of the issue here #223 . Thanks!

**Comment by nikunjparadva** [comment]
## Here is the Solution 

https://stackoverflow.com/a/68599712/5773037

#223
