### ISSUE TITLE
Mocha syntax is not highlighted 

### ISSUE THREAD

**Issue by vaytsel** [one-dark/jetbrains-one-dark-theme#227]
**Describe the bug**
Mocha syntax is not highlighted

**To Reproduce**
Just write code with mocha methods 

**Expected Behavior**
Highlight Mocha constructions

**Environment**
WebStorm 2021.2
Build #WS-212.4746.80, built on July 23, 2021
Runtime version: 11.0.11+9-b1504.13 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry: ide.intellij.laf.enable.animation=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.bluewaitor.tsReact (1.4.0), com.jinsihou.react.snippets (1.1.0), com.markskelton.one-dark-theme (5.3.0), commit-template-idea-plugin (1.2.0), intellij-clock (2.0.0), lermitage.intellij.battery.status (1.19.201), com.mallowigi (38.0.0), org.sylfra.idea.plugins.linessorter (1.0.1), com.intellij.react.css.modules (1.0.1), me.mbolotov.cypress (1.4.1)
 

**Screenshots**
![image](https://user-images.githubusercontent.com/29410898/129168944-92e46018-147c-4617-b298-3c22ca2b6901.png)

**Comment by Unthrottled** [comment]
Hmm, I'm not able to replicate the issue. My WebStorm appears to recognize the global functions (maybe from the node modules?).

Try this:

![Peek 2021-08-12 05-54](https://user-images.githubusercontent.com/15972415/129185420-9671157c-7670-493c-af03-f37e020bb3bf.gif)

1. Navigate `Settings` -> `Languages & Frameworks` -> `Javascript` -> `Libraries` 
1. Select `Download`
1. Search for `Mocha`
1. `Download & Install`
1. ???
1. Profit?

**Comment by vaytsel** [comment]
> Hmm, I'm not able to replicate the issue. My WebStorm appears to recognize the global functions (maybe from the node modules?).
> 
> Try this:
> 
> ![Peek 2021-08-12 05-54](https://user-images.githubusercontent.com/15972415/129185420-9671157c-7670-493c-af03-f37e020bb3bf.gif)
> 
> 1. Navigate `Settings` -> `Languages & Frameworks` -> `Javascript` -> `Libraries`
> 2. Select `Download`
> 3. Search for `Mocha`
> 4. `Download & Install`
> 5. ???
> 6. Profit?

Didn't help (

**Comment by Unthrottled** [comment]
Hmm, does it not recognize the javascript? Can you see what webstorm thinks the lexical tokens are?

![Peek 2021-08-12 05-47](https://user-images.githubusercontent.com/15972415/129186633-9dd7082d-860e-461e-b9cb-65816fc7e1dd.gif)

Hover over describe and `Jump to colors & fonts` .

**Comment by vaytsel** [comment]
> Hmm, does it not recognize the javascript? Can you see what webstorm thinks the lexical tokens are?
> 
> ![Peek 2021-08-12 05-47](https://user-images.githubusercontent.com/15972415/129186633-9dd7082d-860e-461e-b9cb-65816fc7e1dd.gif)
> 
> Hover over describe and `Jump to colors & fonts` .

![image](https://user-images.githubusercontent.com/29410898/129201790-d22c1cc0-3b17-43b3-b5f6-eb764c7726f7.png)
![image](https://user-images.githubusercontent.com/29410898/129202605-0c5075f2-da36-4655-8c11-d1f0055659b2.png)

**Comment by Unthrottled** [comment]
Ah, it looks like you are using typescript.

It also appears that you have customized the color scheme theme. Please either try to click the ellipse and choose `Restore Defaults` or fix the coloring yourself, please. 

![image](https://user-images.githubusercontent.com/15972415/129203259-ff699eb1-7a50-41c4-8b9d-bf51cfbf61bb.png)

The theme currently sets
`<option name="JS.GLOBAL_VARIABLE" baseAttributes="DEFAULT_GLOBAL_VARIABLE"/>` but am unsure if you changed it or if webstorm is being a jerk.

**Comment by vaytsel** [comment]
> Ah, it looks like you are using typescript.
> 
> It also appears that you have customized the color scheme theme. Please either try to click the ellipse and choose `Restore Defaults` or fix the coloring yourself, please.
> 
> ![image](https://user-images.githubusercontent.com/15972415/129203259-ff699eb1-7a50-41c4-8b9d-bf51cfbf61bb.png)
> 
> The theme currently sets
> `<option name="JS.GLOBAL_VARIABLE" baseAttributes="DEFAULT_GLOBAL_VARIABLE"/>` but am unsure if you changed it or if webstorm is being a jerk.

`restore default` works for me, ty so much!

I just changed the background color of the editor once, I don't know why it affected this

**Comment by Unthrottled** [comment]
Cool! Yeah, so that's a feature of the edited/custom editor schemes. Once you make a change, you won't get any updates to the editor color scheme. Would be kind of annoying if every time you updated, your changes would be overridden. Downsides is, that you've got to maintain new additions scheme now. Pretty sure there isn't a editor scheme color merge strategy (that'd be cool though!)

Imma close this issue as this isn't an issue with the plugin, but a current feature of the platform.
