### ISSUE TITLE
When the code is compared, the color difference is not obvious, which is bothersome

### ISSUE THREAD

**Issue by ZhangChengLin** [one-dark/jetbrains-one-dark-theme#228]
When the code is compared, the color difference is not obvious.
The comparison when submitting git submission is also not obvious.

**Comment by Unthrottled** [comment]
Hey!

So this is what I looks like right now:

![Screenshot from 2021-08-23 05-24-57](https://user-images.githubusercontent.com/15972415/130432361-0c7d9101-1451-4a86-9d7f-a70161f1936b.png)

Seems fairly obvious, in my opinion.

Thankfully, you have the option to customize it to your preferences. Just go to `Settings -> Editor -> Diff & Merge` and you should be able to change the colors to your own preferences.

Thanks for understanding!
