### ISSUE TITLE
favorites icon display error

### ISSUE THREAD

**Issue by liy-cn** [one-dark/jetbrains-one-dark-theme#229]
The icon of favorites classes of methods is 'BLACK', but it should be "YELLOW', I can't see the icon in dark mode.plz change to another color icon,thank you.
![微信截图_20210917105214](https://user-images.githubusercontent.com/2853829/133716721-83c1c525-8a9f-4466-be28-f2131295d2ae.png)
![微信截图_20210917105306](https://user-images.githubusercontent.com/2853829/133716727-4ef3649b-8ba8-4234-8f1d-63507b3fa92e.png)

**Comment by Unthrottled** [comment]
Thanks for reporting this issue!

@all-contributors add @liy-cn  for bugs

**Comment by liy-cn** [comment]
Thanks buddy! It's an hornor!
