### ISSUE TITLE
Installs but doesn't work on GoLand 2018.3.3

### ISSUE THREAD

**Issue by mskelton** [one-dark/jetbrains-one-dark-theme#23]
Taken from [review](https://plugins.jetbrains.com/plugin/11938-one-dark-theme/reviews#review=32455)

**Comment by mskelton** [comment]
@x1unix I saw your review comment about this not working in GoLad 2018.3.3.  Could you provide more details about the issue?  My guess is you aren't seeing the theme show up since the readme is setup for version 2 which changed how to install the theme due to changes to the IntelliJ that changed how themes are setup in order to support custom UI themes.

I'll add some information to the installation docs for how to install the legacy version (v1) of this plugin.  Hopefully that will fix your issue.

**Comment by mskelton** [comment]
I have updated the Wiki to include [legacy installation steps](https://github.com/markypython/jetbrains-one-dark-theme/wiki/Installation#legacy-v1-installation).

**Comment by x1unix** [comment]
@markypython theme does not appears in `Settings | Appearance` section on Windows 10.
On Linux (Ubuntu 18.10) everything is fine

**Comment by x1unix** [comment]
![изображение](https://user-images.githubusercontent.com/9203548/56853339-e0a78d80-692e-11e9-94bf-d4e76b8dc08c.png)

![изображение](https://user-images.githubusercontent.com/9203548/56853351-0fbdff00-692f-11e9-8a05-ded1256b41bd.png)

Here is settings screenshot. One Dark theme plugin is installed


**Environment:**
```
GoLand 2018.3.3
Build #GO-183.5153.54, built on January 16, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by mskelton** [comment]
@x1unix After seeing your review, I updated the [installation docs](https://github.com/markypython/jetbrains-one-dark-theme/wiki/Installation#legacy-v1-installation) to include information about the legacy version of this plugin.  The important difference is you must set the color theme in `Preferences | Editor | Color Scheme` rather than the appearance section.

Can you look in the color scheme section to see if the theme options are there?

**Comment by x1unix** [comment]
@markypython color scheme appears but it changes only editor color scheme, not a whole UI

**Comment by mskelton** [comment]
That is expected.  The UI customizations are only available on IDE versions 2019.1 and above.  See the original [blog post](https://blog.jetbrains.com/idea/2019/03/brighten-up-your-day-add-color-to-intellij-idea/) by Jetbrains for more details.

**Comment by mskelton** [comment]
If you would like the UI theme you will need to upgrade your IDE to the latest version (2019.1.1).

**Comment by x1unix** [comment]
@markypython understood. Can you close the ticket?

**Comment by mskelton** [comment]
Thanks for posting your feedback as it gave me the opportunity to update the installation docs.  Hope you find this theme helpful and feel free to open any other issues for questions, bugs, or feature requests!

**Comment by x1unix** [comment]
@markypython thank you for the theme! I'm using it almost on any IDE i have
