### ISSUE TITLE
WebStorm 2021.3 EAP (213.3714.441) compatibility

### ISSUE THREAD

**Issue by Kadeluxe** [one-dark/jetbrains-one-dark-theme#233]
**Describe the bug**
WebStorm switched to 213 version (Build #WS-213.3714.441).

```
WebStorm 2021.3 EAP
Build #WS-213.3714.441, built on September 22, 2021
WebStorm EAP User
Expiration date: October 22, 2021
Runtime version: 11.0.12+7-b1649.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2038M
Cores: 16
Non-Bundled Plugins:
    com.github.leomillon.uuidgenerator (4.4.1)
    String Manipulation (8.15.203.000.3)
    mobi.hsz.idea.gitignore (4.2.0)
    com.intellij.database (213.3714.441)
    izhangzhihao.rainbow.brackets (6.21)
```

**Comment by Unthrottled** [comment]
That must have just come out today, or I'm a bit behind. I'll have a updated version soon, thanks for bringing this to my attention.

**Comment by Kadeluxe** [comment]
> That must have just come out today, or I'm a bit behind. I'll have a updated version soon, thanks for bringing this to my attention.

Yeah I pretty much created an issue as soon as EAP became available.
Currently use zip file you provided, no issues so far. 
Thank you for your work!
