### ISSUE TITLE
The color of the selected option and the colors of the available options make me confused

### ISSUE THREAD

**Issue by muyu66** [one-dark/jetbrains-one-dark-theme#236]
**Describe the bug**

The color of the selected option and the colors of the available options make me confused.

In VSCODE, it is more like "selected items are bright, and available options are dark", which is the opposite in IDEA, which causes inconsistency and is easy to mess (we should highlight the selected items!) 

**To Reproduce**

1.

**Expected Behavior**

**Environment**

**Screenshots**

vscode example
![image](https://user-images.githubusercontent.com/20837526/143842015-da3beaca-5b86-42b4-a9b6-8cf9855572da.png)

idea example
![image](https://user-images.githubusercontent.com/20837526/143839759-ce9d7502-3c2e-42ff-8420-9ac1b5099985.png)

**Comment by Unthrottled** [comment]
Thanks for submitting this issue, I will look into this later this week.

**Comment by Unthrottled** [comment]
@all-contributors add @muyu66 for design
