### ISSUE TITLE
Start screen broken in 2021.3

### ISSUE THREAD

**Issue by dorudumitru-hh** [one-dark/jetbrains-one-dark-theme#237]
2021.3
![Screenshot 2021-12-03 at 09 42 33](https://user-images.githubusercontent.com/40240395/144564280-4ef69930-8960-4de5-96fa-ce853e3022d7.png)![Screenshot 2021-12-03 at 09 43 36](https://user-images.githubusercontent.com/40240395/144564415-a2633af7-1db9-415f-8802-044ffd93b415.png)

2021.2
![Screenshot 2021-12-03 at 09 52 44](https://user-images.githubusercontent.com/40240395/144565690-da19fd84-ea50-4812-b7cd-bcf6b5e35228.png)

**Comment by Unthrottled** [comment]
Will look into this soon, thanks for reporting!

**Comment by Unthrottled** [comment]
@all-contributors add @dorudumitru-hh for bugs
