### ISSUE TITLE
Add all contributors

### ISSUE THREAD

**Issue by mskelton** [one-dark/jetbrains-one-dark-theme#24]

**Comment by mskelton** [comment]
@all-contributors add @markypython to code, question, doc, ideas, maintenance

**Comment by mskelton** [comment]
@all-contributors add @dacoto for bugs

**Comment by mskelton** [comment]
@all-contributors add @x1unix for bugs

**Comment by mskelton** [comment]
@all-contributors add @dacoto for bugs

**Comment by mskelton** [comment]
@all-contributors add @dacoto for bugs

**Comment by mskelton** [comment]
@all-contributors add @x1unix for bugs

**Comment by mskelton** [comment]
@all-contributors add @x1unix for bugs

**Comment by mskelton** [comment]
@all-contributors add @cyclic-reference for question

**Comment by Unthrottled** [comment]
@all-contributors add @dorudumitru to ideas

**Comment by Unthrottled** [comment]
Imma backfill the all contributors. Sorry about all of the noise folks!
![hold onto your butts!](https://1.bp.blogspot.com/-q3ezICNiaSA/VTkydwtF8ZI/AAAAAAAABjU/44e0dsI8jZs/s1600/Jurassic-Park-33-Hold-on-to-your-butts1.jpg)

**Comment by Unthrottled** [comment]
@all-contributors add @chengziorange for bugs

**Comment by Unthrottled** [comment]
@all-contributors add @hongsefb for bugs

**Comment by Unthrottled** [comment]
@all-contributors add @erikdewit87 for ideas, bugs

**Comment by Unthrottled** [comment]
@all-contributors add @skrubbel for bugs
