### ISSUE TITLE
Theme background does not apply to DataSpell 2021.3's jupyter cell

### ISSUE THREAD

**Issue by yujincheng08** [one-dark/jetbrains-one-dark-theme#241]
**Describe the bug**
One dark theme background color does not apply to DataSpell's jupyter cell (as well as pycharm)

**To Reproduce**

1. Install DataSpell 2021.3
2. Install One Dark Theme plugin and apply the theme
3. Attach to a jupyter environment and open a notebook file
4. Create a cell and write some python code

**Expected Behavior**
The python cell of jupyter notebook should show one dark theme like this from #216
![image](https://user-images.githubusercontent.com/5022927/146894289-408ba514-e14b-4a9e-a675-333bbb4a4255.png)

**Environment**
```
DataSpell 2021.3
Build #DS-213.5744.251, built on November 30, 2021
Licensed to **
Subscription is active until April 29, 2022.
Runtime version: 11.0.13+7-b1751.19 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 12
Registry:
    python.scientific.show_help_window=false
    python.scientific.always_use_sci_view=true

Non-Bundled Plugins:
    com.markskelton.one-dark-theme (5.4.1)
```

**Screenshots**

![image](https://user-images.githubusercontent.com/5022927/146891930-7a9f16ba-9065-4955-bd3a-ed189d054733.png)

**Comment by Unthrottled** [comment]
Thank you for bringing this to my attention! 

You can always manually adjust the colors in the settings

![image](https://user-images.githubusercontent.com/15972415/147091921-59cb1cf3-593d-4b90-85a0-0aa87a6a0860.png)


@all-contributors add @yujincheng08 for bug
