### ISSUE TITLE
After updating PHPStorm to the version 2021.3 built-in php functions don't highlighting

### ISSUE THREAD

**Issue by alex-storchak** [one-dark/jetbrains-one-dark-theme#244]
After updating PHPStorm to the version 2021.3 (Build #PS-213.5744.279, built on December 2, 2021) it seems that built-in php functions (ex. implode, array_merge, get_class etc) don't highlighting any more.

![image](https://user-images.githubusercontent.com/47216380/147242060-5d980fdf-6b30-4f6b-9322-6174f0e20515.png)

**Comment by Unthrottled** [comment]
Hey! Could you double check that your issue isn't related to this comment, please?

https://github.com/one-dark/jetbrains-one-dark-theme/issues/227#issuecomment-897635096

**Comment by alex-storchak** [comment]
I've tried to restore defaults and re-install theme plugin. But it didn't help.

Seems that the main problem is that built-in functions and variables both inherits their color from `"Language default"` (`Identifiers->Default` and `Identifiers->local variable`)  where the white color is set for both of them.

I can uncheck "inherit ..." and set the color for my own (and it will work) but imho it should be changed on the color scheme level. 

Unfortunately I cannot check if the settings were the same in the previous release of the theme but I prefer to trust my eyes that have noticed the difference after update of IDE :)

![image](https://user-images.githubusercontent.com/47216380/147257297-5c154116-2586-4eb3-9881-9d4770331a77.png)

**Comment by Unthrottled** [comment]
Thanks for providing the supporting information!

I'll have some time in the future to check out what it might have looked like before. Do you remember which PHP storm you had before upgrading to 2021.3?

**Comment by alex-storchak** [comment]
Thanks!

Most likely it was the 2021.2

![image](https://user-images.githubusercontent.com/47216380/147355214-7d0061c1-652b-453b-ad39-edd7caf90f6c.png)
