### ISSUE TITLE
Tabs from excluded files have poor contrast

### ISSUE THREAD

**Issue by adampatterson** [one-dark/jetbrains-one-dark-theme#246]
**Describe the bug**

Open excluded files have poor contrast in the tab titles.

**To Reproduce**

1. Exclude a folder and then open a file. The title of the tab is very hard to read on a dark theme.

**Expected Behavior**

I would like to easily read the tav title.

**Environment**

PhpStorm 2021.3.1
Build #PS-213.6461.83, built on December 29, 2021
Licensed to BubbleUP Marketing Corp. / Adam Patterson
You have a perpetual fallback license for this version.
Subscription is active until December 2, 2022.
Runtime version: 11.0.13+7-b1751.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
    run.processes.with.pty=TRUE

Non-Bundled Plugins:
    com.fernandojimenez.mattecarbon.theme (3.0.0)
    org.intellij.plugins.postcss (213.5744.190)
    com.markskelton.one-dark-theme (5.4.2)
    net.seesharpsoft.intellij.plugins.csv (2.18.2)
    org.asciidoctor.intellij.asciidoc (0.36.13)
    com.laravel_idea.tailwind (1.3.1)
    ru.adelf.idea.dotenv (2021.3.0.213)
    de.espend.idea.laravel (0.15.4)
    de.beyondco.tinkerwell.tinkerwell (2.0)

**Screenshots**

![image](https://user-images.githubusercontent.com/31537/149967857-23f45f4c-9b3c-42ec-bad0-6c8254e3ad71.png)

**Comment by Unthrottled** [comment]
Thank you for taking the time to report this issue and supplying the supporting information.

I'll look into what can be done to allow you to customize either the font color used for ignored/excluded files when I get time in the near future.

**Comment by Unthrottled** [comment]
Hey! I've got a couple of options for you, as this is tied to the VCS integration, I can't just change it just for non-project scoped files, it affects a bunch of other stuff. So I am not going to fix it in the plugin, I've also got other reasons for not wanting to fix it as well. However, I am open for debate 😃 

Anyways here are some option for you:

1. Change/Remove the [Non-Project File Scope color](https://www.jetbrains.com/help/idea/configuring-scopes-and-file-colors.html#new-color). Press Ctrl+Alt+S to open the IDE settings and select Appearance & Behavior | File Colors. The menu will be available there.
1. You can [export the current theme](https://www.jetbrains.com/help/idea/settings-colors-and-fonts.html). Modify the `.icls` file, replacing the `<option name="FILESTATUS_IDEA_FILESTATUS_IGNORED" value="4f575f"/>` option in the `<colors>` node, to a more visible color for you.


Hopefully that helps some, thanks for understanding! I'll close this for now, and if need be, it can be opened again.

**Comment by adampatterson** [comment]
Looks like I have come full circle. I was curious if anything may have changed since I initially logged this.

OR if you know where in PHP Storm I could adjust the colour myself.

![image](https://github.com/one-dark/jetbrains-one-dark-theme/assets/31537/57da1923-d3b0-4e34-bbf1-fce4ef2194ac)

Perhaps this is worth logging with JetBrains as it's an accessibility issue. If they split out the necessary functionality to adjust this manually or in a theme then people at-least have the option to make the change.

**Comment by adampatterson** [comment]
Perhaps this is worth logging with JetBrains as it's an accessibility issue.  If they split out the necessary functionality to adjust this manually or in a theme then people at-least have the option to make the change.
