### ISSUE TITLE
[Bug / Feature Request] Missing variable definition mark on the scrollbar

### ISSUE THREAD

**Issue by ilyapopovs** [one-dark/jetbrains-one-dark-theme#252]
**Describe the bug**

Variable definition is not marked on the scrollbar. 
In the screenshots section there is a comparison between One Dark an the default Darcula in the same scenario. 
Note there's one mark on the first image, and two marks on the second image.
I usually find it very useful to have that additional mark to tell where a variable is coming from.
Would really appreciate if it was added! :) 

**To Reproduce**
1. Create a JS scratch file (can also be reproduced with PHP and Go)
2. Define a variable (declare & give it a value)
3. Use that variable later in the file
4. Click / move the caret to the latter usage
5. Observe the scrollbar

Note: it is reproducible in any file, scratch file is just an example.

**Expected Behavior**

The place where the variable was defined is marked on the scrollbar, preferably with a different color.

**Environment**

- macos 12.2.1
- GoLand 2021.3.4
- One Dark  theme 5.5.1

**Screenshots**

![image](https://user-images.githubusercontent.com/16862411/162080787-00d46191-4978-4542-bba2-530213048819.png)
![image](https://user-images.githubusercontent.com/16862411/162080865-e08bebe5-9973-471d-a929-12f15096a582.png)

**Comment by Unthrottled** [comment]
Yeah, I like that feature! Didn't know this theme didn't implement it. I'll have some time later this week to circle back and fix this.

Just making sure we are both talking about this thing: 

<img width="200" alt="Screen Shot 2022-04-07 at 6 09 42 AM" src="https://user-images.githubusercontent.com/15972415/162186204-2670a484-8ff4-4682-8040-d653110e0da8.png">

**Comment by ilyapopovs** [comment]
Yep, thank you! 🙌

**Comment by Unthrottled** [comment]
Thank you for taking the time to fill out all the necessary details to get this added! I appreciate it.

Just for future reference, this feature is the `Error Stripe Mark`, you can customize it like this:




https://user-images.githubusercontent.com/15972415/162634485-268230be-1084-4b17-8e89-4d7a506b27e6.mp4

@all-contributors add @ilyapopovs for feature

**Comment by Unthrottled** [comment]
Guess that's what I get for not looking at the docs...

https://github.com/all-contributors add @ilyapopovs for design

**Comment by Unthrottled** [comment]
Guess that's what I get for not looking at the docs...

@all-contributors add @ilyapopovs for design

**Comment by ilyapopovs** [comment]
Looks great, thank you very much @Unthrottled! 🙌 🚀
