### ISSUE TITLE
Barely visible highlighting color

### ISSUE THREAD

**Issue by amgud** [one-dark/jetbrains-one-dark-theme#255]
**Describe the bug**

As seen in the screenshot below the first option `pa` is barely highlighted, hardly recognizable blue color on the blue background.
The original color (Dracula theme) is yellow.

**To Reproduce**

1. Choose "One Dark" theme

**Expected Behavior**

Hightlight color should be yellow

**Environment**

WebStorm 2022.1
Build #WS-221.5080.193, built on April 11, 2022
Runtime version: 11.0.14.1+1-b2043.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6.3

**Screenshots**

![image](https://user-images.githubusercontent.com/30436259/163904649-b1f58a1c-24ae-47f1-b2fb-b497559d3204.png)

**Comment by Unthrottled** [comment]
I think that was done on purpose, as to have the match highlight color match the tree row/list row selection.

<img width="274" alt="Screen Shot 2022-04-19 at 6 04 17 AM" src="https://user-images.githubusercontent.com/15972415/163990392-06d32224-7cbf-4495-b83b-6bcde5fe6cb9.png">

Changing it to another color/something more usable (such as back to yellow), is subjective. So I probably won't fix it in the plugin.

So if you care enough, I've got a [plugin](https://github.com/Unthrottled/themed-components#themed-components), that you [can make a feature request](https://github.com/Unthrottled/themed-components/issues/new?assignees=&labels=&template=feature_request.md&title=) to allow customization of the match highlight color.

Thank you for understanding.
