### ISSUE TITLE
What is the default font of theme 

### ISSUE THREAD

**Issue by bestv5** [one-dark/jetbrains-one-dark-theme#256]
What is the default font of theme  ？  or  What is the default font in preview of the plugin
![image](https://user-images.githubusercontent.com/15650275/165211717-a2dfa74d-f555-4561-b11d-4e83dff94608.png)

**Comment by Unthrottled** [comment]
@mskelton Do you know?

**Comment by mskelton** [comment]
Short answer, [Operator Mono ScreenSmart](https://www.typography.com/fonts/operator/styles/operatormonoscreensmart).  Long answer can be found on my AMA: https://github.com/mskelton/ama/issues/1
