### ISSUE TITLE
Theme 5.6.0 doesn't work in Webstorm 2022.1.1

### ISSUE THREAD

**Issue by yevsa** [one-dark/jetbrains-one-dark-theme#259]
**Describe the bug**
In 5.6.0 version there are no "One Dark"-options in Appearance - Theme selector.
After update the theme was automatically disabled and I couldn't select it again. Restart did not help.

**Environment**
WebStorm 2022.1.1
Build #WS-221.5591.52, built on May 10, 2022
Runtime version: 11.0.14.1+1-b2043.45 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Non-Bundled Plugins:
    some.awesome (1.14)
    ski.chrzanow.foldableprojectview (1.1.2)
    org.intellij.RegexpTester (1.0.8)
    lermitage.intellij.extratci (1.19.0.201)
    com.markskelton.one-dark-theme (5.5.2)
    com.jetbrains.naming-is-hard (1.1.1)
    com.intellij.ideolog (203.0.29.0)
    com.intellij.properties (221.5591.26)
    org.intellij.plugins.postcss (221.5591.19)
    com.godwin.json.parser (1.4.1)
    YAML/Ansible support (0.11.2)
    String Manipulation (9.4.0)
    zielu.gittoolbox (212.8.9)
    mobi.hsz.idea.gitignore (4.4.0)
    mdx.js (1.0.221)
    izhangzhihao.rainbow.brackets (6.23)

**Comment by Unthrottled** [comment]
I just rolled back to 2022.1.1, and downloaded the plugin and it works for me.

```
WebStorm 2022.1.1
Build #WS-221.5591.52, built on May 10, 2022
Runtime version: 11.0.14.1+1-b2043.45 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 6144M
Cores: 10
Non-Bundled Plugins:
    com.markskelton.one-dark-theme (5.6.0)
    GrepConsole (12.12.211.6693.0)
    IdeaVIM (1.10.2)
    String Manipulation (9.4.0)
    io.acari.DDLCTheme (78.2-1.1.1)
    io.unthrottled.amii (0.14.1)
    com.fwdekker.randomness (2.7.4)
    io.acari.normandy.progress.bar (1.9.13)
    io.unthrottled.theme.randomizer (0.4.0)
```


> After update the theme was automatically disabled and I couldn't select it again

That's weird, are you able to re-enable it in the plugin menu?
<img width="1094" alt="Screen Shot 2022-05-23 at 5 23 29 AM" src="https://user-images.githubusercontent.com/15972415/169799425-50fc560d-cfdd-4843-b253-7c141051b375.png">

**Comment by yevsa** [comment]
Pardon my initial wording. The plugin is enabled.
I meant that the theme was unloaded during update but did not load again.  but And I am stuck with default themes only
<img width="347" alt="Screenshot 2022-05-23 at 16 57 50" src="https://user-images.githubusercontent.com/1779779/169824914-1c2bb769-0964-4290-a3c0-322af1f4038f.png">
<img width="588" alt="Screenshot 2022-05-23 at 16 58 16" src="https://user-images.githubusercontent.com/1779779/169824924-fd31467c-09b6-47f2-951a-f7506782f27e.png">

**Comment by Unthrottled** [comment]
Hmm, that is weird, could you try a few things for me please?

- Uninstall the plugin, restart, re-install the plugin, restart.
- If that didn't work, try to [manually install it](https://one-dark.gitbook.io/jetbrains/the-basics/installation#manual)
- If that doesn't work, could you try to install another 3rd party theme, and see if those are available.

**Comment by yevsa** [comment]
Uninstall the plugin, restart and re-install the plugin helped.
But now I have two "One Dark" options:

<img width="366" alt="Screenshot 2022-05-23 at 17 58 31" src="https://user-images.githubusercontent.com/1779779/169836279-71de142e-7cab-4461-830c-ab0a29114a63.png">

**Comment by sdip15fa** [comment]
yes, it doesn't work anymore, even after reinstalling it doesn't appear in themes list

**Comment by Unthrottled** [comment]
That's odd, besides that, the theme works as expected, correct?

If so, I might have some time later to potentially investigate the issue. Something might have happened during the update that might have corrupted things.

**Comment by yevsa** [comment]
> That's odd, besides that, the theme works as expected, correct?

After a day of using I haven't noticed any other issues.

**Comment by JeremiasBohn** [comment]
I had the same issue using PyCharm 2022.1.1, uninstalling, restarting and installing it again helped. However, One Dark is only listed once for me, as intended.

**Comment by Remzi1993** [comment]
@Unthrottled I have left you some extra information in #262 Something is going wrong in the upgrade process and I have added steps for you so you can easily reproduce it yourself. Maybe this way you can get quicker to the core of the problem.

**Comment by Unthrottled** [comment]
Think this might be related to #262 . Will close in favor of that.
