### ISSUE TITLE
Version 5.6.0 is visible but intellij tries to install older version (5.3.1)

### ISSUE THREAD

**Issue by larscom** [one-dark/jetbrains-one-dark-theme#260]
Hi,

I am using Intellij IDEA ultimate:

IntelliJ IDEA 2022.1.1 (Ultimate Edition)
Build #IU-221.5591.52, built on May 10, 2022
Runtime version: 11.0.14.1+1-b2043.45 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.38-1-manjaro

When i try to install version 5.6.0 of One Dark Theme it shows an error which says it tries to install version 5.3.1 which is weird.
I tried to invalidate caches etc in Intellij IDEA but it doesn't help. I don't know if this is an issue with IntelliJ or with this plugin.

![Screenshot_20220523_164246](https://user-images.githubusercontent.com/1215195/169845438-7ba904ed-9527-4e29-a26e-252308f4a221.png)

Plugin "One Dark theme" was not installed: Downloaded version is incompatible with the current IDE: Plugin 'One Dark theme' (version '5.3.1') is not compatible with the current version of the IDE, because it requires build 212.* or older but the current build is IU-221.5591.52

Any help is appreciated, thanks!

**Comment by Unthrottled** [comment]
>I don't know if this is an issue with IntelliJ or with this plugin.

Huh, that's odd. I'm leaning to it being an issue with the platform.

Could you try a couple of things for me, please?

- Uninstall the plugin, restart, re-install the plugin, restart.
- If that didn't work, try to [manually install it](https://one-dark.gitbook.io/jetbrains/the-basics/installation#manual)

**Comment by larscom** [comment]
I coulnd't uninstall/re-install the plugin because it was not installed in the first place ;) 

Although i was using this theme before (installed successfully via the market place) and then there was an update available (version 5.6.0) 
After clicking the 'update' button that error popped up and uninstalled the previous version of this theme and set me back to the default 'darcula' theme.

I tried to invalidate caches, restart intellij several times, but it didn't help.

The only thing that worked for me was to manually install it.. thanks!

**Comment by Unthrottled** [comment]
>I couldn't uninstall/re-install the plugin because it was not installed in the first place ;)

Oh, I missed that, sorry.

I think something wonky was happening with how it was retrieving the update details from the plugin repository. Something wonky must have got cached (not in the normal clearable caches). Might have saved older data.

Example: https://plugins.jetbrains.com/plugins/list?pluginId=com.markskelton.one-dark-theme&build=221.5080.210

**Comment by larscom** [comment]
I have the same problem with other plugins. So it might indeed be an intellij problem..
