### ISSUE TITLE
Command line options are not visible on terminal, for IDE supported commands

### ISSUE THREAD

**Issue by m4heshd** [one-dark/jetbrains-one-dark-theme#261]
**Describe the bug**
The IDE highlights some terminal commands that has built-in integrations like `npm` on WebStorm. When the command is highlighted, command options become invisible even though the regular arguments looks ok.

![image](https://user-images.githubusercontent.com/6711514/170605107-9629cb34-8589-49d9-ba21-f7d290e2e1a9.png)

Here's how it looks when options are selected.

![image](https://user-images.githubusercontent.com/6711514/170605300-0554c9a5-85de-40fd-91bf-a54c646d6ab5.png)

The current workaround is to override this color using this configuration.

![image](https://user-images.githubusercontent.com/6711514/170605199-e7440bed-9d90-4f75-8f5e-a5130806f792.png)

**To Reproduce**
1. Enter a command with options on terminal that supports IDE specific integrations

**Expected Behavior**
Command line options to be visible when the command is highlighted.

**Environment**
* OS - Windows (11)
* Product - WebStorm 2022.1.1
* Plugin version - 5.6.0

**Comment by Unthrottled** [comment]
I am unable to replicate on my MacOS machine. I'll have some time later, maybe this weekend, to see if it is reproducible on my windows machine. 
 
<img width="551" alt="Screen Shot 2022-05-27 at 5 25 37 AM" src="https://user-images.githubusercontent.com/15972415/170682224-58bf97eb-7dbc-48f0-9ccc-65cebec9ce25.png">

You don't have any special  cli plugins, do you? 
Does this happen always, or just sometimes?

**Comment by m4heshd** [comment]
Thanks for the quick response @Unthrottled.

> I am unable to replicate on my MacOS machine.

Seems like it's a powershell thing (interpreter specific). This is using command prompt. 😔

![image](https://user-images.githubusercontent.com/6711514/170804370-d5062da9-ab45-412d-9c54-cd055a1b860d.png)

> You don't have any special cli plugins, do you?

Not at the moment.

> Does this happen always, or just sometimes?

It started happening after a specific IDE update about a year ago. Can't remember what exactly it was.

**Comment by Unthrottled** [comment]
Had some time to look at this, looks like it was using the `dark gray` color for named arguments

![image](https://user-images.githubusercontent.com/15972415/173255723-b4cfa4e6-be05-41d1-ac0b-e20d6d5f66cc.png)

I'll probably just do what you suggested and supply a foreground color for the `command to run using IDE` setting.

**Comment by m4heshd** [comment]
> Had some time to look at this, looks like it was using the dark gray color for named arguments

Yes. I noticed that when messing around with these settings trying to find a workaround when I originally created the issue. But I couldn't find any setting to change that to some other color.

> I'll probably just do what you suggested and supply a foreground color for the `command to run using IDE` setting.

I see that you've overridden the dark gray color completely for that demonstration but is there any possibility a theme could change the color of CLI options for specific interpreters? 🤔
