### ISSUE TITLE
[Dataspell] Notebook's "cell running" bar is too dark

### ISSUE THREAD

**Issue by ppcosmo** [one-dark/jetbrains-one-dark-theme#268]
Hi! 
Thank you for this amazing theme. It's absolutely stunning, but the "running" indicator on jupyter cells is too dark, almost invisible against the dark background.

![Screen Shot 2022-10-14 at 09 39 59](https://user-images.githubusercontent.com/97979801/195849541-532aa3ee-4098-4d00-b76a-f30af85c7523.png)

I don't know if it is an easy fix, but I'd suggest a more vibrant color for this, maybe yellow. 

All the best!

**Comment by Unthrottled** [comment]
Thanks for reporting this. I might have some time in the near future to investigate the issue.


This is just color of progress indicator below the cell executing?

**Comment by ppcosmo** [comment]
Yes, just that! For reference, this is how it looks like in the Dracula Theme:


![Screen Shot 2022-10-17 at 09 15 50](https://user-images.githubusercontent.com/97979801/196174821-121afc5b-0b81-4cdc-a7b7-3e03378d940d.png)

**Comment by Unthrottled** [comment]
Looks like it was using the progress bar . I just inverted the colors, and it uses the brighter color.

![image](https://user-images.githubusercontent.com/15972415/201447334-6491bf9f-a3f8-4414-b522-20b0d77c4c05.png)

Will stick with that.
