### ISSUE TITLE
No highlighting when using jsf/primefaces 

### ISSUE THREAD

**Issue by MakiRollDev** [one-dark/jetbrains-one-dark-theme#269]
**Description**
There is no syntax highlighting in xhtml files for jsf/primefaces components

**To Reproduce**
Open a .xhtml file and use a jsf component

**Expected Behavior**
Highlighting similar to normal html tags

**Environment**
IntelliJ IDEA 2022.2.3 (Ultimate Edition)
Build #IU-222.4345.14, built on October 5, 2022
Licensed to Nicky 
Subscription is active until November 8, 2022.
Evaluation purpose only.
Runtime version: 17.0.4.1+7-b469.62 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 750M
Cores: 8
Non-Bundled Plugins:
    com.markskelton.one-dark-theme (5.7.0)
    com.maff.codingcounter (0.6)
    com.jetbrains.darkPurpleTheme (1.3)
    com.intellij.plugins.vscodekeymap (222.4345.14)
    com.intellij.properties.bundle.editor (222.4345.14)
    org.jetbrains.kotlin (222-1.7.20-release-201-IJ4167.29)
    com.jetbrains.jax.ws (222.4345.14)
    com.github.copilot (1.1.33.1980)
    org.sonarlint.idea (7.1.1.54565)
    com.microsoft.vso.idea (1.162.0)
    com.mallowigi (73.0.0)
    PlantUML integration (5.17.1)
    com.intellij.jsf (222.4345.14)
    com.dmarcotte.handlebars (222.4345.14)
    com.github.dinbtechit.vscodetheme (1.6.2)
    fish.payara.intellij (1.4.0)
    com.microsoft.tooling.msservices.intellij.azure (3.69.0-2022.2)
    com.haulmont.jpab (2022.4.4-222)

Kotlin: 222-1.7.20-release-201-IJ4167.29

**Screenshots**
![image](https://user-images.githubusercontent.com/30658743/196644184-209bfd6d-0624-46ac-b219-bfd83fb8c6d7.png)

**Comment by Unthrottled** [comment]
Does the default intellij themes recognize the jsf tokens (does it highlight as expected)? I'll assume `com.intellij.jsf` is what determines highlighting if so.

Provide an example please if it does look as expected.

**Comment by Unthrottled** [comment]
I just cloned https://github.com/primefaces/primefaces-test

Everything appears to be in working order.

![image](https://user-images.githubusercontent.com/15972415/201449476-8af1ac02-d76a-4b83-9d27-2c42140dfdf8.png)


I'll close this issue.

 However if you can provide detailed reproduction steps and what you are actually expecting, like if the default intellij theme highlights it (I don't know what to expect, but it looks fine to me as it is.). I'll try again.
