### ISSUE TITLE
NewUI - Run with options toolbar widget - little contrast on text, very hard to read

### ISSUE THREAD

**Issue by surgicalcoder** [one-dark/jetbrains-one-dark-theme#271]
Running the NewUI on Rider - the "Run with options toolbar widget" in the top right hand corner, the grey text is barely readable on the green background when something is being run:

![image](https://user-images.githubusercontent.com/1169543/200200406-bf247475-df1a-43ed-9cd8-94c2a68ff47a.png)

When it's not being run, it looks perfectly fine:

![image](https://user-images.githubusercontent.com/1169543/200200447-b7bb36f6-57f4-4ba1-8700-322a0247d7d0.png)

Feel like the text should either be white (instead of grey) or dark to contrast better.

**Comment by Unthrottled** [comment]
Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

It should contain:
* OS (Windows, Linux, Mac)
* IntelliJ Product + version (IDEA, RubyMine...)
* Plugin version 
* A list of enabled plugins

Here's mine as an example

```
IntelliJ IDEA 2022.2.2 (Ultimate Edition)
Build #IU-222.4167.29, built on September 13, 2022
Runtime version: 17.0.4+7-b469.53 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.0
GC: G1 Young Generation, G1 Old Generation
Memory: 10280M
Cores: 10
Metal Rendering is ON
Registry:
    debugger.click.disable.breakpoints=true
    ide.intellij.laf.enable.animation=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    io.unthrottled.theme.randomizer (0.7.1)
    com.intellij.properties.bundle.editor (222.4167.21)
    org.jetbrains.kotlin (222-1.7.20-release-201-IJ4167.29)
    com.fwdekker.randomness (2.7.5)
    io.acari.DDLCTheme (88.1-1.5.4)
    io.unthrottled.amii (1.1.3)
    String Manipulation (9.6.1)
    IdeaVIM (1.11.1)
    GrepConsole (12.15.211.6693.1)
    izhangzhihao.rainbow.brackets (6.26)

Kotlin: 222-1.7.20-release-201-IJ4167.29
```

**Comment by surgicalcoder** [comment]
JetBrains Rider 2022.3 EAP 7
Build #RD-223.7401.6, built on November 1, 2022
Licensed to JetBrains Rider EAP user: surgicalcoder
Expiration date: December 1, 2022
Runtime version: 17.0.5+1-b653.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
.NET 7.0.0 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 16
Registry:
    ide.experimental.ui=true
    indexing.enable.entity.provider.based.indexing=false
    ide.new.project.model.index.case.sensitivity=true
    vcs.empty.toolwindow.show=false
    ide.workspace.model.rbs.as.tree=false
    database.show.search.tab=false
    rdclient.asyncActions=false

Non-Bundled Plugins:
    idea.plugin.protoeditor (223.7401.10)
    com.intellij.ideolog (203.0.30.0)
    com.markskelton.one-dark-theme (5.7.0)
    String Manipulation (9.6.1)
    com.arcticicestudio.nord.jetbrains (0.13.0)
    com.intellij.resharper.StructuredLogging (2022.3.0.263-eap05)
    com.microsoft.vso.idea (1.162.0)
    com.intellij.resharper.azure (3.50.0.1519-2022.3)

**Comment by Unthrottled** [comment]
Great thanks! I'll eventually get around to reproducing the issue on my windows machine. 

Hopefully there is a way to provide an isolated fix ([hasn't been the case with other issues](https://github.com/one-dark/jetbrains-one-dark-theme/issues/267#issuecomment-1259356163))

**Comment by Unthrottled** [comment]
I think this is my favorite thing about the experimental UI.

https://github.com/JetBrains/intellij-community/blob/2c7f2e25baa4cfda82c71b20ab6e525ce1fc1ebd/platform/execution-impl/src/com/intellij/execution/ui/RedesignedRunWidget.kt#L139

They just slap stuff in with no obvious way to see how to customize it. 😄 

Maybe I'm being impatient. I'll look harder, but I hope there is a way to isolate the changes to just the button selected foreground/icon color

**Comment by iamim** [comment]
Still a problem for me with 5.7.1 :(
Should I check something?

**Comment by Unthrottled** [comment]
@iamim Yeah, make sure you are on the latest version of whatever platform you are using.

**Comment by iamim** [comment]
I'm using Rider 2022.3 EAP9 on macOS , Windows 10 and Windows 11 ARM. I see it the same way as the first picture in this   issue on all 3 platforms.

**Comment by Unthrottled** [comment]
Step 1: Put changes related to this in the correct place.
Step 2: ???
Step 3: 🎉

🤦‍♂️

@iamim I drafted #278 , going to wait a while before releasing it though. I attached the version with the fix here https://github.com/one-dark/jetbrains-one-dark-theme/pull/278#issuecomment-1334685980

You can also build from the source as well https://one-dark.gitbook.io/jetbrains/contributing/development#building-the-plugin if needed 😃

**Comment by iamim** [comment]
Awesome! Thanks a lot for your work :)
