### ISSUE TITLE
Change paramenter color!

### ISSUE THREAD

**Issue by osh91** [one-dark/jetbrains-one-dark-theme#275]
**Describe the bug**
Please change the parameter colour because I thought I have implemented the wrong parameters. Check the picture. I don't find it friendly to see the red colour. Please change it to maybe lime-green or neon or light purple?? 

**Environment**
Android Studio Dolphin | 2021.3.1 Patch 1
Build #AI-213.7172.25.2113.9123335, built on September 30, 2022
Runtime version: 11.0.13+0-b1751.21-8125866 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    some.awesome (1.14)
    com.vermouthx.idea (1.13.3)
    com.markskelton.one-dark-theme (5.7.1)
    com.jetbrains.darkPurpleTheme (1.3)
    com.google.d2c.androidstudio.plugin (0.3.00)
    com.example.code-reactions (1.0-SNAPSHOT)
    izhangzhihao.rainbow.brackets (2022.3.4-ij)
    com.clutcher.comments_highlighter (2.4.1)

It should contain:
* OS (Windows, Linux, Mac)
* IntelliJ Product + version (IDEA, RubyMine...)
* Plugin version 
* If needed a list of enabled plugins -->

**Screenshots**
![image](https://user-images.githubusercontent.com/16814145/202698567-97db0be9-f3eb-4c49-96c0-5ed0765c33d6.png)

**Comment by osh91** [comment]
![image](https://user-images.githubusercontent.com/16814145/202699171-4d793fcf-dcf2-4c82-a79d-a61423ef415a.png)

**Comment by Unthrottled** [comment]
I think that is the [coral color](https://one-dark.gitbook.io/jetbrains/contributing/development#color-palette) (which is a different color from the error) of the one dark color palette. So not going to change the existing color palette.

Thankfully, the platform allows you to customize the color scheme to your liking. You can easily change/find colors of tokens in the editor using the [jump to colors and fonts action](https://www.jetbrains.com/help/idea/configuring-colors-and-fonts.html#jump_to_colors_and_fonts).
