### ISSUE TITLE
New UI: Please highlight Run Configurations Widget in Tool Bar

### ISSUE THREAD

**Issue by nineninesevenfour** [one-dark/jetbrains-one-dark-theme#280]
The following is a matter of taste for sure. I also do not know, if this is possible.

Today I activated the new UI through the 2022.3 update. While (apart from the editor theme) the differences in the Jetbrain's default dark theme and "One Dark" became a little less distinctive, I still choose "One Dark" because it has more contrast and saturation.

There is one obvious difference though: The missing highlight of the "Run Configurations" widget.
Jetbrain's default dark:
![grafik](https://user-images.githubusercontent.com/75562299/205337659-847baee7-7f10-4112-ac68-a61f7f9a0da4.png)
One Dark:
![grafik](https://user-images.githubusercontent.com/75562299/205337746-29e64d04-4cc3-4de5-9dac-ac2b5e920e92.png)

I'd personally prefer the highlighted (colored) version.
I understand of course, if this is just rejected, but maybe others see it the same way. 😊
Thank you in advance!

**Comment by Unthrottled** [comment]
Ah, yeah. I meant to fix that in the last version, but I goofed it up.

You can find the version with the run widget in blue on #278 

See https://github.com/one-dark/jetbrains-one-dark-theme/issues/271#issuecomment-1334688103 for more details on ways of installing.

**Comment by nineninesevenfour** [comment]
Great! Checked out 'expUISupport', manually added the built plugin and can confirm that it is fixed! 👍
