### ISSUE TITLE
Run button text unclear in new UI

### ISSUE THREAD

**Issue by RaenonX** [one-dark/jetbrains-one-dark-theme#281]
**Describe the bug**

Visual issue. Text for running config is not to see.

![image](https://user-images.githubusercontent.com/18443743/205516063-546261fc-f54c-4340-8279-683d41f02c46.png)

**To Reproduce**

> Use new UI.

1. Run any run config

**Expected Behavior**

Easier to see the texts.

**Environment**

Build #PY-223.7571.203, built on November 30, 2022

Runtime version: 17.0.5+1-b653.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

Windows 11

Plugin version: 5.7.1.

**Comment by Unthrottled** [comment]
Please see this https://github.com/one-dark/jetbrains-one-dark-theme/issues/280#issuecomment-1335508244

**Comment by RaenonX** [comment]
> Please see this https://github.com/one-dark/jetbrains-one-dark-theme/issues/280#issuecomment-1335508244

Thanks! Is there any planned date for formal release? Doesn't have to be the current style, but just want to know if the coloring improvement will be released some day in the future or not.

**Comment by CameO73** [comment]
If you want to use it right now, you could simply:
- Download the 5.7.2 ZIP from https://github.com/one-dark/jetbrains-one-dark-theme/pull/278#issuecomment-1334685980
- Use the "Install Plugin from disk" option in the Plugins dialog (option in the cog wheel menu)

**Comment by Unthrottled** [comment]
@RaenonX Was planning on  working on adding some extra things in tomorrow and publishing the release then. Thanks for the patience!

**Comment by RaenonX** [comment]
> @RaenonX Was planning on  working on adding some extra things in tomorrow and publishing the release then. Thanks for the patience!

No problem, I'll wait for the release then, thanks!

Also thanks for your hard work!
