### ISSUE TITLE
Theme sometimes doesn't recognize Rust keywords, sometimes does recognize the same keyword

### ISSUE THREAD

**Issue by daym** [one-dark/jetbrains-one-dark-theme#283]
It seems that one dark theme doesn't recognize `self` as a keyword in `mut self` and `&mut self`, but it does recognize `self` as a keyword in `self` and `&self`.

![image](https://user-images.githubusercontent.com/7755349/206586155-14c642da-b018-41de-9d47-1485a0e8ab7c.png)

Tried commit 33f92a9729e13e21e90d0c98082af5c18944fcd7 too, same issue. IntelliJ IDEA Community Edition  2022.3 with Rust plugin (on Linux).

```
IntelliJ IDEA 2022.3 (Community Edition)
Build #IC-223.7571.182, built on November 29, 2022
Runtime version: 17.0.3+0-adhoc..source amd64
VM: OpenJDK 64-Bit Server VM by N/A
Linux 5.4.224
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Non-Bundled Plugins:
    PsiViewer (223-SNAPSHOT)
    com.example.RIdiom (7.0-SNAPSHOT)
    intellij-scheme (0.1.10)
    com.markskelton.one-dark-theme (@version@)
    com.adacore.Ada-IntelliJ (0.6-dev)
    org.rust.lang (0.4.185.SNAPSHOT-223-dev)
    com.alex.tokyonight (0.1.5)
    com.github.jef.forest-night (1.3.0)
    com.friendly-machines.intellij.plugins.idea-native2-debugger (1.0-SNAPSHOT)
    PythonCore (223.7571.182)
    ru.meanmail.plugin.requirements (2022.4)
    intellij-micropython (1.4.0)
    izhangzhihao.rainbow.brackets (2022.3.5)
    com.urswolfer.intellij.plugin.gerrit (1.2.6-203)
    mobi.hsz.idea.gitignore (4.4.4)

Kotlin: 223-1.7.20-release-201-IJ7571.182
Current Desktop: GNOME
```

It might be done by the extra annotator of intellij-rust ( https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/annotator/RsHighlightingMutableAnnotator.kt ).

For comparison: It works with Darcula.

**Comment by Unthrottled** [comment]
Looks like its an issue with the platform/Rust plugin. Looks like it _is_ (should be) recognized, but for whatever reason the editor is dumb. Looks to not be a one dark issue.

**Expected**

<img width="459" alt="Screenshot 2022-12-08 at 7 45 06 PM" src="https://user-images.githubusercontent.com/15972415/206604574-428b9335-a045-4d12-a1fa-764cf5c0caa2.png">

**Actual**

My theme:
<img width="489" alt="Screenshot 2022-12-08 at 7 45 52 PM" src="https://user-images.githubusercontent.com/15972415/206604611-1f2785e6-f54d-4f3a-8c44-0cc37e020587.png">

Darcula
<img width="543" alt="Screenshot 2022-12-08 at 7 46 12 PM" src="https://user-images.githubusercontent.com/15972415/206604692-7e231b2a-9b18-424c-b4bc-f9d51d619322.png">

After further digging into it https://www.jetbrains.com/help/idea/configuring-colors-and-fonts.html#jump_to_colors_and_fonts

Darcula:
<img width="574" alt="Screenshot 2022-12-08 at 7 40 11 PM" src="https://user-images.githubusercontent.com/15972415/206603636-5ba6ba2e-0f09-4133-be71-a7f5b58b21c3.png">

<img width="523" alt="Screenshot 2022-12-08 at 7 42 34 PM" src="https://user-images.githubusercontent.com/15972415/206605105-a5f99e8e-eda1-4d54-9b07-fc562bf205a0.png">


You can see it's there & being recognized, just dunno which of those takes the priority.

I'll leave it to you to play around with.

If you want more of my help, please follow the issue template and provide supporting information. I don't know much of rust, and don't know the expected result. Not helping me help you will result in me not working & closing both issues you opened. 

Thanks!

**Comment by daym** [comment]
Aha! Debugging by key combo Ctrl-Shift-A and `Jump to Colors and Fonts` is totally useful. I had not known that. Thanks!

In Rust, `self` is a keyword, so ideally it would be detected as a keyword whereever it is.

And the underline is in order to detect mutable variables (basically, Rust made variables const by default--and if you want it to be non-const, you have to give a keyword `mut`).

So I'd expect `mut self` be keyword-colored and `self` to be underlined since it can be reassigned (which is uncommon to have in Rust).

That's what Darcula does here. Not in your case, though. Huh.

Writing `self` alone without a colon in function parameters is a shorthand for `self: Self`, and writing `&self` alone without a colon in function parameters is a shorthand for `self: &Self`, and writing `&mut self` alone without a colon in function parameters is a shorthand for `self: &mut Self`. The stuff after the colon is the type. (`&mut` makes an exclusive read-write reference type, and `&` makes a shared read-only reference type)

I just found out that if I set both foreground and background of Keyword then it works:

![image](https://user-images.githubusercontent.com/7755349/206784624-96f76318-5c0e-47c9-9d0a-b3fd9b2ed2cd.png)

If I remove the checkbox at `Background` then it breaks.

Huh.

P.S. How did you make the identifiers be in a different font entirely? Neat.

**Comment by daym** [comment]
It was my fault. And you are totally right, it's a priority thing. I also had foreground color set for `Mutable Parameter`, and that clashed with the other one from the keyword.

There (`Foreground` checkbox on the right-hand side):
![image](https://user-images.githubusercontent.com/7755349/206785944-d462bb62-1431-4c76-9e64-7a7fd5d30dd7.png)

After removing the check there, it works better in one dark:

![image](https://user-images.githubusercontent.com/7755349/206786486-3fa7ca20-94b6-4b88-a0bc-0a4e0ea7a3b3.png)

And after removing the following check on `Foreground` on `Unused code` it works perfectly (and I added strikethrough instead :) ):

![image](https://user-images.githubusercontent.com/7755349/206788151-8564d250-2723-4736-b5f2-e84e6fd03e0b.png)
