### ISSUE TITLE
Memory Indicator colors are off

### ISSUE THREAD

**Issue by michewl** [one-dark/jetbrains-one-dark-theme#284]
**Describe the bug**

The memory indicator colors are off in all four theme variants.

**To Reproduce**

1. Show the memory indicator (New UI Preview): `View` > `Appearance` > `Status Bar Widgets` > `Memory Indicator`

**Expected Behavior**

The memory indicator should follow the theme colors.

**Environment**

```
IntelliJ IDEA 2022.2.4 (Ultimate Edition)
Build #IU-222.4459.24, built on November 22, 2022
Runtime version: 17.0.5+7-b469.71 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.0.6-76060006-generic
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.markskelton.one-dark-theme (5.7.2)
```

**Screenshots**

![memory-indicator](https://user-images.githubusercontent.com/774221/207269240-316bb1f3-db8c-40dd-9f3c-491de15ff688.jpg)

**Comment by Unthrottled** [comment]
I'll give it a look sometime in the near future, thanks for reporting.

**Comment by Unthrottled** [comment]
Looks like it's off in the regular UI as well.

<img width="144" alt="Screenshot 2022-12-15 at 7 34 40 PM" src="https://user-images.githubusercontent.com/15972415/208001723-ccfb3164-4575-4f9a-a6c5-272c2df00066.png">

**Comment by Unthrottled** [comment]
I drafted #286, going to wait a while before releasing it though. I attached the version with the fix here https://github.com/one-dark/jetbrains-one-dark-theme/pull/286#issuecomment-1355313076

You can also build from the source as well https://one-dark.gitbook.io/jetbrains/contributing/development#building-the-plugin if needed/wanted 😃
