### ISSUE TITLE
Font color

### ISSUE THREAD

**Issue by theofrgs** [one-dark/jetbrains-one-dark-theme#285]
**Describe the bug**
The font dont load i still have grey color.
**To Reproduce**

1.

**Expected Behavior**
Expect to have color on each object as the screen in readme.

**Environment**
Build #IU-223.7571.182, built on November 29, 2022
Mac last version
<img width="854" alt="Capture d’écran 2022-12-15 à 14 12 41" src="https://user-images.githubusercontent.com/60193575/207978306-d6f4f519-7cb3-4388-8523-9463a691f9b2.png">

Last pluggin version 5.7.2

It should contain:
* OS (Windows, Linux, Mac)
* IntelliJ Product + version (IDEA, RubyMine...)
* Plugin version 
* If needed a list of enabled plugins -->

**Screenshots**

**Comment by Unthrottled** [comment]
Fairly confident that this is an issue with your project set up and not the theme itself. Your IDE has to recognize the file your looking at as part of the sources. Once you've gotten your project fixed, you get the intelligent editing & syntax highlighting. This plugin just colors the syntax highlighting it doesn't provide the functionality. 

Here is an example of me adding an extra sources root to a maven project.

https://user-images.githubusercontent.com/15972415/208000458-6eeb5927-6256-4c15-a98b-c6671957e086.mp4

Will close the issue, because I am fairly confident that it is a project setup issue.

**Comment by theofrgs** [comment]
I think it’s a project configuration issue too but all my file are like this and the project reconsize them as java file because I have the right icon.

De : Alex Simons ***@***.***>
Date : jeudi, 15 décembre 2022 à 17:27
À : one-dark/jetbrains-one-dark-theme ***@***.***>
Cc : Théo Fargeas ***@***.***>, Author ***@***.***>
Objet : Re: [one-dark/jetbrains-one-dark-theme] Font color (Issue #285)

Fairly confident that this is an issue with your project set up and not the theme itself. Your IDE has to recognize the file your looking at as part of the sources. Once you've gotten your project fixed, you get the intelligent editing & syntax highlighting. This plugin just colors the syntax highlighting it doesn't provide the functionality.

Here is an example of me adding an extra sources root to a maven project.

https://user-images.githubusercontent.com/15972415/208000458-6eeb5927-6256-4c15-a98b-c6671957e086.mp4

Will close the issue, because I am fairly confident that it is a project setup issue.

**Comment by theofrgs** [comment]
There is the screenshot i can make the root as directory in intellij
<img width="1728" alt="Capture d’écran 2022-12-17 à 22 40 20" src="https://user-images.githubusercontent.com/60193575/208285138-a2c9b3ce-d1e7-4935-b70b-f6afa5bc8d9d.png">

**Comment by Unthrottled** [comment]
Ah, just start right clicking `build.gradle` files in you project and importing them. Start at the top and work your way down if needed. The top build gradle should import all the stuff. Your project set up should be fixed after that. Your side bar has all the files highlighted with a red/yellow background meaning they aren't recognized as project files. Importing should fix that.

https://user-images.githubusercontent.com/15972415/208315089-a396f496-00f5-4482-a585-fcf4dbe49187.mp4

**Comment by theofrgs** [comment]
Thanks it was that, than you for your time !
