### ISSUE TITLE
Checked checkboxes are invisible

### ISSUE THREAD

**Issue by AbeJellinek** [one-dark/jetbrains-one-dark-theme#288]
**Describe the bug**
Checked checkboxes are invisible everywhere with the theme enabled.

**To Reproduce**
1. Enable the theme (any variant).
2. Go to the Preferences, the Commit pane, or somewhere else with checkboxes.

**Expected Behavior**
Visible checkboxes.

**Environment**
```
IntelliJ IDEA 2022.3.1 (Ultimate Edition)
Build #IU-223.8214.52, built on December 20, 2022
Runtime version: 17.0.5+1-b653.23 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4192M
Cores: 10
Metal Rendering is ON

Non-Bundled Plugins:
    org.rust.lang (0.4.185.5086-223)
    com.markskelton.one-dark-theme (5.7.2)
    Dart (223.8214.16)
    dev.blachut.svelte.lang (223.8214.16)
    io.flutter (71.2.6)
    Pythonid (223.8214.52)
    zielu.gittoolbox (213.10.5)

Kotlin: 223-1.7.21-release-272-IJ8214.52
```

**Screenshots**
<img width="347" alt="image" src="https://user-images.githubusercontent.com/1770299/209443825-2f368eb0-fcf6-4a24-9a04-de63c4889f9f.png">
<img width="318" alt="image" src="https://user-images.githubusercontent.com/1770299/209443833-d19f481f-375e-4d4a-9d82-77b631c06ade.png">

**Comment by Unthrottled** [comment]
https://user-images.githubusercontent.com/15972415/209741586-37712186-b74f-4ddc-a9d0-5e002dc9032e.mp4



```
IntelliJ IDEA 2022.3.1 (Ultimate Edition)
Build #IU-223.8214.52, built on December 20, 2022
Runtime version: 17.0.5+1-b653.23 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 752M
Cores: 10
Metal Rendering is ON
Non-Bundled Plugins:
    com.markskelton.one-dark-theme (@version@)

Kotlin: 223-1.7.21-release-272-IJ8214.52
```

Hey, I am having a difficult time replicating the issue. We've essentially got the same machine & IDE. I wonder why nobody else has complained about it, is it still happening?

**Comment by Unthrottled** [comment]
I'll upgrade to Ventura 13.1 later this week, and see if it is an issue then. If it is, then I'll complain to JetBrains.

**Comment by Unthrottled** [comment]
Still not able to replicate.

```
IntelliJ IDEA 2022.3.1 (Ultimate Edition)
Build #IU-223.8214.52, built on December 20, 2022
Runtime version: 17.0.5+1-b653.23 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.1
GC: G1 Young Generation, G1 Old Generation
Memory: 752M
Cores: 10
Metal Rendering is ON
Registry:
    eslint.additional.file.extensions=svelte

Non-Bundled Plugins:
    org.rust.lang (0.4.185.5086-223)
    com.markskelton.one-dark-theme (@version@)
    Dart (223.8214.16)
    dev.blachut.svelte.lang (223.8214.16)
    io.flutter (71.2.6)
    Pythonid (223.8214.52)
    zielu.gittoolbox (213.10.5)

Kotlin: 223-1.7.21-release-272-IJ8214.52
```

All of the check box coloring does not have any transparency set

https://github.com/one-dark/jetbrains-one-dark-theme/blob/master/buildSrc/templates/oneDark.template.theme.json#L475

So do not know why the check-boxes become invisible. That being said, I am fairly confident that the fix won't be done in this plugin.  This sounds like either an issue on your machine or an issue with the platform itself (intellij). 

Am going to close this for now, if I am able to replicate and it is because of the plugin. Will re-investigate. 

Thanks for understanding & taking the time to submit the issue.

**Comment by almeric** [comment]
I have the same issue, only when enabling the 'new ui' option in intellij. Made a video:


https://user-images.githubusercontent.com/1922968/224250757-01ec3452-ff38-4e9f-a7d0-f84f065d928d.mov

IntelliJ IDEA 2022.3.3 RC (Ultimate Edition)
Build #IU-223.8836.35, built on March 8, 2023
Runtime version: 17.0.6+1-b653.34 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Non-Bundled Plugins:
    rocks.blackcat.vcl (0.7.2)
    org.intellij.plugins.postcss (223.7571.117)
    com.intellij.ideolog (203.0.30.0)
    com.markskelton.one-dark-theme (5.7.4)
    org.jetbrains.compose.desktop.ide (1.3.1)
    com.github.inxilpro.intellijalpine (v0.4.2)
    mobi.hsz.idea.gitignore (4.4.4)
    com.brandiico.jetbrains-nightfall-theme (1.1.7)
    com.jetbrains.php (223.8836.39)
    izhangzhihao.rainbow.brackets (2023.2.6)
    org.jetbrains.plugins.phpstorm-remote-interpreter (223.7571.117)
    de.timo_reymann.intellij-mjml-support (2.4.0)
    com.jetbrains.twig (223.8836.30)
    com.kalessil.phpStorm.phpInspectionsEA (4.0.7.1)
    org.jetbrains.plugins.phpstorm-docker (223.7571.117)
    ru.adelf.idea.dotenv (2022.3)
    de.espend.idea.php.annotation (9.0.0)
    fr.adrienbrault.idea.symfony2plugin (2022.1.242)
    com.intellij.php.tools.quality.phpstan (223.8836.35)
    de.php_perfect.intellij.ddev (1.0.4)
    com.jetbrains.php.blade (223.8836.35)
    de.espend.idea.laravel (0.15.4)
    com.kalessil.phpStorm.yii2inspections (1.0.6)

Kotlin: 223-1.8.0-release-345-IJ8836.35

**Comment by Unthrottled** [comment]
@almeric If I had to hazard a guess, enabling the new ui button triggers a bunch of stuff behind the scenes. Considering they ask you to restart the ide after enabling it. Is it reproducible if you never touch the new ui checkbox?

**Comment by almeric** [comment]
Sorry wasn't exactly clear, it's not so much the new ui checkbox, the problem with checked checkboxes not visible is only when the new ui is enabled.

When clicking on the checkboxes the checkmark is visible, but when opening any settings screen, or commit window, or anything with checkboxes the checked ones aren't visible until you toggle them manually.

This problem doesn't exist when the new ui is disabled.

Hopefully that makes sense?

**Comment by Unthrottled** [comment]
> the problem with checked checkboxes not visible is only when the new ui is enabled.

Yeah, no I got it, thanks. My point was does the problem persist after you restart the IDE. You clicked the new UI checkbox a bunch without restarting the IDE. Anytime the new UI checkbox is updated (checked or not) you need to restart the IDE. Touching that box does a bunch of stuff. The period between updating the box and restarting, UI behavior is undefined and not supported. Which is what your video primarily showed. If it persists after a restart, then that's another thing.

That being said, the issue is _not_ from the plugin itself, but the platform. The fix _will not_ be on the plugin side. So probably will need to submit an issue to JetBrains.

**Comment by almeric** [comment]
Yeah did restart the ide, doesn't help.

> That being said, the issue is not from the plugin itself, but the platform. The fix will not be on the plugin side. So probably will need to submit an issue to JetBrains.

No prob, will see if I can file an issue there. 
Thanks!
