### ISSUE TITLE
Rider - Discrepancy between OneDark and OneDark Italic in intellisense dialog

### ISSUE THREAD

**Issue by dorudumitru-hh** [one-dark/jetbrains-one-dark-theme#290]
**Environment**

* OS: Linux
* IntelliJ Product: JetBrains Rider 2022.3.1 Build #RD-223.8214.53, built on December 20, 2022
* Plugin version: 5.7.2

**Screenshots**

* OneDark:
![Screenshot from 2023-01-17 13-51-13](https://user-images.githubusercontent.com/40240395/212894423-c5c9d0b5-db9f-4bfb-ac2a-76f3a993b5ba.png)

* OneDark Italic
![Screenshot from 2023-01-17 13-53-59](https://user-images.githubusercontent.com/40240395/212894627-76bee5d9-ed74-44b8-b81d-1569f91ef153.png)

**Comment by Unthrottled** [comment]
I am not able to reproduce on

```
JetBrains Rider 2022.3.1
Build #RD-223.8214.53, built on December 20, 2022
Runtime version: 17.0.5+1-b653.23 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-122-generic
.NET 7.0.0 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 12
Registry:
    ide.mac.bigsur.window.with.tabs.enabled=false
    platform.projectModel.workspace.model.file.index=false
    database.show.search.tab=false
    vcs.empty.toolwindow.show=false
    ide.workspace.model.rbs.as.tree=false
    indexing.enable.entity.provider.based.indexing=false
    ide.new.project.model.index.case.sensitivity=true
    rdclient.asyncActions=false

Non-Bundled Plugins:
    com.markskelton.one-dark-theme (5.7.2)
    IdeaVIM (2.1.0)
    com.microsoft.vso.idea (1.162.0)
    io.acari.DDLCTheme (88.3-1.8.1)
    io.unthrottled.amii (1.1.4)

Current Desktop: ubuntu:GNOME
````

Does the issue persist after restarting the IDE?

**Comment by dorudumitru-hh** [comment]
Yes. I've also uninstalled the plugin, restart IDE, installed plugin, restart IDE, and the issue persists. The issue seems to appear also on OneDark Vivid Italic. Also, the IDE is installed on 2 different machines and the issue is present on both.
