### ISSUE TITLE
Experimental UI: Spaces/Padding in File Tree

### ISSUE THREAD

**Issue by jkroepke** [one-dark/jetbrains-one-dark-theme#291]
Personally, I'm missing the padding/spaces in One Dark Theme. Is it possible that One Dark Theme just changing the colors and inherit the spaces from original themes?

Example

IDEA Dark Theme:

<img width="611" alt="image" src="https://user-images.githubusercontent.com/1560587/213582619-2b87c59f-c561-4322-a40c-4583abed64db.png">

One Dark Theme:

<img width="610" alt="image" src="https://user-images.githubusercontent.com/1560587/213582496-adfe5c80-1611-4808-aaa2-f06d377de219.png">

**Comment by Unthrottled** [comment]
Might be the difference between the expui theme's insets.

https://github.com/JetBrains/intellij-community/blob/c037a653e26f2bc7e125e339fd781584e3ebbf4a/platform/platform-resources/src/themes/expUI/expUI_dark.theme.json#L260

Probably not going to change it, because it would affect the non-experimental UI as well. Will check to see if it does, probably going to close this after verification. Thanks!

**Comment by Unthrottled** [comment]
With the latest code you'll want to update the code here:

https://github.com/one-dark/jetbrains-one-dark-theme/blob/c78b01d461178c37c78ce3b6c8b9a569969df180/buildSrc/templates/oneDark.template.theme.json#L439

to have: 

```json
    "Tree": {
      "selectionBackground": "#4d78cc",
      "modifiedItemForeground": "accentColor",
      "selectionInactiveForeground": "foregroundColor",
      "rowHeight": 24,
      "border": "4,12,4,12"
    }
```

☝️ this affects all UIs, so not adding it in as part of the main theme, but you are free to run your own custom version :)

**Comment by jkroepke** [comment]
@Unthrottled I see the Upcoming EAP version introduce a compact mode 

https://blog.jetbrains.com/idea/2023/02/intellij-idea-2023-1-eap-3/#CompactModeforthenewUI

Maybe One Dark Theme can use this, too?

**Comment by Unthrottled** [comment]
It already can


https://user-images.githubusercontent.com/15972415/219971774-516ce22c-7db5-48bc-815b-a5da4319d201.mp4



```IntelliJ IDEA 2023.1 EAP (Ultimate Edition)
Build #IU-231.7515.13, built on February 16, 2023
Runtime version: 17.0.6+10-b829.1 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 752M
Cores: 10
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.markskelton.one-dark-theme (@version@)
```

**Comment by lsalazarm99** [comment]
> Probably not going to change it, because it would affect the non-experimental UI as well.

@Unthrottled The "experimental UI" is the default UI now. Do you think this can be implemented? It seems like compact mode, and the compact mode switch itself seems inverted with this plugin, as shown in your video.

**Comment by lsalazarm99** [comment]
I applied the changes described [here](https://github.com/one-dark/jetbrains-one-dark-theme/pull/311#issuecomment-2439544979) and this is how it looks like:

![image](https://github.com/user-attachments/assets/c1c1179b-f1bb-4dac-adc1-384d61ea7c28)
