### ISSUE TITLE
'Mute breakpoints' indicator is broken in IntelliJ's new UI

### ISSUE THREAD

**Issue by Guy-Curtis** [one-dark/jetbrains-one-dark-theme#292]
The 'mute breakpoints' button within the debugger no longer indicates when it is active when using IntelliJ's new UI.

![Screenshot 2023-01-25 at 11 10 52](https://user-images.githubusercontent.com/25356084/214549128-132af1d7-5060-4090-8e5c-fd3a011f30cf.png)

**Comment by Unthrottled** [comment]
I drafted https://github.com/one-dark/jetbrains-one-dark-theme/pull/293, going to wait a while before releasing it though. I attached the version with the fix here https://github.com/one-dark/jetbrains-one-dark-theme/pull/293#issuecomment-1405861982

You can also build from the source as well https://one-dark.gitbook.io/jetbrains/contributing/development#building-the-plugin if needed/wanted 😃

**Comment by Guy-Curtis** [comment]
Thanks for sorting! Do you want this ticket left open until the PR is done?

**Comment by Unthrottled** [comment]
Yeah, it can be left open, it will get closed when the PR is merged, thanks.
