### ISSUE TITLE
Experimental UI: Find replace search box off vertical center

### ISSUE THREAD

**Issue by DragonAxe** [one-dark/jetbrains-one-dark-theme#294]
In Idea's New UI, the find replace search box text is off vertical center:

![image](https://user-images.githubusercontent.com/12703200/216106831-b269ca2f-b788-4819-8736-ed3c7b2aa67f.png)

![image](https://user-images.githubusercontent.com/12703200/216107098-07887293-d612-48cf-939c-54e95ac7f4f2.png)

In this issue, JetBrains indicates this is a theme issue. Testing with 'Dark' theme, I get the desired vertical alignment.
https://youtrack.jetbrains.com/issue/IDEA-311366

**Comment by Unthrottled** [comment]
Huh, I never noticed that. I'll see what I can do.

**Comment by Unthrottled** [comment]
Looks like it is this property

https://github.com/JetBrains/intellij-community/blob/fab6d931f166c7407a70ba326a847464ea49d074/platform/platform-resources/src/themes/expUI/expUI_dark.theme.json#L237

Not going to change this, as it breaks the existing UI.

Feel free to make the changes on your own local copy though. Thanks!

**Comment by DragonAxe** [comment]
Thanks for taking a look!
