### ISSUE TITLE
Conflict with zsh-autosuggestions

### ISSUE THREAD

**Issue by liby** [one-dark/jetbrains-one-dark-theme#295]
I find that there are some conflicts with [zsh-autosuggestionsat](https://github.com/zsh-users/zsh-autosuggestions) the beginning of recent versions.

You can see that the foreground color of auto suggestions is not displayed correctly when you type `yarn b...`.

https://user-images.githubusercontent.com/38807139/216800245-db3a2386-5a1c-41da-b16d-28c072212321.mp4

CLion 2022.3.2
[One Dark theme 5.7.2](https://plugins.jetbrains.com/plugin/11938-one-dark-theme/versions/stable/264081)

**Comment by Unthrottled** [comment]
That's a feature of the IDE

https://blog.jetbrains.com/idea/2020/07/run-ide-features-from-the-terminal/

You can change the color going to the settings `Editor -> Color Scheme -> Console Colors` 
<img width="1012" alt="Screenshot 2023-02-05 at 8 19 06 AM" src="https://user-images.githubusercontent.com/15972415/216825054-47a02e98-9356-4a54-af6a-df441610bd79.png">
