### ISSUE TITLE
macOS, Experimental UI horizontal scroll has default styles

### ISSUE THREAD

**Issue by iamim** [one-dark/jetbrains-one-dark-theme#296]
**Describe the bug**
On macOS with Experimental UI the horizontal scroll has default colors when they should be transparent. Appears not only in the editor scroll bar.

**To Reproduce**

1. Install any supported (only tested Rider) IDE
2. Enable Experimental UI
3. Observe horizontal scroll bar having different color

**Expected Behavior**

Should be transparent. See the vertical scroll bar on the screenshot.

**Environment**

JetBrains Rider 2022.3.2
Build #RD-223.8617.53, built on January 25, 2023
Licensed to Ilya Murashov
Subscription is active until May 28, 2023.
Runtime version: 17.0.5+1-b653.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2
.NET 7.0.0 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Registry:
    ide.intellij.laf.enable.animation=true
    ide.mac.bigsur.window.with.tabs.enabled=false
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    platform.projectModel.workspace.model.file.index=false
    ide.new.project.model.index.case.sensitivity=true
    vcs.empty.toolwindow.show=false
    database.show.search.tab=false
    ide.workspace.model.rbs.as.tree=false
    indexing.enable.entity.provider.based.indexing=false
    rdclient.asyncActions=false
    eslint.additional.file.extensions=svelte

Non-Bundled Plugins:
    com.markskelton.one-dark-theme (5.7.3)
    fr.socolin.application-insights-debug-log-viewer (1.7.3)
    idea.plugin.protoeditor (223.8214.6)
    com.werfad (1.0.0)
    IdeaVIM (2.1.0)
    com.github.copilot (1.2.2.2371)
    com.microsoft.vso.idea (1.162.1)
    zielu.gittoolbox (500.0.2+213)
    io.github.mishkun.ideavimsneak (1.2.0)
    com.intellij.resharper.azure (3.50.0.1546-2022.3)

**Screenshots**

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/14250177/217562613-63063804-f341-4adc-8d95-0c38fc228e48.png">

**Comment by iamim** [comment]
This issue is still present on Rider 2023.1 EAP with 5.7.4 version of the plugin.

**Comment by Unthrottled** [comment]
@iamim these changes were in the editor scheme, choose the `restore default` option if you made any changes to the color scheme because any new changes will not be picked up if you did.

https://www.jetbrains.com/help/idea/settings-colors-and-fonts.html

**Comment by iamim** [comment]
Hm, something happened and now the theme is not available in the dropdown. I assume it's a problem with the EAP build, but still :/
<img width="969" alt="image" src="https://user-images.githubusercontent.com/14250177/225026510-af4f7d8d-854b-4cbc-b4bd-c194e39f6f03.png">

**Comment by Unthrottled** [comment]
Does it show up after restarting the IDE?

**Comment by Unthrottled** [comment]
Might be related to https://github.com/one-dark/jetbrains-one-dark-theme/issues/262

**Comment by iamim** [comment]
> Does it show up after restarting the IDE?
No, restarts don't help. Neither does reinstallation of the plugin.

**Comment by Unthrottled** [comment]
https://youtrack.jetbrains.com/issue/RIDER-90774/Plugin-themes-are-not-displayed-in-list-of-themes

**Comment by iamim** [comment]
It was solved in yesterday's EAP release :)
