### ISSUE TITLE
The javaDocs

### ISSUE THREAD

**Issue by MitchellFlint** [one-dark/jetbrains-one-dark-theme#299]
These gray javaDocs are just ugly, and it makes something that should increase readability by a lot difficult to read, it's super irritating. Everything else about this theme looks perfect. Please fix

**Comment by Unthrottled** [comment]
You have the ability to customize the look of the color scheme to fit your preferences. Just go to `Settings` -> `Editor` -> `Color Scheme` -> `Java`  & adjust to your liking. Thanks.

<img width="1094" alt="Screenshot 2023-03-12 at 4 58 16 PM" src="https://user-images.githubusercontent.com/15972415/224576187-af9b9895-45f4-44f5-984c-2b68ff2daf6d.png">
