### ISSUE TITLE
WebStorm 2023.2 EAP support 

### ISSUE THREAD

**Issue by niklv** [one-dark/jetbrains-one-dark-theme#304]
![изображение](https://github.com/one-dark/jetbrains-one-dark-theme/assets/3831943/83dd836a-9b3d-45cd-954c-988d69b11a42)

**Comment by Unthrottled** [comment]
I might have some time this weekend to make it work for the new build. Thanks!

**Comment by surgicalcoder** [comment]
@Unthrottled Sorry to bug you, any update on this? I'm getting widthrawl symptoms from having to use a different theme in the Rider EAP
