### ISSUE TITLE
Too light panel header

### ISSUE THREAD

**Issue by widersky** [one-dark/jetbrains-one-dark-theme#306]
**Describe the bug**
I think those panel headers (look at the attached screenshot below) are too bright comparing to the rest of the interface elements in the case of the New UI.

**To Reproduce**
1. Just open a window :)

**Expected Behavior**
I think it should have the same background color as titlebar or files list.

**Environment**
IntelliJ IDEA 2023.1.2 (Ultimate Edition)
Build #IU-231.9011.34, built on May 16, 2023
Licensed to Adrian Widerski
Subscription is active until June 13, 2023.
Runtime version: 17.0.6+10-b829.9 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 8
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.intellij.apacheConfig (231.9011.41)
    com.github.copilot (1.2.8.2631)
    com.markskelton.one-dark-theme (5.7.4)
    org.tbm98.flutter-riverpod-snippets (2.231.1)
    lermitage.intellij.extra.icons (2023.2.5-231)
    Dart (231.9065)
    com.jetbrains.plugins.jade (231.8109.91)
    com.jetbrains.php (231.9011.38)
    ru.adelf.idea.dotenv (2023.1)
    io.flutter (74.0.4)
    zielu.gittoolbox (500.0.9+213)

Kotlin: 231-1.8.21-IJ9011.34

**Screenshots**
![image](https://github.com/one-dark/jetbrains-one-dark-theme/assets/45122321/7bf1df37-49d7-4e01-900b-b4b73887de74)

**Comment by Unthrottled** [comment]
Thank you for taking the time to submit this issue.

This is a pre-existing feature of the theme, you can see it in the legacy UI as well

![header example](https://raw.githubusercontent.com/one-dark/jetbrains-one-dark-theme/master/docs/screenshots/default.png)

Feel free to make a fork of this repository and adjust it to your liking. However, I will not be making changes to the headers. Please see the [development](https://one-dark.gitbook.io/jetbrains/contributing/development) for how to make changes for yourself. Thanks!
