### ISSUE TITLE
Editor area shows white

### ISSUE THREAD

**Issue by hongbo-miao** [one-dark/jetbrains-one-dark-theme#313]
I recently switched to Light theme, and then switch back to One Dark Theme. The editor area shows white.
I tried to reinstall the One Dark Theme, restart the editor. None of them works. 😔
BTW, thanks for the awesome theme! 😃

**To Reproduce**

1. Switch to Light Theme
2. Switch back to One Dark Theme

And One Dark Theme has four:
- One Dark
- One Dark Italic
- One Dark Vivid
- One Dark Vivid Italic

If I repeat previous step, it happens to each one individually. Now only One Dark left still shows black... I don't want to reproduce again to make this white too... 🥲

**Expected Behavior**

Expect it shows black.

**Environment**

```
IntelliJ IDEA 2023.2.2 (Ultimate Edition)
Build #IU-232.9921.47, built on September 12, 2023
Licensed to Hongbo Miao
Runtime version: 17.0.8+7-b1000.22 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 32000M
Cores: 10
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.minimap.enabled=true
    scala.erase.compiler.process.jdk.once=false

Non-Bundled Plugins:
    github.cweijan.test-theme (1.6)
    com.jetbrains.plugins.ini4idea (232.9921.55)
    wang.zhanwei.clangformat (1.4.0-RELEASE)
    org.rust.lang (0.4.201.5424-232)
    uk.co.hadoopathome.intellij.avro.intellijavroviewer (3.1.0)
    jp.roundrop.sqlformatter (0.1)
    com.eversql.plugins.jetbrains (1.3.1)
    com.intellij.ideolog (222.1.0.0)
    org.jetbrains.plugins.go-template (232.9921.62)
    com.intellij.plugins.macoskeymap (232.6095.10)
    lermitage.intellij.extratci (1.27.0)
    org.intellij.plugins.hcl (232.8660.88)
    com.andrey4623.rainbowcsv (2.0.2)
    me.lensvol.blackconnect (0.6.1)
    ir.msdehghan.plugins.ansible (0.92)
    org.jetbrains.plugins.ruby (232.9921.47)
    org.zalando.intellij.swagger (1.2.0)
    com.markskelton.one-dark-theme (5.8.0)
    com.intellij.plugins.watcher (232.8660.88)
    uk.co.ben-gibson.remote.repository.mapper (4.3.6)
    com.intellij.kubernetes (232.9921.28)
    com.intellij.grazie.pro (0.3.250)
    net.sf.opk.avro-schema-support (213.5.2)
    com.sourcegraph.jetbrains (3.0.9)
    org.jetbrains.plugins.go (232.9921.28)
    net.sjrx.intellij.plugins.systemdunitfiles (223.230322.126)
    name.kropp.intellij.makefile (232.8660.88)
    mobi.hsz.idea.gitignore (4.5.1)
    google-java-format (1.17.0.0)
    com.ypwang.plugin.go-linter (1.6.6)
    me.serce.solidity (2.4.2)
    ImportCost (1.4.232)
    com.intellij.lang.jsgraphql (4.0.2)
    com.jetbrains.php (232.9921.55)
    com.mallowigi (93.1.0)
    zielu.gittoolbox (500.0.18+222)
    org.intellij.scala (2023.2.23)
    org.sylfra.idea.plugins.linessorter (1.0.1)
    wallaby.js (1.0.274)
    Pythonid (232.9921.47)
    ru.meanmail.plugin.requirements (2022.4.1)
    aws.toolkit (1.79-232)
    izhangzhihao.rainbow.brackets (2023.3.4)
    ru.adelf.idea.dotenv (2023.2)
    codiumai.codiumai (0.6.07)
    com.dropbox.plugins.mypy_plugin (0.3.2)
    org.reloadium (1.2.1)
    com.intellij.bigdatatools.core (232.9921.47)
    com.intellij.bigdatatools.binary.files (232.8660.206)
    com.intellij.bigdatatools.rfs (232.9921.47)
    com.intellij.bigdatatools.metastore.core (232.9921.47)
    com.intellij.bigdatatools.spark (232.9559.62)

Kotlin: 232-1.9.0-IJ9921.47
```

**Screenshots**

![image](https://github.com/one-dark/jetbrains-one-dark-theme/assets/3375461/7de0016f-d58e-41b2-86ca-5b0cfc058e92)

**Comment by chakibkh** [comment]
Hi, i had the same issue. to resolve it: Both Appearance & Behavion > Appearance AND Editor > Color Scheme should be set to One Dark ... That worked for me.

**Comment by hongbo-miao** [comment]
Thanks! @chakibkh ! After updating

- Appearance & Behavior -> Appearance -> Theme
- Appearance & Behavior -> Editor -> Color Schema -> Schema

Now it works well 😃

I will leave this ticket open, as I found it does not happen to other dark themes.

**Comment by binbjz** [comment]
This is not a bug,  it is just that the default "Color Scheme" has been updated to "Classic Light".
We can manually restore the original default value.
1.Settings -> Appearance & Behavior -> Appearance -> Theme -> One Dark Vivid Itatic
2.Settings -> Editor -> Color Scheme -> Scheme -> One Dark Vivid Itatic

**Comment by hongbo-miao** [comment]
If first time user can set theme can work correctly.
Users would expect the second time selecting theme should like first time.
Right now first time and second time experience are not consistent.
And this only happens to this dark theme.

**Comment by Sinansi** [comment]
Today I installed version 5.9.0 and I confirm One Dark is showing white editor area, meanwhile everything else remains dark. People installing this plugin assume it is all dark screen, so please do not set the default settings to Classic Light. I thought it is bugged and I reinstalled it.

**Comment by adampatterson** [comment]
I was blinded after I updated 😂

I guess I will head into the settings then!

**Comment by Ggd07** [comment]
Thanks for destroying my eyes with this update. Real nice.
