### ISSUE TITLE
One Dark Vivid broken after latest update

### ISSUE THREAD

**Issue by blaenk** [one-dark/jetbrains-one-dark-theme#317]
Thank you so much for working on this theme!

**Describe the bug**

After upgrading to the latest version 5.9.0, the specific theme "One Dark Vivid" appears to be broken. The rest seem fine.

**To Reproduce**

1. Install 5.9.0
2. Switch to "One Dark Vivid"

**Expected Behavior**

**Environment**

> Build #IU-232.10072.27, built on October 10, 2023
>
> Runtime version: 17.0.8.1+7-b1000.32 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Screenshots**

![image](https://github.com/one-dark/jetbrains-one-dark-theme/assets/84680/4b4ae8a4-235e-436a-a63d-6fb5272d5b17)

**Comment by binbjz** [comment]
This is not a bug,  it is just that the default "Color Scheme" has been updated to "Classic Light".
We can manually restore the original default value.
1.Settings -> Appearance & Behavior -> Appearance -> Theme -> One Dark Vivid Itatic
2.Settings -> Editor -> Color Scheme -> Scheme -> One Dark Vivid Itatic

**Comment by blaenk** [comment]
Thank you! The second point fixed it.

Note that for some reason, it worked with all of the other One Dark themes, as mentioned in my comment. I originally mentioned "One Dark Vivid" as being the broken one, but you talked about "One Dark Vivid Italic".

I don't know if it's noteworthy that for some reason the other One Dark variants, such as "One Dark Vivid Italic", worked perfectly fine without any changes.

That said, thanks again! I'll go ahead and close it then if it's indeed not a bug (though it's curious why the other variants were not affected).
