### ISSUE TITLE
There's an issue with one dark theme on my Pycharm.

### ISSUE THREAD

**Issue by MysterrEverything** [one-dark/jetbrains-one-dark-theme#320]
Everything except for the code editor is in the one dark theme. the code editor is in default light theme which is harder to look at while also looking at the console, toolbar etc. Please help.

**Comment by iZhenius** [comment]
I've noticed the same issue with One Dark Vivid (IntelliJ IDEA 2023.2.4 with new UI enabled).
@MysterrEverything please, try to change 'Scheme' in Editor - Color Scheme - Scheme. It helped me.

**Comment by manusanchev** [comment]
Related with #313
