### ISSUE TITLE
PHPStorm 2023.3 breaks One Dark theme, color scheme has turned white

### ISSUE THREAD

**Issue by ArjunKishore** [one-dark/jetbrains-one-dark-theme#323]
Recently updated to PHPStorm 2023.3 after its release, the color scheme has changed to white background. I have tried reinstalling couple of time. Invalidated caches and built cache. 
![Bug](https://github.com/one-dark/jetbrains-one-dark-theme/assets/366087/7493b9b3-1362-459a-84eb-0025ceabe6e1)

**Comment by manusanchev** [comment]
same issue here, I don't think it's related to the editor version, it's more related to the plugin itself. I use webstorm version 2023.2.5 and it also happens to me. Related with #313 and can confirm https://github.com/one-dark/jetbrains-one-dark-theme/issues/313#issuecomment-1741198761 works

**Comment by kossa** [comment]
Make sure this option is well set

<img width="1105" alt="image" src="https://github.com/one-dark/jetbrains-one-dark-theme/assets/1175584/5d020b7b-2a4a-4c6c-81c2-1199bed9063c">

<img width="841" alt="image" src="https://github.com/one-dark/jetbrains-one-dark-theme/assets/1175584/8340fa4b-739d-4796-8966-2d88385023c5">

**Comment by ArjunKishore** [comment]
Colour scheme wasn't selected @kossa solution resolved the issue. Cheers
