### ISSUE TITLE
Not compatible with the latest intellij version

### ISSUE THREAD

**Issue by movink** [one-dark/jetbrains-one-dark-theme#329]
Plugin is not compatible with the latest intellij version preventing me updating the intellij.

**Comment by sn0ot** [comment]
![GOLAND_theme_error](https://github.com/one-dark/jetbrains-one-dark-theme/assets/63214302/537238d4-97f0-4556-a375-f3e24c7a4747)

**Comment by zhubeilife** [comment]
Same issue, can we have the latest build? Thanks!

**Comment by mskelton** [comment]
Just released a new version that should work with the latest.

**Comment by gynekolog** [comment]
@mskelton Hi, the version 5.10.0 is not available in the jetbrains store. Did someone miss a publishing step or does it just take a while?

**Comment by mskelton** [comment]
@gynekolog There were some publish issues in GitHub actions, so I manually uploaded the version this morning until I can resolve the build issues.
