### ISSUE TITLE
One Dark Problem - White background

### ISSUE THREAD

**Issue by jankowski-app** [one-dark/jetbrains-one-dark-theme#331]
Hello, I have PhpStorm 2023.3.3 and today I updated the One Dark plugin to the new version 5.10.0 and there
is a problem with the background color on the One Dark standard version - the background is white, on
other Italic or Vivid etc. versions, it is ok.

It should contain:
* OS (Windows, Linux, Mac)
 macOS 14.3.1 (23D60) 
* IntelliJ Product + version (IDEA, RubyMine...)
 PhpStorm 2023.3.3 
* Plugin version 
*One Dark 5.10.0 

**Screenshots**
![Zrzut ekranu 2024-02-10 o 00 31 12](https://github.com/one-dark/jetbrains-one-dark-theme/assets/42405604/37f55dff-f67a-4cd3-8f53-da3ef409ec84)
![Zrzut ekranu 2024-02-10 o 00 32 05](https://github.com/one-dark/jetbrains-one-dark-theme/assets/42405604/a92a5276-47a4-488a-8127-43786eaf2387)

**Comment by mskelton** [comment]
@jankowski-app This is probably related to https://github.com/one-dark/jetbrains-one-dark-theme/issues/313#issuecomment-1763564112

Can you check the following settings to make sure they are both set to One Dark?

1.Settings -> Appearance & Behavior -> Appearance -> Theme -> One Dark
2.Settings -> Editor -> Color Scheme -> Scheme -> One Dark

**Comment by jankowski-app** [comment]
Ok, thank you, it helped, the colors are correct now. I didn't know it could be set separately ;)
