### ISSUE TITLE
One Dark Theme update broke background color and variable colors

### ISSUE THREAD

**Issue by selectblinds-ethanh** [one-dark/jetbrains-one-dark-theme#332]
When the plugin theme updated, my background is now white and the linting for variables are also plain black text. For some reason the IDEA settings (gear wheel) > Theme > "One Dark" would not change it back. I had to go to Settings > Editor > Color Scheme > General and change the 'Scheme' to 'One Dark', then everything reverted back to normal ('One Dark' black background and colored variables).

**Comment by Scalahansolo** [comment]
Even down grading to 5.9 still has this issue. Very odd.

**Comment by selectblinds-ethanh** [comment]
Sorry for the duplicate: 
Issue discussed here: https://github.com/one-dark/jetbrains-one-dark-theme/issues/318
Solution found here: https://github.com/one-dark/jetbrains-one-dark-theme/issues/313#issuecomment-1741198761
Closing this duplicate out.
