### ISSUE TITLE
Plugin 'One Dark Theme' is not compatible with WS-242.10180.31

### ISSUE THREAD

**Issue by solidados** [one-dark/jetbrains-one-dark-theme#337]
### **Describe the bug**
  - [ ] Plugin 'One Dark Theme' (version '5.10.0') is not compatible with the current version of the IDE, because it requires build 241.* or older but the current build is WS-242.10180.31

Please release plugin versions that are compatible with 2024.2

### **Environment**
WebStorm 2024.2 EAP
Build #WS-242.10180.31, built on May 16, 2024
Licensed to WebStorm EAP user: Pavel Konyakhin
Expiration date: June 15, 2024
Runtime version: 21.0.3+13-b446.1 x86_64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.7.4
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 1024M
Cores: 4
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.jetbrains.space (242.10180.28)
  com.webfont.ideaplugin (3.0)
  github.cweijan.test-theme (1.6)
  ru.adelf.idea.dotenv (2024.2)
  org.igu.plugins.bettercomments (1.0)
  com.intellij.grazie.pro (0.3.306)
  org.intellij.prisma (242.10180.28)
  jones.restarteslintaction.restart-eslint-action (0.0.1)
  mobi.hsz.idea.gitignore (4.5.3)

### **Screenshots**

<img width="368" alt="Screen Shot 2024-05-20 at 12 21 44" src="https://github.com/one-dark/jetbrains-one-dark-theme/assets/81189948/fe239d37-28fc-4c51-9f93-560bf703a302">

**Comment by mskelton** [comment]
Fixed in the latest release
