### ISSUE TITLE
The coding editor tab has light theme applied instead of dark

### ISSUE THREAD

**Issue by hadalin** [one-dark/jetbrains-one-dark-theme#340]
**Describe the bug**
The coding editor tab has light theme applied instead of dark (see screenshot).

**To Reproduce**
1. Install One Dark Theme, version `5.11.0`
1. Restart IDE (Android Studio)

**Expected Behavior**
The coding editor should have a dark theme. One Dark Vivid works.

**Environment**
- MacOS Sonoma 14.5
- Android Studio Jellyfish | 2023.3.1 Patch 1
- Plugin version: `5.11.0`

**Screenshots**
<img width="472" alt="Screenshot 2024-05-22 at 16 16 03" src="https://github.com/one-dark/jetbrains-one-dark-theme/assets/1746370/ec30d036-ebd3-4260-a102-eac9227f4efd">

**Comment by ToothyDev** [comment]
Can reproduce, base theme is light mode, the 3 variations (Vivid, Italic, Vivid Italic) work as intended

**Comment by Trifase** [comment]
Only Vivid works for me. 
One Dark, Italic and Vivid Italic have all white background for me.

**Comment by mskelton** [comment]
@hadalin This is a common issue with IntelliJ when themes update. If you go into Editor -> Color Scheme in the preferences and ensure that One Dark is selected, that should fix it.
