### ISSUE TITLE
Latest release does not contain non-italic color scheme file

### ISSUE THREAD

**Issue by ihigg** [one-dark/jetbrains-one-dark-theme#37]
The one_dark.xml file is missing from the latest release. Applying the theme defaults the editor color scheme to darcula.

**Comment by mskelton** [comment]
Fixed in [v2.4.1](https://github.com/markypython/jetbrains-one-dark-theme/releases/tag/v2.4.1).  Apologies for the mistake!

**Comment by mskelton** [comment]
@allcontributors[bot] add @zakh508 to bugs

**Comment by mskelton** [comment]
@zakh508 If you haven't manually installed v2.4.1, the plugin was just approved by JetBrains and you can update though the plugin marketplace.
