### ISSUE TITLE
Italic color scheme does not rollback default font

### ISSUE THREAD

**Issue by TazmanOne** [one-dark/jetbrains-one-dark-theme#38]
Hi, I looked at this plugin and it interested me.
I tried to switch to different styles (Italic)
After using several days, I decided to return to the standard view and remove this plugin.
Unfortunately, after removing the plugin, I still have Italic fonts.
Can you fix this behavior? I would like to see the correct font display after removing this plugin.
I attach a screenshot.
![image](https://user-images.githubusercontent.com/13584167/57176863-d6c5e300-6e76-11e9-8730-6a3875a60393.png)

**Comment by mskelton** [comment]
To my knowledge, the italics in those popups are part of the IDE itself, not this theme.  I started a fresh instance of IntelilJ that doesn't have this plugin installed and appeared the exact same.  The italics that the theme sets are for scopes such as keywords, annotations (which look non-italicized in your screenshot), etc.

**Comment by mskelton** [comment]
Closing as not an issue.
