### ISSUE TITLE
Support 2019.1

### ISSUE THREAD

**Issue by dacoto** [one-dark/jetbrains-one-dark-theme#4]
Support 2019.1

![image](https://user-images.githubusercontent.com/16915053/55167740-d77da200-5171-11e9-8c34-0a5e1f1004cf.png)

**Comment by dacoto** [comment]
When do you think the new version will be ready?

**Comment by mskelton** [comment]
@dacoto I got the Gradle config updated this morning, but I will need to do some testing to make sure there isn't anything else that needs to get updated.  I will hopefully have it done by the end of day Saturday.

**Comment by dacoto** [comment]
@markypython Thank you very much, and very good work with this topic, congratulations.

**Comment by mskelton** [comment]
@dacoto I got the plugin updated and it is pending approval from JetBrains.  You can track it yourself for when they approve it on the [plugin site](https://plugins.jetbrains.com/plugin/11938-one-dark-theme).  I will post to this issue when it is published and @ mention you.

Thanks for opening this issue!

**Comment by dacoto** [comment]
@markypython Great, when do you think it will be approved?

**Comment by mskelton** [comment]
@dacoto Previous versions have usually taken about a day, but it might be a bit more since we are coming into the weekend.

**Comment by mskelton** [comment]
@dacoto I have done a bunch of work on this plugin and it is now automatically publishing builds when tags are committed to the repo.  In addition to publishing to the marketplace, I also added the built JAR file to the GitHub releases.

If you would like to get the new version sooner, go ahead and download it from the [latest release page](https://github.com/markypython/jetbrains-one-dark-theme/releases/tag/v1.2.3).

**Comment by dacoto** [comment]
It is already updated, thank you very much =)

**Comment by mskelton** [comment]
@dacoto Yeah, I just got the email this morning that the plugin update was approved.  Sorry it took so long for the update!
