### ISSUE TITLE
PHP variables color

### ISSUE THREAD

**Issue by dacoto** [one-dark/jetbrains-one-dark-theme#54]
**Describe the bug**
Default colors in PHP variables

**Expected behavior**
Previously it had the correct color, but since version **v1.8.0** #84a77d6 it has been lost and it no longer loads the same colors.
He had not modified the colors, at all times he had them by default.

**Screenshots**
Now (v2.10.0):
![image](https://user-images.githubusercontent.com/16915053/57611322-e4642280-7572-11e9-8391-deb348b48df9.png)
Before (v2.4.1):
![image](https://user-images.githubusercontent.com/16915053/57611775-dcf14900-7573-11e9-83d3-2b0258986548.png)

**Comment by mskelton** [comment]
The v2.10.0 screenshot is correct.  Local variables should be colored white, keywords should be colored purple.  Below is a list showing some of the main scopes that apply to each color:

- **chalky**: classes, interfaces, types
- **coral**: instance variables, object keys
- **dark**: comments
- **error**: bad characters or references
- **fountainBlue**: regex
- **green**: strings
- **lightWhite**: default text color
- **malibu**: function definition and calls
- **purple**: keywords
- **whiskey**: function parameters, numbers, constants

I have been working through each IDE updating syntax highlighting to be consistent.  v2.9.0 was the finalization of that effort and future updates will not make drastic changes.
