### ISSUE TITLE
Optimization of file colors

### ISSUE THREAD

**Issue by sveneick** [one-dark/jetbrains-one-dark-theme#55]
First of all thanks for the great theme. Personally, the file colors are not easy to recognize. Can you still optimize that? 
<img width="1362" alt="screenshot_xnpem" src="https://user-images.githubusercontent.com/4112464/57673802-91937500-761d-11e9-9574-be7893b69f0e.png">

**Comment by mskelton** [comment]
Thanks for opening this issue.  I personally don't use file colors in IntelliJ, but when I setup the theme I tried to not make the file colors overly colorful as that seemed to make it hard to read and see the structure.

Do you have some suggestions for hex values for the different colors?

**Comment by sveneick** [comment]
Thank you for your answer. My suggestion is:

Blue = #1e264b
Green = #334e1f
Orange = #562b22
Rose = #50202b
Violet = #4b1e4b
Brown = #563b22

**Comment by mskelton** [comment]
I tried those out, but they seem a bit too vibrant.  What are your thoughts on potentially dropping the opacity or brightness?  For example `#563b2270` for blue (the color you suggested with 70% opacity).

**Comment by sveneick** [comment]
Hi Mark,

Let me give you my application scenario, why a good distinction of colors is important to me. I work a lot in the Shopware theme programming. Here you usually move in 3 theme folders. The files you have open usually have the same name, but in different folders. The folders always have 3 different colors with me, so that I can distinguish the files, which I have open, with the Tab colors well.

You have a very good feeling for colors. That's why I leave the decision to you. But it is important that the chosen colors make sense, so that you can distinguish them. At the moment it's hard, as you can see on my screenshot.

<img width="1116" alt="screenshot_rxzv9" src="https://user-images.githubusercontent.com/4112464/57829049-01d10080-77ae-11e9-8675-e7d5d7b7082d.png">

**Comment by mskelton** [comment]
@all-contributors add @eickit to design

**Comment by mskelton** [comment]
@eickit I have updated the colors and released [v2.10.1](https://github.com/markypython/jetbrains-one-dark-theme/releases/tag/v2.10.1).  I decided to go with `cc` as the opacity on the colors you suggested.

**Comment by sveneick** [comment]
Perfect, Thank You!
