### ISSUE TITLE
Theme not completely working with Android studio 3.4

### ISSUE THREAD

**Issue by marcocadei** [one-dark/jetbrains-one-dark-theme#58]
I want to use this theme for Android Studio 3.4. 
I followed the instructions for the v1 legacy version of the theme.
The color scheme is correctly updated but everything else stay like in the normal Dracula theme.
How can i obtain a complete update on each part of the interface like what you show on [this screen](https://raw.githubusercontent.com/markypython/jetbrains-one-dark-theme/master/docs/screenshots/java.png)?

**Comment by mskelton** [comment]
@MarcoCadei Unfortunately, Android Studio is still using IntelliJ version 2018 which does not support the new UI theme customizations available in IntelliJ 2019.1.  When the next major Android Studio version is released (likely in about a year), then it will support the UI theme customizations.
