### ISSUE TITLE
Please make it Intellij 2019.2 compatible

### ISSUE THREAD

**Issue by drkn** [one-dark/jetbrains-one-dark-theme#59]
Please make it compatible with current EAP 2019.2 version. Tried to just change version in descriptor, but some colors acted weird. Buttons overlay color hide icons:

![image](https://user-images.githubusercontent.com/140258/58799931-e0be3b80-8606-11e9-9282-0aaa214511c5.png)

**Comment by mskelton** [comment]
There are some issues with IntelliJ 2019.2 that affect this theme.  Until they are resolved, I won't be publishing the update for 2019.2.

Here is one of the main issues with the new version of IntelliJ: https://youtrack.jetbrains.com/issue/IDEA-215462

**Comment by mskelton** [comment]
[v2.11.0](https://github.com/markypython/jetbrains-one-dark-theme/releases/tag/v2.11.0) is now compatible with IntelliJ 2019.2.  There is one issue I noticed with the header for the plugin settings page looking strange, and I have opened a separate issue to resolve that.
