### ISSUE TITLE
Add screenshots to plugin page

### ISSUE THREAD

**Issue by GauthierPLM** [one-dark/jetbrains-one-dark-theme#6]
Screenshots always make thing more clear and appealing. Even if this theme is well known, I think it would be a good addition to the plugin page and would give users a good preview of the theme.

**Comment by mskelton** [comment]
@GauthierPLM Thanks for opening this issue.  I will work to add screenshots as soon as possible.

**Comment by mskelton** [comment]
Screenshots have been added to the readme and the plugin page.

**Comment by mskelton** [comment]
@allcontributors[bot] add @GauthierPLM to ideas
