### ISSUE TITLE
Configurable Project View Tree Padding

### ISSUE THREAD

**Issue by Nikki1993** [one-dark/jetbrains-one-dark-theme#60]
The theme seems to override default padding/not respecting the font size in the appearance tab. Here is Dracula default theme
![image](https://user-images.githubusercontent.com/1446529/58945537-b5fdef80-878c-11e9-8c25-092e4045df68.png)
and here is the Dark theme 
![image](https://user-images.githubusercontent.com/1446529/58945435-84852400-878c-11e9-8f33-1a656797757a.png)

Would be nice to get back the original padding back as a configurable feature or at least respect the default

**Comment by mskelton** [comment]
Which setting are you referring to for changing the font size?

**Comment by mskelton** [comment]
@Nikki1993 Which setting are you referring to for changing the font size?

**Comment by Nikki1993** [comment]
Sorry, I was traveling by car for a few days, according to Webstorm docs, modifying this setting makes file tree size change, unless I misunderstood the docs wildly

![image](https://user-images.githubusercontent.com/1446529/59456648-7b94f200-8e1f-11e9-89fe-3fbf252cdab8.png)

However, material design theme ext for JetBrains made it as a configurable option, so perhaps similar could be done here?

**Comment by Nikki1993** [comment]
here are a few comments referring to similar findings https://stackoverflow.com/questions/17804838/how-to-change-line-space-in-project-window

**Comment by mskelton** [comment]
@Nikki1993 Even when I increase the font size, the padding still looks fine.  Can you send me a list of the plugins you have installed or try disabling them to see if they are potentially causing the issue?

I am not interested in making the tree view padding configurable as I would like to keep this plugin as simple as possible with just the UI and editor theme.  Additionally, having the tree view padding configurable would likely be a seldom used feature.  That isn't to say I don't want to help get to the bottom of this issue as I certainly do!

**Comment by Nikki1993** [comment]
I do fully understand and support the notion of a configless theme. 

Here are all the custom plugins I have installed,

![image](https://user-images.githubusercontent.com/1446529/59518541-7f338200-8ece-11e9-8d8c-9453264bc9fe.png)

I tried turning all off and only enabling the theme, the same effect as in screenshots above.
on a side note could this somehow be related that I am using a 4k display?

**Comment by mskelton** [comment]
The reason for making this theme configless is that it is based on a pre-existing color theme and there are almost no non-color settings this theme introduces.

I don't think it would be due to the display, as I too have a 4k monitor.  I'll have to investigate this further when I have a chance.

FYI, I will be on vacation for a week and won't be available to work on this improvement for at least 2 weeks.  I will try to get to it as soon as I can, but don't expect it to be fixed immediately.

**Comment by Nikki1993** [comment]
No worries, if/when you need additional details from me just let me know, otherwise happy vacay :)

**Comment by mskelton** [comment]
I tried a few more things, but I still can't reproduce the issue you are having.  I did take some screenshots and the spacing for the Darcula theme is much different than the screenshot you sent.

**Darcula**

![2019-06-23_08-06-55](https://user-images.githubusercontent.com/25914066/59976706-ebc51580-958d-11e9-8da1-5ccad7b9d05a.png)

**One dark**

![2019-06-23_08-07-07](https://user-images.githubusercontent.com/25914066/59976707-ecf64280-958d-11e9-9a45-653c6b032f7d.png)

**Comment by Nikki1993** [comment]
which JDK version are you running? I am currently stuck using bundled with webstorm version JDK 8

**Comment by mskelton** [comment]
I'm using the default JDK for webstorm.

**Comment by Nikki1993** [comment]
do you use 2x scaling for your 4k display? cause I am running it at 1x?

**Comment by mskelton** [comment]
Sorry for the delayed reply.  Do you know how I would go about checking the scaling?  I'm not a big hardware guy, so I don't know so much about that kind of thing 😄

**Comment by mskelton** [comment]
Another thing I would suggest that could help further debug this issue is to clone this repo, open it in IntelliJ, sync the Gradle project, and run the `runIde` run configuration.  That will start a fresh ide with nothing installed except for the plugin and then you can select the plugin theme from the plugin menu to see if it tree view padding acts like it does in your original screenshot.  That would help to rule out the possibility of it being related to the configuration of your ide.

**Comment by Nikki1993** [comment]
depends on what system you are running if you tell me I can provide instructions for running display at native 4k, I will clone the repo and have a look

**Comment by mskelton** [comment]
I run macOS Mojave.

**Comment by Nikki1993** [comment]
pretty easy, go to display settings, set it to scaled mode and select highest available resolution https://www.eizoglobal.com/support/compatibility/dpi_scaling_settings_mac_os_x/index.html

**Comment by mskelton** [comment]
Oh, I didn't realize that was what you were referring to when you said 1x or 2x 😄

I run my MacBook on the highest res possible and my 4k monitor right in the middle.  I'll try switching my other monitor to the highest res to see what happens, but it won't be until Monday since that monitor is the one I use at work.

**Comment by Nikki1993** [comment]
cant test, both jdk 11 and 12 give me when doing ideRun 
 https://gist.github.com/Nikki1993/1aab4673eb0dc44b81b6c573605648fd

**Comment by mskelton** [comment]
Sorry, I forgot to mention the build steps that you will need to run.  You will need to run `python3 ./scripts/build.py` to build the theme files before running the IDE.  I have a development wiki doc if you need further explanation.

https://github.com/markypython/jetbrains-one-dark-theme/wiki/Development

**Comment by Nikki1993** [comment]
all works now, but same padding difference for me, unfortunately,

**Comment by mskelton** [comment]
Okay, thanks for doing that as that helps to rule out other plugins/configuration as a potential issue.  Like I said, I'll check on Monday with my 4k monitor to see how it looks scaled down.

**Comment by mskelton** [comment]
Additionally, you could try removing [this line](https://github.com/markypython/jetbrains-one-dark-theme/blob/master/src/main/resources/themes/one_dark.theme.json#L324) from the theme file, rebuilding the files with the Python command I sent, and restarting the ide.  That would help discover if that setting is what is causing the issue.

**Comment by Nikki1993** [comment]
@markypython YES, success, removing rowHeight worked perfectly!

**Comment by mskelton** [comment]
Okay, so it is definitely related to that setting.  I wonder if this isn't a bug within IntelliJ, so I might open a bug once I am able to reproduce it.

**Comment by mskelton** [comment]
@Nikki1993 First of all, apologies for the delay in responding, I totally forgot about this early last week and then the holiday came around.  I did check this morning and I noticed no difference on my monitor regardless of the scale I set it to.

**Comment by Nikki1993** [comment]
no worries at all :) I am not sure what's up then, perhaps I am alone with this due to very specific setup, I guess I could always fork your repo and just remove the rowHeight :D

**Comment by mskelton** [comment]
@Nikki1993 I hate to make you do that.  Can you try installing the [dark purple](https://plugins.jetbrains.com/plugin/12100-dark-purple-theme) theme from JetBrains?  It also changes the [row height](https://github.com/OlyaB/DarkPurpleTheme/blob/master/src/DarkPurple.theme.json#L354) and I wonder if you will get the same result with that theme.  If you do, this is probably an IntelliJ bug for your specific system/IDE configuration that you could report to JetBrains.

**Comment by mskelton** [comment]
@Nikki1993 Were you able to try out the dark purple theme and see if it has the same issue?

**Comment by Nikki1993** [comment]
@markypython so sorry, I am so forgetful, but to answer your question, yes and it does have the same issue. Stock Dracula theme however does not.

**Comment by mskelton** [comment]
@Nikki1993 This must be a bug with IntelliJ then that occurs with your specific setup.  I'm going to close this issue as it is not a problem with this theme.  I would encourage you to [open an issue](https://youtrack.jetbrains.com/newIssue) on YouTrack and see if the folks at JetBrains can track down and fix the issue.
