### ISSUE TITLE
Enhance the background color of the selected area

### ISSUE THREAD

**Issue by cnfn** [one-dark/jetbrains-one-dark-theme#63]
**Describe the proposed feature**

The selected area background color is too light to find it...
Could you find what I have selected in the string `SpringBootApplication`?

![image](https://user-images.githubusercontent.com/1445517/59336308-e3204400-8d30-11e9-976e-187503536645.png)

My environment:
- Jetbrains IDEA: 2019.1
- Language: Java

**Comment by mskelton** [comment]
I can see the background you have selected, but this did encourage me to look at the color Atom is using for the selection background.  Their color is almost the same, but they don't highlight the current line when you have a selection which affects the color.  I will look into darkening the color to make it more apparent.

**Comment by cnfn** [comment]
Thank you very much~

I have tried to modify some background fields for this theme, but not work. May be I not found the special field for selection background.😂

**Comment by mskelton** [comment]
FYI, I will be on vacation for a week and won't be available to work on this improvement for at least 2 weeks.  I will try to get to it as soon as I can, but don't expect it to be fixed immediately.

**Comment by mskelton** [comment]
Fix committed and will be in the next release

**Comment by cnfn** [comment]
I know why not work for me when I try modify the theme. Because I directly modify the jar file, `~/Library/Application Support/IntelliJIdea2019.1/one-dark-theme/lib/one-dark-theme-2.11.0.jar`. But IDEA maybe cache it....

Thank you again~

**Comment by mskelton** [comment]
@allcontributors-bot add cnfn to design
