### ISSUE TITLE
Use selected color scheme in special areas

### ISSUE THREAD

**Issue by kalbert312** [one-dark/jetbrains-one-dark-theme#64]
**Describe the proposed feature**

I'm using One Dark with a modified Dracula color scheme for the code. I've noticed that in certain areas like breakpoint conditional, evaluate expression, datagrip table quick filter, the theme's default color scheme is used. Is it possible to use the selected color scheme in all places, or is it just limited to the editor?

**Comment by mskelton** [comment]
Can you provide some screenshots of the current behavior?

**Comment by kalbert312** [comment]
Ruby example in evaluate expression: 
![Screen Shot 2019-06-18 at 5 08 47 PM](https://user-images.githubusercontent.com/5498623/59720019-d0ec4d00-91eb-11e9-8dd3-5af33e684ff9.png)
TypeScript example in breakpoint condition:
![Screen Shot 2019-06-18 at 5 11 38 PM](https://user-images.githubusercontent.com/5498623/59720169-30e2f380-91ec-11e9-8642-b3fed6b2b2f9.png)

**Comment by mskelton** [comment]
@kalbert312 I would suggest opening [an issue](https://youtrack.jetbrains.com/newIssue) on YouTrack and see what the folks at JetBrains think as I don't think this is an issue with the theme but with how the IDE selects the color theme.

**Comment by mskelton** [comment]
Closing as this is likely an issue with IntelliJ itself rather than this theme.  @kalbert312 If you find this is an issue with this theme, comment on this issue and I will reopen it.
