### ISSUE TITLE
One Dark Italic: fix low contrast (light gray on yellow background)

### ISSUE THREAD

**Issue by cliffordp** [one-dark/jetbrains-one-dark-theme#65]
**Describe the bug**
Light gray text on yellow background is near impossible to read

**Expected behavior**
More contrast between text and bg colors

**Screenshots**
![image](https://user-images.githubusercontent.com/1812179/59880467-b5f81500-9372-11e9-846a-6232ae93ac12.png)

**Comment by mskelton** [comment]
Is this bug in PhpStorm?

**Comment by cliffordp** [comment]
Here's a screenshot from Default:
![image](https://user-images.githubusercontent.com/1812179/59979518-964d3080-95ae-11e9-9089-808ec54ec77d.png)

And a screenshot from Darcula:
![image](https://user-images.githubusercontent.com/1812179/59979522-a533e300-95ae-11e9-8d66-66b3d5dbe19b.png)

So... *maybe*

**Comment by mskelton** [comment]
Fixed in the next version

**Comment by mskelton** [comment]
@all-contributors add @cliffordp to bugs
