### ISSUE TITLE
Can't Install latest release from JetBrains plugins store

### ISSUE THREAD

**Issue by yazeedobaid** [one-dark/jetbrains-one-dark-theme#72]
Hi,
I'm trying to install the plugin from PhpStorm market place but it displays version 1.6 for me. I tried to in-validate PhpStorm cache and it still the same.

Please note that I was able to install the plugin (latest release 2.11) manually. 

Thanks

**Comment by mskelton** [comment]
@yazeedobaid What version of PhpStorm are you using?

**Comment by yazeedobaid** [comment]
@markypython I'm using PhpStorm 2019.1.3

**Comment by mskelton** [comment]
@yazeedobaid Can you provide some screenshots?  I tried installing it with version 2019.1.3 and it worked fine.

**Comment by yazeedobaid** [comment]
Hi again, the 1.6 version has the name "Atom One Dark theme". However, the latest release has the name "One Dark Theme" which is 2.* version.
![image](https://user-images.githubusercontent.com/26872001/61740325-0a8a1800-ad97-11e9-9f19-d78500ec9aaa.png)

I have installed the latest one "One Dark".

Thanks;
