### ISSUE TITLE
Please change the selection background color

### ISSUE THREAD

**Issue by sundongmin** [one-dark/jetbrains-one-dark-theme#73]
I like this theme very much, but there is a problem for me. 

On my monitor, the `Selection background` color is similar with `Identifier under caret` and `Identifier under caret (write)` color, see the figure
![20190725145402](https://user-images.githubusercontent.com/17910228/61852441-163b2300-aeec-11e9-9503-94c322290f40.png)
In this figure, the character `res` has alreay selected, but could not see.

There is another problem, if I select the comment, the line comment color is too light to see clearly.
![QQ截图20190725150440](https://user-images.githubusercontent.com/17910228/61853067-92823600-aeed-11e9-9fc4-328698d96e3e.png)

So, Please change the selection background color.

Thanks!

**Comment by mskelton** [comment]
@sundongmin Thanks for the feedback.  The selection color is pretty tricky to get correct based on how IntelliJ handles it, but I will play around with it a bit more and see what I can come up with.

**Comment by mskelton** [comment]
Related to #63

**Comment by mskelton** [comment]
@sundongmin After playing around with the colors a bit, I did make some small adjustments to the section and identifier under caret colors.  That said, IntelliJ is a bit limiting in what they let you do for those two which make it worse that VS Code for example which handles this all extremely well.

The fix for this will be in the next release.

**Comment by sundongmin** [comment]
Thank you very much.

And I expect it.

**Comment by mskelton** [comment]
@allcontributors add sundongmin to design

**Comment by mskelton** [comment]
Fixed in [v2.12.0](https://github.com/markypython/jetbrains-one-dark-theme/releases/tag/v2.12.0)
