### ISSUE TITLE
Colors in Go inherits Darcula

### ISSUE THREAD

**Issue by Defman21** [one-dark/jetbrains-one-dark-theme#74]
**Describe the bug**
For some reason, most of the tokens in Go are colorized with Darcula.

**Expected behavior**
Go should inherit from the One dark theme.

**Screenshots**
![image](https://user-images.githubusercontent.com/7100645/61933733-4556a080-af8f-11e9-8243-9f2a73b40f9f.png)

I fixed it myself by going to `Editor - Color Scheme - Go` and checking `Inherit values from: ... (Language Defaults)` for every token that doesn't inherit and its color isn't in the palette.

**Comment by mskelton** [comment]
@Defman21 Yikes!  I'll get to fixing this right away on Saturday.

**Comment by mskelton** [comment]
@allcontributors add defman21 to bugs

**Comment by mskelton** [comment]
@Defman21 I actually had a bit of time this morning, so I fixed and released a [patch](https://github.com/markypython/jetbrains-one-dark-theme/releases/tag/v2.11.3).  You can either download it manually, or wait for JetBrains to approve the plugin update and then install it that way.

Thanks for reporting this!

**Comment by Defman21** [comment]
Woah, that was fast. Thanks a lot! :)
