### ISSUE TITLE
Not working with Goland 2019.2

### ISSUE THREAD

**Issue by jonnylangefeld** [one-dark/jetbrains-one-dark-theme#77]
**Describe the bug**
The plugin is incompatible with the current GoLand version (2019.2)

**Screenshots**
![Screen Shot 2019-07-26 at 10 31 22 AM](https://user-images.githubusercontent.com/18717376/61969957-9915b980-af90-11e9-94b3-a4249217a124.png)

This is my favorite theme, I hope it is compatible with GoLand 2019.2 soon again!

**Comment by mskelton** [comment]
@jonnylangefeld I'm not sure why it isn't showing that there is an update for the theme as version [2.11.0](https://plugins.jetbrains.com/plugin/11938-one-dark-theme/update/63833) was release last month and is compatible with version 2019.1 — 2019.2.

Could you try uninstalling and reinstalling the theme?

**Comment by mskelton** [comment]
Also, be aware that version 2.11.0 had a bug with the Go syntax highlighting that I fixed this morning in PR #75.  I released version 2.11.3 but it is still pending approval from JetBrains.  You can download it manually on the [release page](https://github.com/markypython/jetbrains-one-dark-theme/releases/tag/v2.11.3) if you would like.

**Comment by jonnylangefeld** [comment]
Wow thanks for your quick reply and your quick fix this morning. Because true, once I uninstalled it and reinstalled it, I ran into the same issue as described in #74. But now I downloaded your release from this morning and everything is working fine again 🎉 
So next time, once JetBrains approved, it'll work via the marketplace again!
