### ISSUE TITLE
how to change selected color?

### ISSUE THREAD

**Issue by Lingouzi** [one-dark/jetbrains-one-dark-theme#82]
**Describe the proposed feature**

![image](https://user-images.githubusercontent.com/12908403/62351417-08168380-b538-11e9-8f33-feb06a1ee69f.png)
I want to change the background color here.But don't know how to modify.Or foreground
![image](https://user-images.githubusercontent.com/12908403/62351550-6a6f8400-b538-11e9-8386-e0ab60888648.png)

It doesn't look very obvious

**Comment by mskelton** [comment]
@tulongxCodes Just so I am clear, you are referring to the background color of the selected item in the autocomplete list right?

**Comment by Lingouzi** [comment]
@markypython yes

**Comment by mskelton** [comment]
@tulongxCodes What IntelliJ version and plugin version are you using?

**Comment by Lingouzi** [comment]
![image](https://user-images.githubusercontent.com/12908403/62611306-e5b9a700-b937-11e9-8c4f-4faede06a087.png)
![image](https://user-images.githubusercontent.com/12908403/62611381-08e45680-b938-11e9-9df8-d16bc8bf67ec.png)
![image](https://user-images.githubusercontent.com/12908403/62611409-17cb0900-b938-11e9-9f71-9743a8d2ce46.png)
@markypython

**Comment by mskelton** [comment]
@tulongxCodes I wasn't able to find a way and customize this, so I opened a YouTrack issue to try and get some help.  You can follow that issue [here](https://youtrack.jetbrains.com/issue/IDEA-220191).

**Comment by Lingouzi** [comment]
thks

**Comment by mskelton** [comment]
Fixed in [v3.1.0](https://github.com/one-dark/jetbrains-one-dark-theme/releases/tag/v3.1.0)

**Comment by mskelton** [comment]
@all-contributors add @tulongxCodes  to design
