### ISSUE TITLE
bad install on clion

### ISSUE THREAD

**Issue by smye** [one-dark/jetbrains-one-dark-theme#83]
**Fails to restart successfully after downloading plugin**
Downloaded from marketplace, told to restart. On restarting, it freezes at loading 
components. On force closing that, it loads up but this time freezes on loading modules. 

**Screenshots**
![one_dark](https://user-images.githubusercontent.com/17861005/62843609-ff9a1780-bcb2-11e9-865d-581e3f8e211c.PNG)

**Comment by smye** [comment]
Sorry about that.

Yes, the theme does work.

**Comment by mskelton** [comment]
Not a problem.  Glad there wasn't an issue!

**Comment by mskelton** [comment]
@smye Can I close this issue then?

**Comment by smye** [comment]
Yes
Sorry once again

**Comment by mskelton** [comment]
Don't apologize, I'm always happy to help 😀
