### ISSUE TITLE
Dosent work with Latest Android Studio 3.4.2 and InteliJ + Old Version in Repo

### ISSUE THREAD

**Issue by mustii82** [one-dark/jetbrains-one-dark-theme#84]
The Versions on the Repo are really old. The latest Builds here cant be imported into the IDEAS

**Comment by mskelton** [comment]
What versions show up in Android Studio?  Keep in mind that Android Studio is a major version behind IntelliJ so the editor style customizations that you see in the screenshots are not available in Android Studio.

**Comment by mustii82** [comment]
v1.8.2 is on the Market Place in AS, I downloaded your latest Builds and they dont work for me either in AS nor in InteliJ both latest versions

**Comment by mskelton** [comment]
Can you explain what you mean by "not working"?  Did you follow the steps in the [Installation Wiki doc](https://github.com/markypython/jetbrains-one-dark-theme/wiki/Installation) after installing the theme to enable it?

**Comment by mustii82** [comment]
Yes I did o. InteliJ its working quite well but I can't get it get working on AS

**Comment by mskelton** [comment]
Can you provide some screenshots showing where the behavior you are seeing differs from the docs?

**Comment by mustii82** [comment]
on AS just the Editor Scheme changes nothing more i loaded the version from the plugin store

**Comment by mskelton** [comment]
That is expected functionality.  Android Studio does not yet have the ability to customize the overall editor theme as that was new in IntelliJ 2019.1.  Until Android Studio updates the IDE core, the editor color scheme is all that will be able to be updated.

**Comment by mskelton** [comment]
For future reference, I added some of these details to the [Installation](https://github.com/markypython/jetbrains-one-dark-theme/wiki/Installation#legacy-v1-installation) Wiki doc.
