### ISSUE TITLE
Vivid Variant

### ISSUE THREAD

**Issue by jeffjohnson** [one-dark/jetbrains-one-dark-theme#85]
Would love to see the Vivid variant as that is my daily driver. I can create and do a pull request if necessary.

**Comment by mskelton** [comment]
@jeffjohnson Glad to hear about your interest.  I haven't gotten around to the vivid variant but I would love to get it added to the theme.  Here are the basic steps I would take to add the vivid variant.

- [x] Update the [plugin.xml](https://github.com/markypython/jetbrains-one-dark-theme/blob/master/src/main/resources/META-INF/plugin.xml#L11-L12) to include the `one_dark_vivid` and `one_dark_vivid_italic` json files.
- [x] Move [colors.yaml](https://github.com/markypython/jetbrains-one-dark-theme/blob/master/scripts/config/colors.yaml) to a subfolder so the path is `colors/normal.yaml`
- [x] Add the vivid.yaml color file to the `colors` folder
- [x] Update [build.py](https://github.com/markypython/jetbrains-one-dark-theme/blob/master/scripts/build.py) to allow a command line argument of `normal` or `vivid`.  Normal should output files `one_dark.theme.json` and `one_dark_italic.theme.json` and vivid should output `one_dark_vivid.theme.json` and `one_dark_vivid_italic.theme.json`.
- [x] Update [build.sh](https://github.com/markypython/jetbrains-one-dark-theme/blob/master/build.sh) to run the build.py script twice, first with the normal colors, second with the vivid colors.
- [x] Update the `build_json` function in [build.py](https://github.com/markypython/jetbrains-one-dark-theme/blob/master/scripts/build.py) to build all 3 json files (`one_dark_italic.theme.json`, `one_dark_vivid.theme.json`, and `one_dark_vivid_italic.theme.json`).

I think that is about everything.  Let me know if you have any questions.  Again, thanks for your interest in helping with this!

**Comment by mskelton** [comment]
@jeffjohnson Do you still plan on working on this or would you like me to take care of it?

**Comment by mskelton** [comment]
Fixed in version [3.0.0](https://github.com/one-dark/jetbrains-one-dark-theme/releases/tag/v3.0.0)

**Comment by jeffjohnson** [comment]
I apologize for not getting back to you on this.

I've had some family concerns that have kept me fairly busy.

I noticed last night that you had done the work. Thank you. Looking forward to using the theme.
R,
Jeff

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mskelton** [comment]
@jeffjohnson Not a problem.  I'm glad you expressed interest in this as it allowed me to prioritize adding the vivid theme.

**Comment by jeffjohnson** [comment]
Starting using it today, it's awesome. Thank you so much!!!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
