### ISSUE TITLE
Tab Height is not working with IntelliJ 2019.2.1

### ISSUE THREAD

**Issue by goxr3plus** [one-dark/jetbrains-one-dark-theme#87]
![image](https://user-images.githubusercontent.com/20374208/63763431-60d60380-c8cd-11e9-9688-c4d9fafb96d2.png)

Notice how the tabs are on the above image , i can't read the value of them anymore .

No matter how i change the Tab Height the tabs are broken like shown in the above image .

I don't know why it doesn't work anymore.

![image](https://user-images.githubusercontent.com/20374208/63763482-79461e00-c8cd-11e9-99c8-9764e8484ed3.png)

**Comment by goxr3plus** [comment]
@markypython

**Comment by mskelton** [comment]
@goxr3plus It appears that you are using the material theme extension.  I'm guessing the issue is because of that as the tab height works perfectly fine for me.  Can you try disabling the material theme extension and see if the issue persists?

**Comment by goxr3plus** [comment]
Yes you are right another people seem to have the same problem i have opened an issue there :)
