### ISSUE TITLE
One dark weird behavior in IntelliJ 2019.2

### ISSUE THREAD

**Issue by C1PR14N055** [one-dark/jetbrains-one-dark-theme#88]
Keywords are highlighted in other colors in IntelliJ 2019.2 compared to 2019.1. 
The theme does not look like one dark anymore, sometimes it breaks completely and doesnt look at all like one dark.

This issue appeared only after the update.

**Comment by mskelton** [comment]
Can you provide a screenshot please?

**Comment by mskelton** [comment]
Closing due to lack of response.
