### ISSUE TITLE
I want to know what kind of font in screenshots?

### ISSUE THREAD

**Issue by asnig** [one-dark/jetbrains-one-dark-theme#89]

**Comment by mskelton** [comment]
The font I'm using is called [Operator Mono ScreenSmart](https://www.typography.com/fonts/operator/styles/operatormonoscreensmart).

It is a paid font and is pretty pricy but here are some good alternatives:

- [Dank Mono](https://dank.sh)
- [Fira Code](https://github.com/tonsky/FiraCode)

**Comment by asnig** [comment]
Thank you!
