### ISSUE TITLE
normal and italic have different color ? 

### ISSUE THREAD

**Issue by xiaohp** [one-dark/jetbrains-one-dark-theme#91]
**Describe the bug**
In WebStorm, my js file use this two themes have  different color.

**Expected behavior**
According to the docs, it should have the same colors and effects with the only difference being the italic variant italicizes certain language constructs

version
macOS 10.13.6
One Dark plugin 2.13.0
WebStorm 2019.2.2

**Screenshots**

![image](https://user-images.githubusercontent.com/23056320/65012273-4978bc00-d949-11e9-8df2-75952c4708f8.png)
one-dark

![image](https://user-images.githubusercontent.com/23056320/65012295-62816d00-d949-11e9-80e8-75a4195c5cd6.png)
one-dark-italic

**Comment by mskelton** [comment]
What version of WebStorm and the One Dark plugin are you using?

**Comment by xiaohp** [comment]
> What version of WebStorm and the One Dark plugin are you using?

One Dark plugin 2.13.0
WebStorm 2019.2.2

**Comment by mskelton** [comment]
Can you paste a minimal but complete JS file that reproduces the issue?

**Comment by xiaohp** [comment]
> Can you paste a minimal but complete JS file that reproduces the issue?

Like this file https://github.com/xiaohp/webpack-demo/blob/master/src/index.js

**Comment by mskelton** [comment]
Hmm, that seems to work for me.  Could you uninstall and reinstall the plugin to see if that fixes it?

**Comment by xiaohp** [comment]
Sorry, it's my problem. 
I found a color config file in Webstorm system path. It import from https://github.com/yurtaev/idea-one-dark-theme in last year, and it also named one dark. I think it conflict with the theme. So delete this file and restart Webstorm, it have fixed.
![image](https://user-images.githubusercontent.com/23056320/65102976-4e984280-d9ff-11e9-8c86-6846418a08de.png)

**Comment by mskelton** [comment]
Cool, glad you got it figured out!
