### ISSUE TITLE
One Light theme variant

### ISSUE THREAD

**Issue by danilkhromov** [one-dark/jetbrains-one-dark-theme#95]
It would be nice to have light variant for this theme, based on the similair one from [Atom](https://github.com/atom/one-light-ui). I'm willing to help, but i never ever developed any themes for intellij or any other editor.

**Comment by mskelton** [comment]
@danilkhromov As I explained in #66, I don't want to add one light to this repo as it's name clearly indicates one dark.  That said, I'd be happy to help you setup one light based off of this project.  Feel free to email me at mdskelton99@gmail.com and we can talk further.

Here was my comment in the other issue:

> While I'm not opposed to the idea of having the light version of this theme, I think it is so different from this theme that it should be in a separate repository/IntelliJ plugin. Because this theme is just a color theme and doesn't have any other customizations or features, most of this repo would have to change.

cc: @cata0309

**Comment by napsterv** [comment]
@danilkhromov Hi, I am curious whether you were able to setup a light theme variant?

**Comment by danilkhromov** [comment]
@napsterv unfortunately no, i started to play around with it but then i had little to no free time to continue with it. And later i lost interest in doing this, honestly

**Comment by ReHoss** [comment]
@napsterv @danilkhromov @mskelton 
Hello, I enjoy using One Dark, but I need a light variant when I work in places with very high ambient luminosity. Is there a way to get the same editor colors setup somehow?

Update: unfortunately, I switched to Gerry Themes since it proposes such a feature. Dracula also implements it.

Best,

**Comment by napsterv** [comment]
For anyone looking for a light theme, as of the time of writing, the Gerry Light theme is the best option. It uses minimal colors and ensures that code doesn’t look unattractive.
