### ISSUE TITLE
UML diagram cannot see clearly

### ISSUE THREAD

**Issue by wangwangdaxian** [one-dark/jetbrains-one-dark-theme#96]
Thanks for your wonderful theme,I have been using it for a long time.

However,there is something weired.When I show UML diagram in IDEA,I got one below,which I cannot see clearly.

![uml_digram](https://user-images.githubusercontent.com/32627085/66734985-b4110f00-ee97-11e9-95d9-69e8b89b2bee.png)

And I cannot find where to change diagrams' color.Please give me some advices.

**Comment by mskelton** [comment]
@wangwangdaxian Thanks for the feedback on the theme!  I'm so happy that others are enjoying this theme 😄 

I don't use the UML diagram, but I did turn it on for a class and took a screenshot and in mine I'm not seeing the odd behavior you are.

![2019-10-14_20-41-38](https://user-images.githubusercontent.com/25914066/66793467-23502880-eec3-11e9-986a-90468f90818a.png)

To help me debug this issue, could you please share what version of IntelliJ you are using?  Thanks!

**Comment by wangwangdaxian** [comment]
@markypython Hi, the IntelliJ on my machine is downloaded from jetbrains toolbox,and its version is 2019.2.3

More:
I just find that it only appers on classes of dependecy package.I write a demo class which implements Serializable interface,and it become like this:

![image](https://user-images.githubusercontent.com/32627085/67007629-69eb9000-f11a-11e9-8d6e-2768c3cbbb23.png)

Below is what the dependecy package looks like:

![image](https://user-images.githubusercontent.com/32627085/67008020-3cebad00-f11b-11e9-8936-13dcc95c71ec.png)

**Comment by mskelton** [comment]
I wasn't able to find a setting to control that, so I opened an issue with IntelliJ to see if I'm missing something.

https://youtrack.jetbrains.com/issue/IDEA-225180

**Comment by wangwangdaxian** [comment]
OK,I'll pay attention to that issue.Thanks for help.😃
